//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.SignalR.Channel
{
    /// <summary>
    /// 通讯测试
    /// </summary>
    public class DemoHub : BaseChannelHub
    {
        public Task Time(DateTime message)
        {
            return this.Clients.SendMessage(new ActionData<DateTime>()
            {
                Action = "Time",
                Data = message
            });
        }

        public Task StringTest(string message)
        {
            return this.Clients.SendMessage(new ActionData<string>()
            {
                Action = "Time",
                Data = message
            });
        }

        public Task ObjectTest(Gksyb.Model.Core.CF_USER message)
        {
            return this.Clients.SendMessage(new ActionData<Gksyb.Model.Core.CF_USER>()
            {
                Action = "Time",
                Data = message
            });
        }

        public Task ObjectTest2(long? userid, string loginname, DateTime ? lastlogintime)
        {
            return this.Clients.SendMessage(new ActionData<string>()
            {
                Action = "Time",
                Data = loginname
            });
        }
    }
}