//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 扩展DTO类ASSET_REPORT_AND_CARD
    /// </summary>
    [Table("ASSET_REPORT_AND_CARD")]
    public class ASSET_REPORT_AND_CARD
    {
        #region ASSET_REPORT 部分
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string REPORT_ID { get; set; }

        /// <summary>
        /// 维修申请记录状态
        /// </summary>
        [Description("维修申请记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_APPLY { get; set; }

        /// <summary>
        /// 维修实施记录状态
        /// </summary>
        [Description("维修实施记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_CHECK { get; set; }

        /// <summary>
        /// 维修验收记录状态
        /// </summary>
        [Description("维修验收记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_ACCEPT { get; set; }

        /// <summary>
        /// 委外维修记录状态
        /// </summary>
        [Description("委外维修记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_OUTSOURCE { get; set; }

        /// <summary>
        /// 修复状态
        /// </summary>
        [Description("修复状态")]
        [Column(DbType = DbType.AnsiString)]
        public string REPORT_STATE { get; set; }

        /// <summary>
        /// IT设备ID
        /// </summary>
        [Description("IT设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_ID { get; set; }

        /// <summary>
        /// 维修申请单号
        /// </summary>
        [Description("维修申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_CODE { get; set; }

        /// <summary>
        /// 维修申请提交时间
        /// </summary>
        [Description("维修申请提交时间")]
        public DateTime? APPLY_DATE { get; set; }

        /// <summary>
        /// 申请部门ID
        /// </summary>
        [Description("申请部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_DEPTID { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_DEPT { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        public long? APPLY_USER_ID { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USER_NAME { get; set; }

        /// <summary>
        /// 申请人联系电话
        /// </summary>
        [Description("申请人联系电话")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_TEL { get; set; }

        /// <summary>
        /// 维修实施提交时间
        /// </summary>
        [Description("维修实施提交时间")]
        public DateTime? CHECK_DATE { get; set; }

        /// <summary>
        /// 验收评价
        /// </summary>
        [Description("验收评价")]
        [Column(DbType = DbType.AnsiString)]
        public string ACCEPT_APPRAISE { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 故障发生时间
        /// </summary>
        [Description("故障发生时间")]
        public DateTime? FAILURE_TIME { get; set; }

        /// <summary>
        /// 故障现象描述
        /// </summary>
        [Description("故障现象描述")]
        [Column(DbType = DbType.AnsiString)]
        public string FAILURE_DESCRIBE { get; set; }

        /// <summary>
        /// 故障原因
        /// </summary>
        [Description("故障原因")]
        [Column(DbType = DbType.AnsiString)]
        public string FAILURE_CAUSE { get; set; }

        /// <summary>
        /// 申请备注
        /// </summary>
        [Description("申请备注")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_MEMO { get; set; }

        /// <summary>
        /// 处理方式
        /// </summary>
        [Description("处理方式")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_METH { get; set; }

        /// <summary>
        /// 处理备注
        /// </summary>
        [Description("处理备注")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_MEMO { get; set; }

        /// <summary>
        /// 验收时间
        /// </summary>
        [Description("验收时间")]
        public DateTime? ACCEPT_DATE { get; set; }

        /// <summary>
        /// 验收情况
        /// </summary>
        [Description("验收情况")]
        [Column(DbType = DbType.AnsiString)]
        public string ACCEPT_DESC { get; set; }

        /// <summary>
        /// 处理部门ID
        /// </summary>
        [Description("处理部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_DEPTID { get; set; }

        /// <summary>
        /// 处理部门
        /// </summary>
        [Description("处理部门")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_DEPT { get; set; }

        /// <summary>
        /// 处理人ID
        /// </summary>
        [Description("处理人ID")]
        public long? CHECK_USERID { get; set; }

        /// <summary>
        /// 处理人
        /// </summary>
        [Description("处理人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_USER { get; set; }

        /// <summary>
        /// 开始处理时间
        /// </summary>
        [Description("开始处理时间")]
        public DateTime? CHECK_BEGIN { get; set; }

        /// <summary>
        /// 结束处理时间
        /// </summary>
        [Description("结束处理时间")]
        public DateTime? CHECK_END { get; set; }

        /// <summary>
        /// 是否在保修期内
        /// </summary>
        [Description("是否在保修期内")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_UNDER_WARRANTY { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER { get; set; }

        /// <summary>
        /// 供应商联系电话
        /// </summary>
        [Description("供应商联系电话")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_TEL { get; set; }

        /// <summary>
        /// 委外备注
        /// </summary>
        [Description("委外备注")]
        [Column(DbType = DbType.AnsiString)]
        public string OUTSOURCE_MEMO { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        public long? CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        public long? MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        #endregion ASSET_REPORT 部分

        #region ASSET_CARD 部分

        /// <summary>
        /// 是否有形资产
        /// </summary>
        [Description("是否有形资产")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_TANGIBLE { get; set; }

        /// <summary>
        /// 记录编码
        /// </summary>
        [Description("记录编码")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_CODE { get; set; }

        /// <summary>
        /// 资产名称
        /// </summary>
        [Description("资产名称")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_NAME { get; set; }

        /// <summary>
        /// 资产简称
        /// </summary>
        [Description("资产简称")]
        [Column(DbType = DbType.AnsiString)]
        public string SHORT_NAME { get; set; }

        /// <summary>
        /// 许可数量
        /// </summary>
        [Description("许可数量")]
        public long? LICENSE_NUM { get; set; }

        /// <summary>
        /// 存放位置
        /// </summary>
        [Description("存放位置")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTALL_SITE { get; set; }

        /// <summary>
        /// 设备类型
        /// </summary>
        [Description("设备类型")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 资产编号
        /// </summary>
        [Description("资产编号")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSETNO { get; set; }

        /// <summary>
        /// 品牌
        /// </summary>
        [Description("品牌")]
        [Column(DbType = DbType.AnsiString)]
        public string BRAND { get; set; }

        /// <summary>
        /// 型号
        /// </summary>
        [Description("型号")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_TYPE { get; set; }

        /// <summary>
        /// 序列号
        /// </summary>
        [Description("序列号")]
        [Column(DbType = DbType.AnsiString)]
        public string SERIAL_NUM { get; set; }

        /// <summary>
        /// 硬件配置信息
        /// </summary>
        [Description("硬件配置信息")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIG_INFO { get; set; }

        /// <summary>
        /// 使用情况
        /// </summary>
        [Description("使用情况")]
        [Column(DbType = DbType.AnsiString)]
        public string USE_STATE { get; set; }

        /// <summary>
        /// 所属域
        /// </summary>
        [Description("所属域")]
        [Column(DbType = DbType.AnsiString)]
        public string DOMAIN { get; set; }

        /// <summary>
        /// 计算机名
        /// </summary>
        [Description("计算机名")]
        [Column(DbType = DbType.AnsiString)]
        public string COMPUTER_NAME { get; set; }

        /// <summary>
        /// IP地址
        /// </summary>
        [Description("IP地址")]
        [Column(DbType = DbType.AnsiString)]
        public string IP_ADDRESS { get; set; }

        /// <summary>
        /// MAC地址
        /// </summary>
        [Description("MAC地址")]
        [Column(DbType = DbType.AnsiString)]
        public string MAC_ADDRESS { get; set; }

        /// <summary>
        /// 外网权限
        /// </summary>
        [Description("外网权限")]
        [Column(DbType = DbType.AnsiString)]
        public string OUTER_NET { get; set; }

        /// <summary>
        /// 采购日期
        /// </summary>
        [Description("采购日期")]
        public DateTime? PUR_DATE { get; set; }

        /// <summary>
        /// 版本
        /// </summary>
        [Description("版本")]
        [Column(DbType = DbType.AnsiString)]
        public string VERSION { get; set; }

        /// <summary>
        /// 资产类型编号
        /// </summary>
        [Description("资产类型编号")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 使用人
        /// </summary>
        [Description("使用人")]
        [Column(DbType = DbType.AnsiString)]
        public string CARD_USER { get; set; }

        /// <summary>
        /// 责任人
        /// </summary>
        [Description("责任人")]
        [Column(DbType = DbType.AnsiString)]
        public string PERSON { get; set; }

        /// <summary>
        /// 管理部门ID
        /// </summary>
        [Description("管理部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MDEPT_ID { get; set; }

        /// <summary>
        /// 管理部门
        /// </summary>
        [Description("管理部门")]
        [Column(DbType = DbType.AnsiString)]
        public string MDEPT_NAME { get; set; }

        /// <summary>
        /// 使用部门ID
        /// </summary>
        [Description("使用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 使用部门
        /// </summary>
        [Description("使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 资产类型ID
        /// </summary>
        [Description("资产类型ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 管理人ID
        /// </summary>
        [Description("管理人ID")]
        public long? MANAGER_USERID { get; set; }

        /// <summary>
        /// 管理人
        /// </summary>
        [Description("管理人")]
        [Column(DbType = DbType.AnsiString)]
        public string MANAGER_USER { get; set; }

        /// <summary>
        /// 操作系统类型
        /// </summary>
        [Description("操作系统类型")]
        [Column(DbType = DbType.AnsiString)]
        public string SYSTEM_TYPE { get; set; }

        /// <summary>
        /// 操作系统版权
        /// </summary>
        [Description("操作系统版权")]
        [Column(DbType = DbType.AnsiString)]
        public string SYSTEM_COPYRIGHT { get; set; }

        /// <summary>
        /// 操作系统备份及存放位置
        /// </summary>
        [Description("操作系统备份及存放位置")]
        [Column(DbType = DbType.AnsiString)]
        public string SYSTEM_BAK { get; set; }

        /// <summary>
        /// 远程连接工具
        /// </summary>
        [Description("远程连接工具")]
        [Column(DbType = DbType.AnsiString)]
        public string REMOTE_TOOL { get; set; }

        /// <summary>
        /// 供应商名
        /// </summary>
        [Description("供应商名")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 产品类型
        /// </summary>
        [Description("产品类型")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCT_TYPE { get; set; }

        #endregion ASSET_CARD 部分
    }
}