//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类BASE_SPCATALOG
    /// </summary>
    [Table("base_spcatalog")]
    public class BASE_SPCATALOG
    {

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }
        
        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }
        
        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }
        
        /// <summary>
        /// 图号
        /// </summary>
        [Description("图号")]
        [Column(DbType = DbType.AnsiString)]
        public string DRAWING_NO { get; set; }
        
        /// <summary>
        /// 物料分类
        /// </summary>
        [Description("物料分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }
        
        /// <summary>
        /// 物料分类ID
        /// </summary>
        [Description("物料分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }
        
        /// <summary>
        /// 物料分类编码
        /// </summary>
        [Description("物料分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }
        
        /// <summary>
        /// ABC分类
        /// </summary>
        [Description("ABC分类")]
        [Column(DbType = DbType.AnsiString)]
        public string ABC_TYPE { get; set; }
        
        /// <summary>
        /// 材质
        /// </summary>
        [Description("材质")]
        [Column(DbType = DbType.AnsiString)]
        public string STUFF { get; set; }
        
        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }
        
        /// <summary>
        /// 计划单价
        /// </summary>
        [Description("计划单价")]
        public decimal? PLAN_PRICE { get; set; }
        
        /// <summary>
        /// 最高储备量
        /// </summary>
        [Description("最高储备量")]
        public decimal? HIGH_NUM { get; set; }
        
        /// <summary>
        /// 最低储备量
        /// </summary>
        [Description("最低储备量")]
        public decimal? LOW_NUM { get; set; }
        
        /// <summary>
        /// 库存数量
        /// </summary>
        [Description("库存数量")]
        public decimal? STORE_NUM { get; set; }
        
        /// <summary>
        /// 库存单价
        /// </summary>
        [Description("库存单价")]
        public decimal? STORE_PRICE { get; set; }
        
        /// <summary>
        /// 库存金额
        /// </summary>
        [Description("库存金额")]
        public decimal? STORE_MONEY { get; set; }
        
        /// <summary>
        /// 是否专用件
        /// </summary>
        [Description("是否专用件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_SPECIAL { get; set; }
        
        /// <summary>
        /// 是否加工件
        /// </summary>
        [Description("是否加工件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_WORK { get; set; }
        
        /// <summary>
        /// 是否标准件
        /// </summary>
        [Description("是否标准件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_STANDARD { get; set; }
        
        /// <summary>
        /// 是否回收
        /// </summary>
        [Description("是否回收")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_RECOVERY { get; set; }
        
        /// <summary>
        /// 是否为备件
        /// </summary>
        [Description("是否为备件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_PARTS { get; set; }
        
        /// <summary>
        /// 是否为工索具
        /// </summary>
        [Description("是否为工索具")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_RIGGING { get; set; }
        
        /// <summary>
        /// 采购周期(天)
        /// </summary>
        [Description("采购周期(天)")]
        public decimal? PUR_PERIOD { get; set; }
        
        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }
        
        /// <summary>
        /// 是否禁用
        /// </summary>
        [Description("是否禁用")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_CANCEL { get; set; }
        
        /// <summary>
        /// 上次入库单价
        /// </summary>
        [Description("上次入库单价")]
        public decimal? LAST_PRICE { get; set; }
        
        /// <summary>
        /// 上次供应商ID
        /// </summary>
        [Description("上次供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string LAST_PROVIDERID { get; set; }
        
        /// <summary>
        /// 上次供应商
        /// </summary>
        [Description("上次供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string LAST_PROVIDER { get; set; }
        
        /// <summary>
        /// 注销人ID
        /// </summary>
        [Description("注销人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CANCEL_USERID { get; set; }
        
        /// <summary>
        /// 注销日期
        /// </summary>
        [Description("注销日期")]
        public DateTime? CANCEL_DATE { get; set; }
        
        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }
        
        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }
        
        /// <summary>
        /// 申请部门ID
        /// </summary>
        [Description("申请部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }
        
        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }
        
        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }
        
        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }
        
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }
        
        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }
        
        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }
        
        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }
        
        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }
        
        /// <summary>
        /// 采购分类ID
        /// </summary>
        [Description("采购分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_ID { get; set; }
        
        /// <summary>
        /// 采购分类
        /// </summary>
        [Description("采购分类")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_NAME { get; set; }
        
        /// <summary>
        /// 上次入库库位
        /// </summary>
        [Description("上次入库库位")]
        [Column(DbType = DbType.AnsiString)]
        public string LAST_STOCK { get; set; }
        
        /// <summary>
        /// 上次入库库位ID
        /// </summary>
        [Description("上次入库库位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string LAST_STOCKID { get; set; }
        
        /// <summary>
        /// 上次采购日期
        /// </summary>
        [Description("上次采购日期")]
        public DateTime? LAST_PUR_DATE { get; set; }
        
        /// <summary>
        /// 质保期
        /// </summary>
        [Description("质保期")]
        public decimal? WARRANTY { get; set; }
        
    }
}