//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{

    /// <summary>
    /// 实体类sp_disable_det
    /// </summary>
    [Table("sp_disable_det")]
    public class SP_DISABLE_DET
    {

        /// <summary>
        /// 物料ID
        /// </summary>
        [Description("物料ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 说明
        /// </summary>
        [Description("说明")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string DISABLE_DET_ID { get; set; }

        /// <summary>
        /// 外键
        /// </summary>
        [Description("外键")]
        [Column(DbType = DbType.AnsiString)]
        public string DISABLE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }

}