//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类sp_enable
    /// </summary>
    [Table("sp_enable")]
    public class SP_ENABLE
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 启用单号
        /// </summary>
        [Description("启用单号")]
        [Column(DbType = DbType.AnsiString)]
        public string ENABLE_CODE { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 部门名称
        /// </summary>
        [Description("部门名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 启用日期
        /// </summary>
        [Description("启用日期")]
        public DateTime? ENABLE_DATE { get; set; }

        /// <summary>
        /// 启用原因
        /// </summary>
        [Description("启用原因")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string ENABLE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }

}