//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;
namespace Gksyb.Model
{
    /// <summary>
    /// 实体类SPARE_APPLY_DET
    /// </summary>
    [Table("SPARE_APPLY_DET")]
    public class SPARE_APPLY_DET
    {
        /// <summary>
        /// 外键
        /// </summary>
        [Description("外键")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string APPLY_DET_ID { get; set; }

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 图号
        /// </summary>
        [Description("图号")]
        [Column(DbType = DbType.AnsiString)]
        public string DRAWING_NO { get; set; }

        /// <summary>
        /// 物料分类ID
        /// </summary>
        [Description("物料分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 物料分类
        /// </summary>
        [Description("物料分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 物料分类编码
        /// </summary>
        [Description("物料分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 材质
        /// </summary>
        [Description("材质")]
        [Column(DbType = DbType.AnsiString)]
        public string STUFF { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 是否专用件
        /// </summary>
        [Description("是否专用件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_SPECIAL { get; set; }

        /// <summary>
        /// 是否加工件
        /// </summary>
        [Description("是否加工件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_WORK { get; set; }

        /// <summary>
        /// 是否标准件
        /// </summary>
        [Description("是否标准件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_STANDARD { get; set; }

        /// <summary>
        /// 是否回收
        /// </summary>
        [Description("是否回收")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_RECOVERY { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

        /// <summary>
        /// 编制人
        /// </summary>
        [Description("编制人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 编制日期
        /// </summary>
        [Description("编制日期")]
        public DateTime? EDIT_DATE { get; set; }

        /// <summary>
        /// 编制人ID
        /// </summary>
        [Description("编制人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 采购分类ID
        /// </summary>
        [Description("采购分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_ID { get; set; }

        /// <summary>
        /// 采购分类
        /// </summary>
        [Description("采购分类")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_NAME { get; set; }

        /// <summary>
        /// 是否停用
        /// </summary>
        [Description("是否停用")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_STOP { get; set; }

        /// <summary>
        /// 是否工索具
        /// </summary>
        [Description("是否工索具")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_RIGGING { get; set; }

    }
}