<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RuntimeIdentifiers>win-x64;linux-x64;win-x86;</RuntimeIdentifiers>
	</PropertyGroup>

	<PropertyGroup Condition="'1'=='1'">
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Services\FileName.cs" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Gksyb.Common\Gksyb.Common.csproj" />
		<ProjectReference Include="..\Gksyb.Core\Gksyb.Core.csproj" />
		<ProjectReference Include="..\Gksyb.Model\Gksyb.Model.csproj" />
		<ProjectReference Include="..\Gksyb.Server\Gksyb.Server.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Chloe">
			<HintPath>..\dll\Chloe.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
