<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
		<NoWarn>$(NoWarn);1591;</NoWarn>
		<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
		<SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="wwwroot\code-gen\**;wwwroot\UploadDirectory\**" />
		<None Include="wwwroot\code-gen\**;wwwroot\UploadDirectory\**" />
		<Content Remove="wwwroot\lib\eui\css\**;wwwroot\lib\eui\js\**" />
		<None Include="wwwroot\lib\eui\css\**;wwwroot\lib\eui\js\**" />
		<Content Remove="wwwroot\lib\jquery\jquery.all.js" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.21" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="6.0.21" />
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Gksyb.Common\Gksyb.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Chloe">
			<HintPath>..\dll\Chloe.dll</HintPath>
		</Reference>
	</ItemGroup>

	<!--基础库-->
	<ItemGroup>
		<PluginBaseProject Include="..\Gksyb.Model\Gksyb.Model.csproj" />
		<PluginBaseProject Include="..\Gksyb.Core\Gksyb.Core.csproj" />
	</ItemGroup>
	<!--插件-->
	<ItemGroup>
		<PluginPublishProject Include="..\Gksyb.Server\Gksyb.Server.csproj" />
		<PluginPublishProject Include="..\Gksyb.Workflow\Gksyb.Workflow.csproj" />
		<PluginPublishProject Include="..\EAM.Device\EAM.Device.csproj" />
		<PluginPublishProject Include="..\EAM.Repair\EAM.Repair.csproj" />
		<PluginPublishProject Include="..\EAM.Material\EAM.Material.csproj" />
		<PluginPublishProject Include="..\EAM.Special\EAM.Special.csproj" />
		<PluginPublishProject Include="..\EAM.Energy\EAM.Energy.csproj" />
	</ItemGroup>
	<!--自定义生成-->
	<PropertyGroup>
		<PluginTarget>Build</PluginTarget>
		<PluginProperties>WarningsAsErrors=false;SatelliteResourceLanguages=zh-Hans;Configuration=$(Configuration); Platform=$(Platform);TargetFramework=$(TargetFramework);</PluginProperties>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<PluginTarget>Rebuild</PluginTarget>
	</PropertyGroup>
	<Target Name="PluginRebuild" BeforeTargets="BeforeRebuild">
		<PropertyGroup>
			<PluginTarget>Rebuild</PluginTarget>
		</PropertyGroup>
	</Target>
	<Target Name="PluginClean" AfterTargets="BeforeClean">
		<Message Text="清理插件" Importance="high" />
		<MSBuild Projects="@(ProjectReference);@(PluginBaseProject);@(PluginPublishProject)" Targets="Clean" BuildInParallel="true" Properties="$(PluginProperties)" />
	</Target>
	<Target Name="PluginBase" AfterTargets="BeforeBuild">
		<RemoveDir Directories="$(TargetDir)" ContinueOnError="true" />
		<Message Text="开始$(PluginTarget)基础库：$(PluginProperties)" Importance="high" />
		<MSBuild Projects="@(ProjectReference);@(PluginBaseProject)" Targets="$(PluginTarget)" Properties="$(PluginProperties)" />
		<Message Text="开始$(PluginTarget)插件：$(PluginProperties)" Importance="high" />
		<MSBuild Projects="@(PluginPublishProject)" Targets="$(PluginTarget)" BuildInParallel="true" Properties="$(PluginProperties)">
			<Output ItemName="GeneratedFiles" TaskParameter="TargetOutputs" />
		</MSBuild>
		<ItemGroup>
			<PluginFiles Include="%(GeneratedFiles.RelativeDir)*.dll;%(GeneratedFiles.RelativeDir)*.pdb;%(GeneratedFiles.RelativeDir)*.xml"></PluginFiles>
		</ItemGroup>
		<MSBuild Projects="$(MSBuildProjectFullPath)" Targets="ResolveReferences">
			<Output TaskParameter="TargetOutputs" ItemName="MainResolvedFiles" />
		</MSBuild>
		<MSBuild Projects="@(PluginBaseProject);@(PluginPublishProject)" Targets="ResolveReferences" Properties="$(PluginProperties)">
			<Output TaskParameter="TargetOutputs" ItemName="PluginResolvedFiles" />
		</MSBuild>
		<ItemGroup>
			<ResolvedFiles Include="@(PluginResolvedFiles)" Exclude="@(MainResolvedFiles)"></ResolvedFiles>
		</ItemGroup>
		<Copy SourceFiles="@(PluginFiles);@(ResolvedFiles);" DestinationFolder="$(TargetDir)\plugins\" />
	</Target>
	<Target Name="RemoveDLL" AfterTargets="Build">
		<Message Text="清理多余的dll" Importance="high" />
		<ItemGroup>
			<AboveFile Include="$(TargetDir)\*.*"></AboveFile>
		</ItemGroup>
		<Delete Files="@(AboveFile->'$(TargetDir)\plugins\%(filename)%(extension)')" />
	</Target>
	<Target Name="CorpPlugins" AfterTargets="Publish">
		<Message Text="开始发布插件" Importance="high" />
		<ItemGroup>
			<PublishFile Include="$(TargetDir)\plugins\*.dll;$(TargetDir)\plugins\*.pdb;$(TargetDir)\plugins\*.xml;"></PublishFile>
		</ItemGroup>
		<Copy SourceFiles="@(PublishFile)" DestinationFolder="$(PublishDir)\plugins\" />
	</Target>

</Project>