//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类build_count
    /// </summary>
    [Table("build_count")]
    public class BUILD_COUNT
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string BUILD_ID { get; set; }

        /// <summary>
        /// 日期
        /// </summary>
        [Description("日期")]
        public DateTime STARTDATE { get; set; }

        /// <summary>
        /// 船次
        /// </summary>
        [Description("船次")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIPTIMES { get; set; }

        /// <summary>
        /// 船方
        /// </summary>
        [Description("船方")]
        public int? SHIPNUM { get; set; }

        /// <summary>
        /// 施工准备
        /// </summary>
        [Description("施工准备")]
        [Column(DbType = DbType.AnsiString)]
        public string CONPLAN { get; set; }

        /// <summary>
        /// 挖泥时间
        /// </summary>
        [Description("挖泥时间")]
        public decimal? DREDGETIME { get; set; }

        /// <summary>
        /// 航行时间
        /// </summary>
        [Description("航行时间")]
        public decimal? SAILTIME { get; set; }

        /// <summary>
        /// 检修时间
        /// </summary>
        [Description("检修时间")]
        public decimal? REPAIRTIME { get; set; }

        /// <summary>
        /// 天气影响
        /// </summary>
        [Description("天气影响")]
        public decimal? WEATHEREFFECT { get; set; }

        /// <summary>
        /// 其他停工
        /// </summary>
        [Description("其他停工")]
        public decimal? OTHERSTOP { get; set; }

        /// <summary>
        /// 日耗
        /// </summary>
        [Description("日耗")]
        public int? DAILYCONSUMPTION { get; set; }

        /// <summary>
        /// 补充
        /// </summary>
        [Description("补充")]
        public int? SUPPLEMENT { get; set; }

        /// <summary>
        /// 库存
        /// </summary>
        [Description("库存")]
        public int? STOCK { get; set; }

        /// <summary>
        /// 主机日耗
        /// </summary>
        [Description("主机日耗")]
        public decimal? MASTER { get; set; }

        /// <summary>
        /// 辅机日耗
        /// </summary>
        [Description("辅机日耗")]
        public decimal? AUXILIARY { get; set; }

        /// <summary>
        /// 泵机日耗
        /// </summary>
        [Description("泵机日耗")]
        public decimal? PUMP { get; set; }

        /// <summary>
        /// 小计
        /// </summary>
        [Description("小计")]
        public decimal? SUBTOTAL { get; set; }

        /// <summary>
        /// 补充
        /// </summary>
        [Description("补充")]
        public int? SUPPLEMENT2 { get; set; }

        /// <summary>
        /// 库存
        /// </summary>
        [Description("库存")]
        public int? STOCK2 { get; set; }

        /// <summary>
        /// 滑油日耗
        /// </summary>
        [Description("滑油日耗")]
        public decimal? LUBRICATE { get; set; }

        /// <summary>
        /// 简要说明
        /// </summary>
        [Description("简要说明")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 运转时间
        /// </summary>
        [Description("运转时间")]
        public decimal? RUNTIME { get; set; }

        /// <summary>
        /// 停工时间
        /// </summary>
        [Description("停工时间")]
        public decimal? STOPTIME { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 添加人姓名
        /// </summary>
        [Description("添加人姓名")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERNAME { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 修改人姓名
        /// </summary>
        [Description("修改人姓名")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERNAME { get; set; }

        /// <summary>
        /// 关联设备ID
        /// </summary>
        [Description("关联设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 船舶名称
        /// </summary>
        [Description("船舶名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

    }
}