//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// DRUG_LIMIT
    /// </summary>
    [Table("DRUG_LIMIT")]
    public class DRUG_LIMIT
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string LIMIT_ID { get; set; }

        /// <summary>
        /// 物资ID
        /// </summary>
        [Description("物资ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 物资编号
        /// </summary>
        [Description("物资编号")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物资名称
        /// </summary>
        [Description("物资名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 物资型号
        /// </summary>
        [Description("物资型号")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_TYPE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 港内限制数量(4月）
        /// </summary>
        [Description("港内限制数量(4月）")]
        public decimal? INSIDE_APRIL { get; set; }

        /// <summary>
        /// 港外限制数量(4月）
        /// </summary>
        [Description("港外限制数量(4月）")]
        public decimal? OUTSIDE_APRIL { get; set; }

        /// <summary>
        /// 港内限制数量(10月）
        /// </summary>
        [Description("港内限制数量(10月）")]
        public decimal? INSIDE_OCTOBER { get; set; }

        /// <summary>
        /// 港外限制数量(10月）
        /// </summary>
        [Description("港外限制数量(10月）")]
        public decimal? OUTSIDE_OCTOBER { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        public long? CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        public long? MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}