//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类labor_user
    /// </summary>
    [Table("labor_user")]
    public class LABOR_USER
    {

        /// <summary>
        /// 人员编码
        /// </summary>
        [Description("人员编码")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_CODE { get; set; }

        /// <summary>
        /// 姓名
        /// </summary>
        [Description("姓名")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }

        /// <summary>
        /// 部门编码
        /// </summary>
        [Description("部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 部门名称
        /// </summary>
        [Description("部门名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 人员ID
        /// </summary>
        [Description("人员ID")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 是否注销
        /// </summary>
        [Description("是否注销")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_NOVALID { get; set; }

        /// <summary>
        /// 性别
        /// </summary>
        [Description("性别")]
        [Column(DbType = DbType.AnsiString)]
        public string SEX { get; set; }

        /// <summary>
        /// 生日
        /// </summary>
        [Description("生日")]
        public DateTime? BIRTHDAY { get; set; }

        /// <summary>
        /// 生产系统人员ID
        /// </summary>
        [Description("生产系统人员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_SID { get; set; }

    }
}