//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类labor_request
    /// </summary>
    [Table("labor_request")]
    public class labor_request
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 需求计划单号
        /// </summary>
        [Description("需求计划单号")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_CODE { get; set; }

        /// <summary>
        /// 申请日期
        /// </summary>
        [Description("申请日期")]
        public DateTime? REQUEST_DATE { get; set; }

        /// <summary>
        /// 所属月份
        /// </summary>
        [Description("所属月份")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_MONTH { get; set; }

        /// <summary>
        /// 所属年份
        /// </summary>
        [Description("所属年份")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_YEAR { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_USER { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_USERID { get; set; }

        /// <summary>
        /// 申请部门编号
        /// </summary>
        [Description("申请部门编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 申请部门ID
        /// </summary>
        [Description("申请部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 物资归属船舶
        /// </summary>
        [Description("物资归属船舶")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_NAME { get; set; }

        /// <summary>
        /// 物资归属船舶ID
        /// </summary>
        [Description("物资归属船舶ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_ID { get; set; }

        /// <summary>
        /// 物资归属船舶编码
        /// </summary>
        [Description("物资归属船舶编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_CODE { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 类别
        /// </summary>
        [Description("类别")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_TYPE { get; set; }

        /// <summary>
        /// 格式号
        /// </summary>
        [Description("格式号")]
        [Column(DbType = DbType.AnsiString)]
        public string FORM_ID { get; set; }

        /// <summary>
        /// 需求分类
        /// </summary>
        [Description("需求分类")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_SPTYPE { get; set; }

        /// <summary>
        /// 来源单号
        /// </summary>
        [Description("来源单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_CODE { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string REQUEST_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}