//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类labor_rent
    /// </summary>
    [Table("labor_rent")]
    public class LABOR_RENT
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 租借单号
        /// </summary>
        [Description("租借单号")]
        [Column(DbType = DbType.AnsiString)]
        public string RENT_CODE { get; set; }

        /// <summary>
        /// 租借日期
        /// </summary>
        [Description("租借日期")]
        public DateTime? RENT_DATE { get; set; }

        /// <summary>
        /// 租借部门
        /// </summary>
        [Description("租借部门")]
        [Column(DbType = DbType.AnsiString)]
        public string RENT_DEPT { get; set; }

        /// <summary>
        /// 租借人
        /// </summary>
        [Description("租借人")]
        [Column(DbType = DbType.AnsiString)]
        public string RENT_USER { get; set; }

        /// <summary>
        /// 经办部门
        /// </summary>
        [Description("经办部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 经办人
        /// </summary>
        [Description("经办人")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }

        /// <summary>
        /// 租借开始日期
        /// </summary>
        [Description("租借开始日期")]
        public DateTime? BEGIN_DATE { get; set; }

        /// <summary>
        /// 租借结束日期
        /// </summary>
        [Description("租借结束日期")]
        public DateTime? END_DATE { get; set; }

        /// <summary>
        /// 租借原因
        /// </summary>
        [Description("租借原因")]
        [Column(DbType = DbType.AnsiString)]
        public string RENT_REASON { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string RENT_ID { get; set; }

        /// <summary>
        /// 租借部门ID
        /// </summary>
        [Description("租借部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string RENT_DEPTID { get; set; }

        /// <summary>
        /// 租借人ID
        /// </summary>
        [Description("租借人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string RENT_USERID { get; set; }

        /// <summary>
        /// 经办部门ID
        /// </summary>
        [Description("经办部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 经办人ID
        /// </summary>
        [Description("经办人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 预计结束日期
        /// </summary>
        [Description("预计结束日期")]
        public DateTime? EXPEND_DATE { get; set; }

        /// <summary>
        /// 租借状态
        /// </summary>
        [Description("租借状态")]
        [Column(DbType = DbType.AnsiString)]
        public string RENT_STATUS { get; set; }

    }
}