//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类labor_in
    /// </summary>
    [Table("labor_in")]
    public class LABOR_IN
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 采购结果确认单号
        /// </summary>
        [Description("采购结果确认单号")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_CODE { get; set; }

        /// <summary>
        /// 采购人
        /// </summary>
        [Description("采购人")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_USER { get; set; }

        /// <summary>
        /// 采购人ID
        /// </summary>
        [Description("采购人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_USERID { get; set; }

        /// <summary>
        /// 确认部门
        /// </summary>
        [Description("确认部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 确认部门ID
        /// </summary>
        [Description("确认部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 供应商编码
        /// </summary>
        [Description("供应商编码")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_CODE { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 供应商ID
        /// </summary>
        [Description("供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 仓库货位编码
        /// </summary>
        [Description("仓库货位编码")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_CODE { get; set; }

        /// <summary>
        /// 仓库货位名称
        /// </summary>
        [Description("仓库货位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 仓库货位ID
        /// </summary>
        [Description("仓库货位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 发票号
        /// </summary>
        [Description("发票号")]
        [Column(DbType = DbType.AnsiString)]
        public string INVOICE_NO { get; set; }

        /// <summary>
        /// 库存方式
        /// </summary>
        [Description("库存方式")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_TYPE { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 含税总金额(元)
        /// </summary>
        [Description("含税总金额(元)")]
        public decimal? TAX_MONEY { get; set; }

        /// <summary>
        /// 不含税总金额(元)
        /// </summary>
        [Description("不含税总金额(元)")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 入库单号
        /// </summary>
        [Description("入库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string IN_CODE { get; set; }

        /// <summary>
        /// 入库日期
        /// </summary>
        [Description("入库日期")]
        public DateTime? IN_DATE { get; set; }

        /// <summary>
        /// 仓管员
        /// </summary>
        [Description("仓管员")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_USER { get; set; }

        /// <summary>
        /// 仓管员ID
        /// </summary>
        [Description("仓管员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_USERID { get; set; }

        /// <summary>
        /// 入库金额
        /// </summary>
        [Description("入库金额")]
        public decimal? IN_MONEY { get; set; }

        /// <summary>
        /// 税率(%)
        /// </summary>
        [Description("税率(%)")]
        public decimal? RATIO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string IN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 确认单ID
        /// </summary>
        [Description("确认单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_ID { get; set; }

        /// <summary>
        /// 确认人ID
        /// </summary>
        [Description("确认人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_USERID { get; set; }

        /// <summary>
        /// 确认人
        /// </summary>
        [Description("确认人")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_USER { get; set; }

    }
}