//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类labor_out
    /// </summary>
    [Table("labor_out")]
    public class LABOR_OUT
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 出库单号
        /// </summary>
        [Description("出库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_CODE { get; set; }

        /// <summary>
        /// 领用人
        /// </summary>
        [Description("领用人")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_USER { get; set; }

        /// <summary>
        /// 领用人ID
        /// </summary>
        [Description("领用人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_USERID { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 申请部门ID
        /// </summary>
        [Description("申请部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        [Description("仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 仓库编码
        /// </summary>
        [Description("仓库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_CODE { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 出库日期
        /// </summary>
        [Description("出库日期")]
        public DateTime? OUT_DATE { get; set; }

        /// <summary>
        /// 仓管员
        /// </summary>
        [Description("仓管员")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_USER { get; set; }

        /// <summary>
        /// 仓管员ID
        /// </summary>
        [Description("仓管员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_USERID { get; set; }

        /// <summary>
        /// 出库用途
        /// </summary>
        [Description("出库用途")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_USE { get; set; }

        /// <summary>
        /// 出库类型
        /// </summary>
        [Description("出库类型")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_TYPE { get; set; }

        /// <summary>
        /// 出库不含税金额(元)
        /// </summary>
        [Description("出库不含税金额(元)")]
        public decimal? TAX_MONEY { get; set; }

        /// <summary>
        /// 出库含税金额(元)
        /// </summary>
        [Description("出库含税金额(元)")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string OUT_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USERID { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USER { get; set; }

    }
}