//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类spec_lowspare_scrap
    /// </summary>
    [Table("SPEC_LOWSPARE_SCRAP")]
    public class SPEC_LOWSPARE_SCRAP
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }
        
        /// <summary>
        /// 报废单号
        /// </summary>
        [Description("报废单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SCRAP_CODE { get; set; }
        
        /// <summary>
        /// 报废日期
        /// </summary>
        [Description("报废日期")]
        public DateTime? SCRAP_DATE { get; set; }
        
        /// <summary>
        /// 备件品种编码
        /// </summary>
        [Description("备件品种编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }
        
        /// <summary>
        /// 备件品种名称
        /// </summary>
        [Description("备件品种名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }
        
        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }
        
        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }
        
        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }
        
        /// <summary>
        /// 制造厂
        /// </summary>
        [Description("制造厂")]
        [Column(DbType = DbType.AnsiString)]
        public string FACTORY { get; set; }
        
        /// <summary>
        /// 其他编号
        /// </summary>
        [Description("其他编号")]
        [Column(DbType = DbType.AnsiString)]
        public string OTHER_CODE { get; set; }
        
        /// <summary>
        /// 备件类别
        /// </summary>
        [Description("备件类别")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }
        
        /// <summary>
        /// 低值类别
        /// </summary>
        [Description("低值类别")]
        [Column(DbType = DbType.AnsiString)]
        public string LOW_TYPE { get; set; }
        
        /// <summary>
        /// 保管人
        /// </summary>
        [Description("保管人")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }
        
        /// <summary>
        /// 使用部门
        /// </summary>
        [Description("使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }
        
        /// <summary>
        /// 存放地点
        /// </summary>
        [Description("存放地点")]
        [Column(DbType = DbType.AnsiString)]
        public string LOCATION { get; set; }
        
        /// <summary>
        /// 办理人
        /// </summary>
        [Description("办理人")]
        [Column(DbType = DbType.AnsiString)]
        public string HANDLE_USER { get; set; }
        
        /// <summary>
        /// 台账数量
        /// </summary>
        [Description("台账数量")]
        public decimal? LOWSPARE_NUM { get; set; }
        
        /// <summary>
        /// 报废数量
        /// </summary>
        [Description("报废数量")]
        public decimal? SCRAP_NUM { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }
        
        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }
        
        /// <summary>
        /// 使用部门ID
        /// </summary>
        [Description("使用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }
        
        /// <summary>
        /// 办理人ID
        /// </summary>
        [Description("办理人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HANDLE_USERID { get; set; }
        
        /// <summary>
        /// 保管人ID
        /// </summary>
        [Description("保管人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }
        
        /// <summary>
        /// 低值品ID
        /// </summary>
        [Description("低值品ID")]
        [Column(DbType = DbType.AnsiString)]
        public string LOWSPARE_ID { get; set; }
        
        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }
        
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string SCRAP_ID { get; set; }
        
        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }
        
        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }
        
        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }
        
        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }
        
        /// <summary>
        /// 系统租户ID
        /// </summary>
        [Description("系统租户ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TENANT_ID { get; set; }
        
        /// <summary>
        /// 备件id
        /// </summary>
        [Description("备件id")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }
        
    }
}