//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类BASE_DOCK
    /// </summary>
    [Table("BASE_DOCK")]
    public class BASE_DOCK
    {

        /// <summary>
        /// 码头编号
        /// </summary>
        [Description("码头编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DOCK_CODE { get; set; }

        /// <summary>
        /// 码头名称
        /// </summary>
        [Description("码头名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DOCK_NAME { get; set; }

        /// <summary>
        /// 码头地址
        /// </summary>
        [Description("码头地址")]
        [Column(DbType = DbType.AnsiString)]
        public string DOCK_ADDRESS { get; set; }

        /// <summary>
        /// 编辑人
        /// </summary>
        [Description("编辑人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 编辑人ID
        /// </summary>
        [Description("编辑人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string DOCK_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 编辑日期
        /// </summary>
        [Description("编辑日期")]
        public DateTime? EDIT_DATE { get; set; }

    }
}