//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类BC_CODE
    /// </summary>
    public class BC_CODE
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString, Size = 11)]
        public string SID { get; set; }

        /// <summary>
        /// 类型
        /// </summary>
        [Description("类型")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string CODE_TYPE { get; set; }

        /// <summary>
        /// 编码
        /// </summary>
        [Description("编码")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string CODE_EN { get; set; }

        /// <summary>
        /// 名称
        /// </summary>
        [Description("名称")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string CODE_CN { get; set; }

        /// <summary>
        /// 顺序
        /// </summary>
        [Description("顺序")]
        public int? CODE_SEQ { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string REMARK { get; set; }

    }
}