//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_CONFIGURATION
    /// </summary>
    [Table("CF_CONFIGURATION")]
    [Description("配置")]
    public class CF_CONFIGURATION
    {

        /// <summary>
        /// 配置ID
        /// </summary>
        [Description("配置ID")]
        [Column(IsPrimaryKey = true)]
        [AutoIncrement]
        public long? CONFIGID { get; set; }

        /// <summary>
        /// 表名
        /// </summary>
        [Description("表名")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string VIEWS { get; set; }

        /// <summary>
        /// 表格json
        /// </summary>
        [Description("表格json")]
        [Column(DbType = DbType.AnsiString, Size = int.MaxValue)]
        public string GRID { get; set; }

        /// <summary>
        /// 查询json
        /// </summary>
        [Description("查询json")]
        [Column(DbType = DbType.AnsiString, Size = int.MaxValue)]
        public string SEARCH { get; set; }

        /// <summary>
        /// 表单json
        /// </summary>
        [Description("表单json")]
        [Column(DbType = DbType.AnsiString, Size = int.MaxValue)]
        public string FORM { get; set; }

        /// <summary>
        /// 程序名称
        /// </summary>
        [Description("程序名称")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string APPNAME { get; set; }

    }
}