//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_FAVORITE
    /// </summary>
    [Table("CF_FAVORITE")]
    [Description("收藏")]
    public class CF_FAVORITE
    {

        /// <summary>
        /// 收藏ID
        /// </summary>
        [Description("收藏ID")]
        [Column(IsPrimaryKey = true)]
        [AutoIncrement]
        public long? FAVORITEID { get; set; }

        /// <summary>
        /// 收藏名称
        /// </summary>
        [Description("收藏名称")]
        [Column(DbType = DbType.String)]
        public string FAVORITETITLE { get; set; }

        /// <summary>
        /// 收藏创建时间
        /// </summary>
        [Description("收藏创建时间")]
        public DateTime? FAVORITEADDTIME { get; set; }

        /// <summary>
        /// 收藏内容
        /// </summary>
        [Description("收藏内容")]
        [Column(DbType = DbType.String)]
        public string FAVORITECONTENT { get; set; }

        /// <summary>
        /// 所属用户
        /// </summary>
        [Description("所属用户")]
        public long? USERID { get; set; }

        /// <summary>
        /// 链接
        /// </summary>
        [Description("链接")]
        [Column(DbType = DbType.AnsiString)]
        public string URL { get; set; }

        /// <summary>
        /// 图标
        /// </summary>
        [Description("图标")]
        [Column(DbType = DbType.AnsiString)]
        public string ICON { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.String)]
        public string APPNAME { get; set; }

    }
}