//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_FAVORITE_TJ
    /// </summary>
    [NotDbLog]
    [Table("CF_FAVORITE_TJ")]
    public class CF_FAVORITE_TJ
    {

        /// <summary>
        /// 点击ID
        /// </summary>
        [Description("点击ID")]
        [Column(IsPrimaryKey = true)]
        public long? CLICKID { get; set; }

        /// <summary>
        /// 收藏名称
        /// </summary>
        [Description("收藏名称")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string FAVORITETITLE { get; set; }

        /// <summary>
        /// 收藏内容
        /// </summary>
        [Description("收藏内容")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string FAVORITECONTENT { get; set; }

        /// <summary>
        /// 所属用户
        /// </summary>
        [Description("所属用户")]
        public long? USERID { get; set; }

        /// <summary>
        /// 链接
        /// </summary>
        [Description("链接")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string URL { get; set; }

        /// <summary>
        /// 图标
        /// </summary>
        [Description("图标")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string ICON { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string APPNAME { get; set; }

        /// <summary>
        /// 点击次数
        /// </summary>
        [Description("点击次数")]
        public long? CLICKNUM { get; set; }

        /// <summary>
        /// 统计月份
        /// </summary>
        [Description("统计月份")]
        [Column(DbType = DbType.AnsiString, Size = 10)]
        public string TJ_MONTH { get; set; }

        /// <summary>
        /// 账号
        /// </summary>
        [Description("账号")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string USERNAME { get; set; }

    }
}