//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_PRIVILEGE
    /// </summary>
    [Table("CF_PRIVILEGE")]
    [Description("权限")]
    public class CF_PRIVILEGE
    {

        /// <summary>
        /// 权限ID
        /// </summary>
        [Description("权限ID")]
        [Column(IsPrimaryKey = true)]
        [AutoIncrement]
        public long? PRIVILEGEID { get; set; }

        /// <summary>
        /// 权限拥有者
        /// </summary>
        [Description("权限拥有者")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string PRIVILEGEMASTER { get; set; }

        /// <summary>
        /// 权限拥有者ID
        /// </summary>
        [Description("权限拥有者ID")]
        [Column(DbType = DbType.String, Size = 100)]
        public string PRIVILEGEMASTERKEY { get; set; }

        /// <summary>
        /// 拥有权限
        /// </summary>
        [Description("拥有权限")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string PRIVILEGEACCESS { get; set; }

        /// <summary>
        /// 拥有权限ID
        /// </summary>
        [Description("拥有权限ID")]
        [Column(DbType = DbType.String, Size = 100)]
        public string PRIVILEGEACCESSKEY { get; set; }

        /// <summary>
        /// 是否拥有
        /// </summary>
        [Description("是否拥有")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string PRIVILEGEOPERATION { get; set; }

        /// <summary>
        /// 创建者
        /// </summary>
        [Description("创建者")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 创建日期
        /// </summary>
        [Description("创建日期")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 最后修改人
        /// </summary>
        [Description("最后修改人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// 修改之间
        /// </summary>
        [Description("修改之间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.String, Size = 100)]
        public string RECORDSTATUS { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.String, Size = 100)]
        public string APPNAME { get; set; }

    }
}