//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_USER_LOG
    /// </summary>
    [NotDbLog]
    [Table("CF_USER_LOG")]
    public class CF_USER_LOG
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true)]
        public long? ID { get; set; }

        /// <summary>
        /// 日志类型
        /// </summary>
        [Description("日志类型")]
        [Column(DbType = DbType.AnsiString)]
        public string LOGTYPE { get; set; }

        /// <summary>
        /// 日志标题
        /// </summary>
        [Description("日志标题")]
        [Column(DbType = DbType.AnsiString)]
        public string LOGTITLE { get; set; }

        /// <summary>
        /// 日志摘要
        /// </summary>
        [Description("日志摘要")]
        [Column(DbType = DbType.AnsiString)]
        public string LOGSUMMARY { get; set; }

        /// <summary>
        /// 登录名称/工号
        /// </summary>
        [Description("登录名称/工号")]
        [Column(DbType = DbType.AnsiString)]
        public string LOGINNAME { get; set; }

        /// <summary>
        /// 登录日期
        /// </summary>
        [Description("登录日期")]
        public DateTime? LOGINDATE { get; set; }

        /// <summary>
        /// IP
        /// </summary>
        [Description("IP")]
        [Column(DbType = DbType.AnsiString)]
        public string IP { get; set; }

        /// <summary>
        /// 浏览器
        /// </summary>
        [Description("浏览器")]
        [Column(DbType = DbType.AnsiString)]
        public string UA { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.AnsiString)]
        public string APPNAME { get; set; }

    }
}