//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_USER_PORT
    /// </summary>
    [Table("CF_USER_PORT")]
    [Description("用户扩展")]
    public class CF_USER_PORT
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true)]
        [AutoIncrement]
        public long? USERPORTID { get; set; }

        /// <summary>
        /// 登录名称/工号
        /// </summary>
        [Description("登录名称/工号")]
        [Column(DbType = DbType.AnsiString)]
        public string LOGINNAME { get; set; }

        /// <summary>
        /// 组织
        /// </summary>
        [Description("组织")]
        [Column(DbType = DbType.String)]
        public string CORPID { get; set; }

        /// <summary>
        /// 分类（业务、生产）
        /// </summary>
        [Description("分类（业务、生产）")]
        [Column(DbType = DbType.String)]
        public string OPTYPE { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.String)]
        public string APPNAME { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string REMARK { get; set; }

        /// <summary>
        /// 登记人员@#Create User
        /// </summary>
        [Description("登记人员")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 登记时间
        /// </summary>
        [Description("登记时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 最后修改人
        /// </summary>
        [Description("最后修改人")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// 最后修改时间
        /// </summary>
        [Description("最后修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}