//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_USER
    /// </summary>
    [Table("CF_USER")]
    [Description("用户")]
    public partial class CF_USER
    {

        /// <summary>
        /// 用户ID
        /// </summary>
        [Description("用户ID")]
        [Column(IsPrimaryKey = true)]
        [AutoIncrement]
        public long? USERID { get; set; }

        /// <summary>
        /// 登录名称/工号
        /// </summary>
        [Description("登录名称/工号")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string LOGINNAME { get; set; }

        /// <summary>
        /// 登录密码
        /// </summary>
        [Description("登录密码")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string LOGINPASSWORD { get; set; }

        /// <summary>
        /// 密码过期时间
        /// </summary>
        [Description("密码过期时间")]
        public long? SUPPLIERID { get; set; }

        /// <summary>
        /// 真实姓名
        /// </summary>
        [Description("真实姓名")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string REALNAME { get; set; }

        /// <summary>
        /// 显示名称
        /// </summary>
        [Description("显示名称")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string TITLE { get; set; }

        /// <summary>
        /// 性别
        /// </summary>
        [Description("性别")]
        [Column(DbType = DbType.AnsiString, Size = 8)]
        public string SEX { get; set; }

        /// <summary>
        /// 电话
        /// </summary>
        [Description("电话")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string PHONE { get; set; }

        /// <summary>
        /// IP
        /// </summary>
        [Description("IP")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string FAX { get; set; }

        /// <summary>
        /// 邮件
        /// </summary>
        [Description("邮件")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string EMAIL { get; set; }

        /// <summary>
        /// QQ
        /// </summary>
        [Description("QQ")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string QQ { get; set; }

        /// <summary>
        /// 昵称
        /// </summary>
        [Description("昵称")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string NICKNAME { get; set; }

        /// <summary>
        /// UA
        /// </summary>
        [Description("UA")]
        [Column(DbType = DbType.AnsiString, Size = 4000)]
        public string ADDRESS { get; set; }

        /// <summary>
        /// 最后登录时间
        /// </summary>
        [Description("最后登录时间")]
        public DateTime? LASTLOGINTIME { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 创建日期
        /// </summary>
        [Description("创建日期")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 最后修改人
        /// </summary>
        [Description("最后修改人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// 修改日期
        /// </summary>
        [Description("修改日期")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string RECORDSTATUS { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string APPNAME { get; set; }

        /// <summary>
        /// 有效否
        /// </summary>
        [Description("有效否")]
        [Column(DbType = DbType.AnsiString, Size = 1)]
        public string FLAG { get; set; }

        /// <summary>
        /// 工号
        /// </summary>
        [Description("工号")]
        [Column(DbType = DbType.AnsiString, Size = 20)]
        public string DEPARTCODE { get; set; }

        /// <summary>
        /// 所属组
        /// </summary>
        [Description("所属组")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string STATION { get; set; }

        /// <summary>
        /// 班组
        /// </summary>
        [Description("班组")]
        [Column(DbType = DbType.AnsiString, Size = 1)]
        public string CLASS { get; set; }

        /// <summary>
        /// 作业区
        /// </summary>
        [Description("作业区")]
        [Column(DbType = DbType.AnsiString, Size = 30)]
        public string C_TERMINAL { get; set; }

    }
}