//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类REP_DOCK_PLAN
    /// </summary>
    [Table("REP_DOCK_PLAN")]
    public class REP_DOCK_PLAN
    {

        /// <summary>
        /// 计划单状态
        /// </summary>
        [Description("计划单状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_PLAN { get; set; }

        /// <summary>
        /// 实施单状态
        /// </summary>
        [Description("实施单状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_EXE { get; set; }

        /// <summary>
        /// 计划单单号
        /// </summary>
        [Description("计划单单号")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_CODE { get; set; }

        /// <summary>
        /// 实施单单号
        /// </summary>
        [Description("实施单单号")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_CODE { get; set; }

        /// <summary>
        /// 码头ID
        /// </summary>
        [Description("码头ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DOCK_ID { get; set; }

        /// <summary>
        /// 码头编号
        /// </summary>
        [Description("码头编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DOCK_CODE { get; set; }

        /// <summary>
        /// 码头名称
        /// </summary>
        [Description("码头名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DOCK_NAME { get; set; }

        /// <summary>
        /// 故障现象描述
        /// </summary>
        [Description("故障现象描述")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_DESC { get; set; }

        /// <summary>
        /// 计划开工时间
        /// </summary>
        [Description("计划开工时间")]
        public DateTime? PLAN_BDATE { get; set; }

        /// <summary>
        /// 计划完工时间
        /// </summary>
        [Description("计划完工时间")]
        public DateTime? PLAN_EDATE { get; set; }

        /// <summary>
        /// 实际完工时间
        /// </summary>
        [Description("实际完工时间")]
        public DateTime? EXE_EDATE { get; set; }

        /// <summary>
        /// 实际开工时间
        /// </summary>
        [Description("实际开工时间")]
        public DateTime? EXE_BDATE { get; set; }

        /// <summary>
        /// 维修工时
        /// </summary>
        [Description("维修工时")]
        public decimal? EXE_HOUR { get; set; }

        /// <summary>
        /// 负责人ID
        /// </summary>
        [Description("负责人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHARGE_USERID { get; set; }

        /// <summary>
        /// 负责人
        /// </summary>
        [Description("负责人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHARGE_USER { get; set; }

        /// <summary>
        /// 维修内容
        /// </summary>
        [Description("维修内容")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_CONTENT { get; set; }

        /// <summary>
        /// 实施情况描述
        /// </summary>
        [Description("实施情况描述")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_DESCRIBE { get; set; }

        /// <summary>
        /// 是否遗留问题
        /// </summary>
        [Description("是否遗留问题")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_LEAVE { get; set; }

        /// <summary>
        /// 遗留问题描述
        /// </summary>
        [Description("遗留问题描述")]
        [Column(DbType = DbType.AnsiString)]
        public string LEAVE_DESCRIBE { get; set; }

        /// <summary>
        /// 预计维修费用
        /// </summary>
        [Description("预计维修费用")]
        public decimal? PLAN_COST { get; set; }

        /// <summary>
        /// 实际维修费用
        /// </summary>
        [Description("实际维修费用")]
        public decimal? EXE_COST { get; set; }

        /// <summary>
        /// 计划制定人ID
        /// </summary>
        [Description("计划制定人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 计划制定人
        /// </summary>
        [Description("计划制定人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 计划制定时间
        /// </summary>
        [Description("计划制定时间")]
        public DateTime? EDIT_DATE { get; set; }

        /// <summary>
        /// 实施人ID
        /// </summary>
        [Description("实施人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_USERID { get; set; }

        /// <summary>
        /// 实施人
        /// </summary>
        [Description("实施人")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_USER { get; set; }

        /// <summary>
        /// 实施提交日期
        /// </summary>
        [Description("实施提交日期")]
        public DateTime? EXE_DATE { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string PLAN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 采购方式
        /// </summary>
        [Description("采购方式")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_METHOD { get; set; }

        /// <summary>
        /// 计划承修方ID
        /// </summary>
        [Description("计划承修方ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_PROVIDERID { get; set; }

        /// <summary>
        /// 计划承修方
        /// </summary>
        [Description("计划承修方")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_PROVIDER { get; set; }

        /// <summary>
        /// 实际承修方ID
        /// </summary>
        [Description("实际承修方ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_PROVIDERID { get; set; }

        /// <summary>
        /// 实际承修方
        /// </summary>
        [Description("实际承修方")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_PROVIDER { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 部门名称
        /// </summary>
        [Description("部门名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 确认单状态
        /// </summary>
        [Description("确认单状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_CONFIRM { get; set; }

        /// <summary>
        /// 验收单状态
        /// </summary>
        [Description("验收单状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_CHECK { get; set; }

        /// <summary>
        /// 确认单单号
        /// </summary>
        [Description("确认单单号")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_CODE { get; set; }

        /// <summary>
        /// 验收单单号
        /// </summary>
        [Description("验收单单号")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_CODE { get; set; }

        /// <summary>
        /// 维修方案
        /// </summary>
        [Description("维修方案")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_METHOD { get; set; }

        /// <summary>
        /// 故障原因
        /// </summary>
        [Description("故障原因")]
        [Column(DbType = DbType.AnsiString)]
        public string REASON { get; set; }

        /// <summary>
        /// 解决方法
        /// </summary>
        [Description("解决方法")]
        [Column(DbType = DbType.AnsiString)]
        public string SOLUTION { get; set; }

        /// <summary>
        /// 维修费用(元)
        /// </summary>
        [Description("维修费用(元)")]
        public decimal? REP_MONEY { get; set; }

        /// <summary>
        /// 合同编号
        /// </summary>
        [Description("合同编号")]
        [Column(DbType = DbType.AnsiString)]
        public string PACT_CODE { get; set; }

        /// <summary>
        /// 合同名称
        /// </summary>
        [Description("合同名称")]
        [Column(DbType = DbType.AnsiString)]
        public string PACT_NAME { get; set; }

        /// <summary>
        /// 验收人ID
        /// </summary>
        [Description("验收人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_USERID { get; set; }

        /// <summary>
        /// 供应商名称
        /// </summary>
        [Description("供应商名称")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_PROVIDER { get; set; }

        /// <summary>
        /// 合同金额(元)
        /// </summary>
        [Description("合同金额(元)")]
        public decimal? PACT_MONEY { get; set; }

        /// <summary>
        /// 签订日期
        /// </summary>
        [Description("签订日期")]
        public DateTime? PACT_DATE { get; set; }

        /// <summary>
        /// 验收人
        /// </summary>
        [Description("验收人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_USER { get; set; }

        /// <summary>
        /// 验收时间
        /// </summary>
        [Description("验收时间")]
        public DateTime? CHECK_DATE { get; set; }

        /// <summary>
        /// 验收情况
        /// </summary>
        [Description("验收情况")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_DESC { get; set; }

        /// <summary>
        /// 确认备注
        /// </summary>
        [Description("确认备注")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_MEMO { get; set; }

        /// <summary>
        /// 遗留问题描述
        /// </summary>
        [Description("遗留问题描述")]
        [Column(DbType = DbType.AnsiString)]
        public string LEAVE_MEMO { get; set; }

        /// <summary>
        /// 承修方ID
        /// </summary>
        [Description("承修方ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 承修方
        /// </summary>
        [Description("承修方")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 确认人ID
        /// </summary>
        [Description("确认人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_USERID { get; set; }

        /// <summary>
        /// 确认人
        /// </summary>
        [Description("确认人")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_USER { get; set; }

        /// <summary>
        /// 是否遗留问题确认
        /// </summary>
        [Description("是否遗留问题确认")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_LEAVE_CONFIR { get; set; }
    }
}