//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类REP_FAULT_LABOR
    /// </summary>
    [Table("REP_FAULT_LABOR")]
    public class REP_FAULT_LABOR
    {

        /// <summary>
        /// 人员姓名
        /// </summary>
        [Description("人员姓名")]
        [Column(DbType = DbType.AnsiString)]
        public string LABOR_NAME { get; set; }

        /// <summary>
        /// 人员ID
        /// </summary>
        [Description("人员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string LABOR_ID { get; set; }

        /// <summary>
        /// 工时(H)
        /// </summary>
        [Description("工时(H)")]
        public decimal? WORK_HOURS { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string FAULT_LABOR_ID { get; set; }

        /// <summary>
        /// 外键
        /// </summary>
        [Description("外键")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}