//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类REP_DOCK_PLAN_ITEM
    /// </summary>
    [Table("REP_DOCK_PLAN_ITEM")]
    public class REP_DOCK_PLAN_ITEM
    {

        /// <summary>
        /// 维修项目
        /// </summary>
        [Description("维修项目")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_ITEM { get; set; }

        /// <summary>
        /// 维修内容
        /// </summary>
        [Description("维修内容")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_CONTENT { get; set; }

        /// <summary>
        /// 维修方案
        /// </summary>
        [Description("维修方案")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_METHOD { get; set; }

        /// <summary>
        /// 预计人员数量
        /// </summary>
        [Description("预计人员数量")]
        public decimal? LABOR_NUM { get; set; }

        /// <summary>
        /// 预计花费时间
        /// </summary>
        [Description("预计花费时间")]
        public decimal? TAKE_TIME { get; set; }

        /// <summary>
        /// 检修负责人
        /// </summary>
        [Description("检修负责人")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_LEADER { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string PLAN_ITEM_ID { get; set; }

        /// <summary>
        /// 码头维修计划ID
        /// </summary>
        [Description("码头维修计划ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 是否完成
        /// </summary>
        [Description("是否完成")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_COMPLETE { get; set; }

        /// <summary>
        /// 实施日期
        /// </summary>
        [Description("实施日期")]
        public DateTime? EXE_DATE { get; set; }

        /// <summary>
        /// 实际人员数量
        /// </summary>
        [Description("实际人员数量")]
        public decimal? EXE_LABOR_NUM { get; set; }

        /// <summary>
        /// 实际花费时间
        /// </summary>
        [Description("实际花费时间")]
        public decimal? EXE_TAKE_TIME { get; set; }

    }
}