//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 文件表
    /// </summary>
    [Table("SYS_FILE")]
    [Description("文件表")]
    public class SYS_FILE
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true)]
        public long ID { get; set; }

        /// <summary>
        /// 文件hash
        /// </summary>
        [Description("文件hash")]
        [Column(DbType = DbType.AnsiString, Size = 32)]
        public string FILE_HASH { get; set; }

        /// <summary>
        /// 文件名
        /// </summary>
        [Description("文件名")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string FILE_NAME { get; set; }

        /// <summary>
        /// 文件路径
        /// </summary>
        [Description("文件路径")]
        [Column(DbType = DbType.AnsiString, Size = 2000)]
        public string FILE_PATH { get; set; }

        /// <summary>
        /// 文件地址
        /// </summary>
        [Description("文件地址")]
        [Column(DbType = DbType.AnsiString, Size = 2000)]
        public string FILE_URL { get; set; }

        /// <summary>
        /// 原始文件名
        /// </summary>
        [Description("原始文件名")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string ORGIN_FILE_NAME { get; set; }

        /// <summary>
        /// 文件大小
        /// </summary>
        [Description("文件大小")]
        public long? FILE_SIZE { get; set; }

        /// <summary>
        /// 文件类型
        /// </summary>
        [Description("文件类型")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string FILE_TYPE { get; set; }

        /// <summary>
        /// 上传IP
        /// </summary>
        [Description("上传IP")]
        [Column(DbType = DbType.AnsiString, Size = 30)]
        public string IP { get; set; }

        /// <summary>
        /// 来源路由
        /// </summary>
        [Description("来源路由")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string SOURCE_PATH { get; set; }

        /// <summary>
        /// 来源url
        /// </summary>
        [Description("来源url")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string SOURCE_URL { get; set; }

        /// <summary>
        /// 创建人ID
        /// </summary>
        [Description("创建人ID")]
        public long? CREATEUSERID { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public DateTime? CREATEDATE { get; set; }

    }
}