//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类SYS_MENU
    /// </summary>
    [Table("SYS_MENU")]
    [Description("菜单")]
    public class SYS_MENU
    {

        /// <summary>
        /// 菜单ID
        /// </summary>
        [Description("菜单ID")]
        [Column(IsPrimaryKey = true)]
        [AutoIncrement]
        public long? MENUID { get; set; }

        /// <summary>
        /// 菜单号
        /// </summary>
        [Description("菜单号")]
        [Column(DbType = DbType.AnsiString)]
        public string MENUNO { get; set; }

        /// <summary>
        /// 父菜单号
        /// </summary>
        [Description("父菜单号")]
        [Column(DbType = DbType.AnsiString)]
        public string MENUPARENTNO { get; set; }

        /// <summary>
        /// 菜单序号
        /// </summary>
        [Description("菜单序号")]
        public int? MENUORDER { get; set; }

        /// <summary>
        /// 菜单名称
        /// </summary>
        [Description("菜单名称")]
        [Column(DbType = DbType.String)]
        public string MENUNAME { get; set; }

        /// <summary>
        /// 菜单链接
        /// </summary>
        [Description("菜单链接")]
        [Column(DbType = DbType.AnsiString)]
        public string MENUURL { get; set; }

        /// <summary>
        /// 菜单图标
        /// </summary>
        [Description("菜单图标")]
        [Column(DbType = DbType.AnsiString)]
        public string MENUICON { get; set; }

        /// <summary>
        /// 是否可见
        /// </summary>
        [Description("是否可见")]
        public int? ISVISIBLE { get; set; }

        /// <summary>
        /// 是否叶节点
        /// </summary>
        [Description("是否叶节点")]
        public int? ISLEAF { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.String)]
        public string APPNAME { get; set; }

    }
}