//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类TDBLINK
    /// </summary>
    [Table("TDBLINK")]
    [Description("数据库配置")]
    public class TDBLINK
    {

        /// <summary>
        /// 连接名
        /// </summary>
        [Description("连接名")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string LINKNAME { get; set; }

        /// <summary>
        /// 公司
        /// </summary>
        [Description("公司")]
        [Column(DbType = DbType.AnsiString)]
        public string CORPID { get; set; }

        /// <summary>
        /// 连接类型
        /// </summary>
        [Description("连接类型")]
        [Column(DbType = DbType.AnsiString)]
        public string LINKTYPE { get; set; }

        /// <summary>
        /// 连接字符串
        /// </summary>
        [Description("连接字符串")]
        [Column(DbType = DbType.AnsiString)]
        public string CONNSTR { get; set; }

        /// <summary>
        /// 有效否
        /// </summary>
        [Description("有效否")]
        [Column(DbType = DbType.AnsiString)]
        public string VALIDFLAG { get; set; }

    }
}