//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Gksyb.Common;
using System.Text;

namespace Gksyb.Model.Core
{
    public static class TDBLINKExtensions
    {
        private const string PUBLIC_KEY = "048f3c593cbaac8cdf2e5c02e092d6caa2e2a2e5751507f076138e1c4578259a1c428cf96b4e65b78bec9e8263b514c944bc3e6930666bc27e79024f09a0b4cef0";
        private const string PRIVATE_KEY = "1df182cda4a165b3eaafb17ebe5e514ace129513ac995d4c98c87e126ab04d32";

        /// <summary>
        /// 加密
        /// </summary>
        public static TDBLINK Encrypt(this TDBLINK source)
        {
            source.CONNSTR = Encrypt(source.CONNSTR);
            return source;
        }

        /// <summary>
        /// 解密
        /// </summary>
        public static TDBLINK Decrypt(this TDBLINK source)
        {
            try
            {
                source.CONNSTR = Decrypt(source.CONNSTR);
            }
            catch { }
            return source;
        }

        /// <summary>
        /// 加密
        /// </summary>
        public static string Encrypt(string text)
        {
            var cipherBytes = CryptographyHelper.SM2Encrypt(PUBLIC_KEY, Encoding.UTF8.GetBytes(text));
            return Convert.ToHexString(cipherBytes).ToLower();
        }

        /// <summary>
        /// 解密
        /// </summary>
        public static string Decrypt(string text)
        {
            var plainBytes = CryptographyHelper.SM2Decrypt(PRIVATE_KEY, Convert.FromHexString(text));
            return Encoding.UTF8.GetString(plainBytes);
        }

    }
}