//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using Gksyb.Common;
using Gksyb.Common.Weixin;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 微信通知
    /// </summary>
    [NotDbLog]
    public class WEIXIN_NOTICE
    {
        public const string InitStatus = "未发送";
        /// <summary>
        /// 参考例子
        /// </summary>
        /// <returns></returns>
        public static WEIXIN_NOTICE Sample()
        {
            var tdata = new WeiXinTemplateData
            {
                first = new WeiXinTemplateDataItem("带颜色数据", "#FF0000"),
                keyword1 = new WeiXinTemplateDataItem("keyword1"),
                keyword2 = new WeiXinTemplateDataItem("keyword2"),
                keyword3 = new WeiXinTemplateDataItem("keyword3"),
                keyword4 = new WeiXinTemplateDataItem("keyword4"),
                keyword5 = new WeiXinTemplateDataItem("keyword5"),
                keyword6 = new WeiXinTemplateDataItem("keyword6"),
                keyword7 = new WeiXinTemplateDataItem("keyword7"),
                remark = new WeiXinTemplateDataItem("remark")
            };
            var notice = new WEIXIN_NOTICE
            {
                SID = GuidHelper.NewShortId(),
                TEMPLATE = "消息模板ID",
                RECEIVER = "微信openid",
                URL = "链接地址",
                TDATA = tdata.ToJson(),
                CREATEUSER = "创建人",
                CREATEDATE = DateTime.Now,
                MODIFYUSER = "修改人",
                MODIFYDATE = DateTime.Now
            };
            return notice;
        }

        /// <summary>
        /// 主键(Guid)
        /// </summary>
        [Description("主键(Guid)")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString, Size = 11)]
        public string SID { get; set; }

        /// <summary>
        /// 模板
        /// </summary>
        [Description("模板")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string TEMPLATE { get; set; }

        /// <summary>
        /// 通知对象
        /// </summary>
        [Description("通知对象")]
        [Column(DbType = DbType.AnsiString, Size = 50)]
        public string RECEIVER { get; set; }

        /// <summary>
        /// 通知URL
        /// </summary>
        [Description("通知URL")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string URL { get; set; }

        /// <summary>
        /// 通知数据json
        /// </summary>
        [Description("通知数据json")]
        [Column(DbType = DbType.AnsiString, Size = 4000)]
        public string TDATA { get; set; }

        /// <summary>
        /// 重试次数
        /// </summary>
        [Description("重试次数")]
        public int? RETRY { get; set; }

        /// <summary>
        /// 调用结果
        /// </summary>
        [Description("调用结果")]
        [Column(DbType = DbType.AnsiString, Size = 400)]
        public string RESULT { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        [Description("状态")]
        [Column(DbType = DbType.AnsiString, Size = 20)]
        public string STATUS { get; set; } = InitStatus;

        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人
        /// </summary>
        [Description("修改人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 发送时间
        /// </summary>
        [Description("发送时间")]
        public DateTime? SENDDATE { get; set; }

    }
}