//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace Gksyb.Common
{
    /// <summary>
    /// 广播数据封装
    /// </summary>
    public class ActionData
    {
        /// <summary>
        /// 方法名
        /// </summary>
        [JsonProperty(Order = 10)]
        public string Action { get; set; }

        /// <summary>
        /// 传递数据
        /// </summary>
        [JsonProperty(Order = 20)]
        public object Data { get; set; }

        /// <summary>
        /// 操作时间
        /// </summary>
        [JsonProperty(Order = 30)]
        public DateTime ActionTime { get; set; } = DateTime.Now;

        public ActionData<string> ToActionString() => new ActionData<string>()
        {
            Action = Action,
            Data = Data.ToJson()
        };

        public override string ToString() => this.ToJson();
    }

    /// <summary>
    /// 广播数据封装
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class ActionData<T> : ActionData
    {
        [JsonProperty(Order = 20)]
        public new T Data
        {
            get { return (T)base.Data; }
            set { base.Data = value; }
        }
    }
}