//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace Gksyb.Common
{
    /// <summary>
    /// 广播数据封装
    /// </summary>
    public class ActionData
    {
        /// <summary>
        /// 方法名
        /// </summary>
        public string Action { get; set; }

        /// <summary>
        /// 传递数据
        /// </summary>
        public object Data { get; set; }

        /// <summary>
        /// 操作时间
        /// </summary>
        public DateTime ActionTime { get; set; } = DateTime.Now;


        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }

    /// <summary>
    /// 广播数据封装
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class ActionData<T> : ActionData
    {
        public new T Data { get; set; }
    }
}