//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.XXX.Business
{
    /// <summary>
    /// 实体类SAMPLE_TABLE
    /// </summary>
    [Table("SAMPLE_TABLE")]
    public class SAMPLE_TABLE
    {

        /// <summary>
        /// SID
        /// </summary>
        [Description("SID")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string SID { get; set; }

        /// <summary>
        /// STRING_COLUMN
        /// </summary>
        [Description("STRING_COLUMN")]
        [Column(DbType = DbType.AnsiString)]
        public string STRING_COLUMN { get; set; }

        /// <summary>
        /// INT_COLUMN
        /// </summary>
        [Description("INT_COLUMN")]
        public long? INT_COLUMN { get; set; }

        /// <summary>
        /// FLOAT_COLUMN
        /// </summary>
        [Description("FLOAT_COLUMN")]
        public decimal? FLOAT_COLUMN { get; set; }

        /// <summary>
        /// DATE_COLUMN
        /// </summary>
        [Description("DATE_COLUMN")]
        public DateTime? DATE_COLUMN { get; set; }

        /// <summary>
        /// COMB_COLUMN
        /// </summary>
        [Description("COMB_COLUMN")]
        public long? COMB_COLUMN { get; set; }

        /// <summary>
        /// DIFF_COMB_COLUMN
        /// </summary>
        [Description("DIFF_COMB_COLUMN")]
        [Column(DbType = DbType.AnsiString)]
        public string DIFF_COMB_COLUMN { get; set; }

        /// <summary>
        /// CORPID
        /// </summary>
        [Description("CORPID")]
        [Column(DbType = DbType.AnsiString)]
        public string CORPID { get; set; }

        /// <summary>
        /// CREATEUSERID
        /// </summary>
        [Description("CREATEUSERID")]
        public long? CREATEUSERID { get; set; }

        /// <summary>
        /// CREATEUSER
        /// </summary>
        [Description("CREATEUSER")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// CREATEDATE
        /// </summary>
        [Description("CREATEDATE")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// MODIFYUSERID
        /// </summary>
        [Description("MODIFYUSERID")]
        public long? MODIFYUSERID { get; set; }

        /// <summary>
        /// MODIFYUSER
        /// </summary>
        [Description("MODIFYUSER")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// MODIFYDATE
        /// </summary>
        [Description("MODIFYDATE")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// RECORDSTATUS
        /// </summary>
        [Description("RECORDSTATUS")]
        [Column(DbType = DbType.AnsiString)]
        public string RECORDSTATUS { get; set; }

    }
}