<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Gksyb.Common\Gksyb.Common.csproj" />
		<ProjectReference Include="..\Gksyb.Core\Gksyb.Core.csproj" />
		<ProjectReference Include="..\Gksyb.Model\Gksyb.Model.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Chloe">
			<HintPath>..\dll\Chloe.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
