//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类PROVIDER_ASSESS_TASK_DET
    /// </summary>
    [Table("PROVIDER_ASSESS_TASK_DET")]
    public class PROVIDER_ASSESS_TASK_DET
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string ASSESS_TASK_DET_ID { get; set; }

        /// <summary>
        /// 评估任务id
        /// </summary>
        [Description("评估任务id")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSESS_TASK_ID { get; set; }

        /// <summary>
        /// 评估任务基础id
        /// </summary>
        [Description("评估任务基础id")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSESS_BASE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

    }
}