//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类PROVIDER
    /// </summary>
    [Table("PROVIDER")]
    public class PROVIDER
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 服务单位
        /// </summary>
        [Description("服务单位")]
        [Column(DbType = DbType.AnsiString)]
        public string ORG_NAME { get; set; }

        /// <summary>
        /// 管理部门
        /// </summary>
        [Description("管理部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 供应商编码
        /// </summary>
        [Description("供应商编码")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_CODE { get; set; }

        /// <summary>
        /// 供应商名称
        /// </summary>
        [Description("供应商名称")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 供应商简称
        /// </summary>
        [Description("供应商简称")]
        [Column(DbType = DbType.AnsiString)]
        public string ABBREVIATION { get; set; }

        /// <summary>
        /// 地址
        /// </summary>
        [Description("地址")]
        [Column(DbType = DbType.AnsiString)]
        public string REG_ADDRESS { get; set; }

        /// <summary>
        /// 企业法人
        /// </summary>
        [Description("企业法人")]
        [Column(DbType = DbType.AnsiString)]
        public string LEGAL_REPRESENT { get; set; }

        /// <summary>
        /// 注册资金
        /// </summary>
        [Description("注册资金")]
        [Column(DbType = DbType.AnsiString)]
        public string ENTITY_REG_FUND { get; set; }

        /// <summary>
        /// 企业性质
        /// </summary>
        [Description("企业性质")]
        [Column(DbType = DbType.AnsiString)]
        public string ENTER_NATURE { get; set; }

        /// <summary>
        /// 营业执照号
        /// </summary>
        [Description("营业执照号")]
        [Column(DbType = DbType.AnsiString)]
        public string LICENSE_CODE { get; set; }

        /// <summary>
        /// 企业年资
        /// </summary>
        [Description("企业年资")]
        [Column(DbType = DbType.AnsiString)]
        public string ENTER_QUALITY { get; set; }

        /// <summary>
        /// 经营许可证
        /// </summary>
        [Description("经营许可证")]
        [Column(DbType = DbType.AnsiString)]
        public string BUSINESS_LIC { get; set; }

        /// <summary>
        /// 联系人
        /// </summary>
        [Description("联系人")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_CONTACT { get; set; }

        /// <summary>
        /// 联系电话
        /// </summary>
        [Description("联系电话")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_PHONE { get; set; }

        /// <summary>
        /// 传真
        /// </summary>
        [Description("传真")]
        [Column(DbType = DbType.AnsiString)]
        public string FAX { get; set; }

        /// <summary>
        /// 邮件
        /// </summary>
        [Description("邮件")]
        [Column(DbType = DbType.AnsiString)]
        public string EMAIL { get; set; }

        /// <summary>
        /// 网站
        /// </summary>
        [Description("网站")]
        [Column(DbType = DbType.AnsiString)]
        public string WEBSITE { get; set; }

        /// <summary>
        /// 一般纳税人
        /// </summary>
        [Description("一般纳税人")]
        [Column(DbType = DbType.AnsiString)]
        public string AVERAGE_TAX { get; set; }

        /// <summary>
        /// 主供范围
        /// </summary>
        [Description("主供范围")]
        [Column(DbType = DbType.AnsiString)]
        public string BIZ_SCOPE { get; set; }

        /// <summary>
        /// 供应商来源
        /// </summary>
        [Description("供应商来源")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_SRC { get; set; }

        /// <summary>
        /// 供应商分类
        /// </summary>
        [Description("供应商分类")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_TYPE { get; set; }

        /// <summary>
        /// 供应商状态
        /// </summary>
        [Description("供应商状态")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_STATUS { get; set; }

        /// <summary>
        /// 合作情况
        /// </summary>
        [Description("合作情况")]
        [Column(DbType = DbType.AnsiString)]
        public string COOPERATION { get; set; }

        /// <summary>
        /// 评审结论
        /// </summary>
        [Description("评审结论")]
        [Column(DbType = DbType.AnsiString)]
        public string CONCLUSION { get; set; }

        /// <summary>
        /// 合格供应商综合评定
        /// </summary>
        [Description("合格供应商综合评定")]
        [Column(DbType = DbType.AnsiString)]
        public string QUA_CONCLUSION { get; set; }

        /// <summary>
        /// 国家
        /// </summary>
        [Description("国家")]
        [Column(DbType = DbType.AnsiString)]
        public string COUNTY { get; set; }

        /// <summary>
        /// 省份
        /// </summary>
        [Description("省份")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVINCE { get; set; }

        /// <summary>
        /// 城市
        /// </summary>
        [Description("城市")]
        [Column(DbType = DbType.AnsiString)]
        public string CITY { get; set; }

        /// <summary>
        /// 开户银行
        /// </summary>
        [Description("开户银行")]
        [Column(DbType = DbType.AnsiString)]
        public string BANK_NAME { get; set; }

        /// <summary>
        /// 联行号
        /// </summary>
        [Description("联行号")]
        [Column(DbType = DbType.AnsiString)]
        public string BANK_CODE { get; set; }

        /// <summary>
        /// 税务登记号
        /// </summary>
        [Description("税务登记号")]
        [Column(DbType = DbType.AnsiString)]
        public string TAX_REG_NO { get; set; }

        /// <summary>
        /// 物资品质
        /// </summary>
        [Description("物资品质")]
        [Column(DbType = DbType.AnsiString)]
        public string QUALITY { get; set; }

        /// <summary>
        /// 交货期
        /// </summary>
        [Description("交货期")]
        [Column(DbType = DbType.AnsiString)]
        public string DELIVERY { get; set; }

        /// <summary>
        /// 紧急订单处理情况
        /// </summary>
        [Description("紧急订单处理情况")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDER_SIT { get; set; }

        /// <summary>
        /// 资信情况
        /// </summary>
        [Description("资信情况")]
        [Column(DbType = DbType.AnsiString)]
        public string CREDIT { get; set; }

        /// <summary>
        /// 综合实力
        /// </summary>
        [Description("综合实力")]
        [Column(DbType = DbType.AnsiString)]
        public string STRENGTH { get; set; }

        /// <summary>
        /// 售后服务响应速度
        /// </summary>
        [Description("售后服务响应速度")]
        [Column(DbType = DbType.AnsiString)]
        public string RESPONE_SPEED { get; set; }

        /// <summary>
        /// 售后服务品质
        /// </summary>
        [Description("售后服务品质")]
        [Column(DbType = DbType.AnsiString)]
        public string SERVICE_QUAL { get; set; }

        /// <summary>
        /// 服务单位ID
        /// </summary>
        [Description("服务单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ORG_ID { get; set; }

        /// <summary>
        /// 管理部门ID
        /// </summary>
        [Description("管理部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public long CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public long MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}