//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类sp_apply
    /// </summary>
    [Table("sp_apply")]
    public class SP_APPLY
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 确认记录状态
        /// </summary>
        [Description("确认记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_CHECK { get; set; }

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_NO { get; set; }

        /// <summary>
        /// 申请日期
        /// </summary>
        [Description("申请日期")]
        public DateTime? APPLY_DATE { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USERID { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USER { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 部门编号
        /// </summary>
        [Description("部门编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 部门名称
        /// </summary>
        [Description("部门名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 是否补库
        /// </summary>
        [Description("是否补库")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_REC { get; set; }

        /// <summary>
        /// 时间要求
        /// </summary>
        [Description("时间要求")]
        [Column(DbType = DbType.AnsiString)]
        public string TIME_REQ { get; set; }

        /// <summary>
        /// 来源ID
        /// </summary>
        [Description("来源ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SOURCE_ID { get; set; }

        /// <summary>
        /// 申购来源
        /// </summary>
        [Description("申购来源")]
        [Column(DbType = DbType.AnsiString)]
        public string SOURCE { get; set; }

        /// <summary>
        /// 用途
        /// </summary>
        [Description("用途")]
        [Column(DbType = DbType.AnsiString)]
        public string USE_MEMO { get; set; }

        /// <summary>
        /// 采购分类ID
        /// </summary>
        [Description("采购分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 采购分类编码
        /// </summary>
        [Description("采购分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 采购分类
        /// </summary>
        [Description("采购分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 紧急程度
        /// </summary>
        [Description("紧急程度")]
        [Column(DbType = DbType.AnsiString)]
        public string EXIG_DEV { get; set; }

        /// <summary>
        /// 项目编号
        /// </summary>
        [Description("项目编号")]
        [Column(DbType = DbType.AnsiString)]
        public string PROJECT_CODE { get; set; }

        /// <summary>
        /// OA审批结果
        /// </summary>
        [Description("OA审批结果")]
        [Column(DbType = DbType.AnsiString)]
        public string OA_CHECK { get; set; }

        /// <summary>
        /// OA审批时间
        /// </summary>
        [Description("OA审批时间")]
        public DateTime? OA_DATE { get; set; }

        /// <summary>
        /// OA退回理由
        /// </summary>
        [Description("OA退回理由")]
        [Column(DbType = DbType.AnsiString)]
        public string OA_MEMO { get; set; }

        /// <summary>
        /// 二级部门ID
        /// </summary>
        [Description("二级部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// OA审批流ID
        /// </summary>
        [Description("OA审批流ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_ID { get; set; }

        /// <summary>
        /// 二级部门
        /// </summary>
        [Description("二级部门")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string APPLY_ID { get; set; }

        /// <summary>
        /// 生成月度计划
        /// </summary>
        [Description("生成月度计划")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_GEN { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 预估金额(元)
        /// </summary>
        [Description("预估金额(元)")]
        public decimal? SUM_MONEY { get; set; }

        /// <summary>
        /// 采购方式
        /// </summary>
        [Description("采购方式")]
        [Column(DbType = DbType.AnsiString)]
        public string CGFS { get; set; }

        /// <summary>
        /// 采购分类ID
        /// </summary>
        [Description("采购分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID2 { get; set; }

        /// <summary>
        /// 实施主体
        /// </summary>
        [Description("实施主体")]
        [Column(DbType = DbType.AnsiString)]
        public string SSZT { get; set; }

        /// <summary>
        /// 实施主体ID
        /// </summary>
        [Description("实施主体ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SSZTID { get; set; }

        /// <summary>
        /// 标的名称
        /// </summary>
        [Description("标的名称")]
        [Column(DbType = DbType.AnsiString)]
        public string BD_NAME { get; set; }

    }

}