//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Gksyb.Model
{

    /// <summary>
    /// 实体类sp_collect_request
    /// </summary>
    [Table("sp_collect_request")]
    public class SP_COLLECT_REQUEST
    {

        /// <summary>
        /// 需求计划单号
        /// </summary>
        [Description("需求计划单号")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_CODE { get; set; }

        /// <summary>
        /// 申请日期
        /// </summary>
        [Display(Name = "申请日期")]
        [Description("申请日期")]
        public DateTime? REQUEST_DATE { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_USER { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_USERID { get; set; }

        /// <summary>
        /// 备件品种编码
        /// </summary>
        [Description("备件品种编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 备件品种名称
        /// </summary>
        [Description("备件品种名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 备件型号
        /// </summary>
        [Description("备件型号")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_TYPE { get; set; }

        /// <summary>
        /// 品牌
        /// </summary>
        [Description("品牌")]
        [Column(DbType = DbType.AnsiString)]
        public string BRAND { get; set; }

        /// <summary>
        /// 其他编号
        /// </summary>
        [Description("其他编号")]
        [Column(DbType = DbType.AnsiString)]
        public string OTHER_CODE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 制造厂
        /// </summary>
        [Description("制造厂")]
        [Column(DbType = DbType.AnsiString)]
        public string FACTORY { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 申请部门ID
        /// </summary>
        [Description("申请部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string COLLECT_REQUEST_ID { get; set; }

        /// <summary>
        /// 备件请购明细ID
        /// </summary>
        [Description("备件请购明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_DET_ID { get; set; }

        /// <summary>
        /// 备件请购单ID
        /// </summary>
        [Description("备件请购单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_ID { get; set; }

        /// <summary>
        /// 需求计划明细ID
        /// </summary>
        [Description("需求计划明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_DET_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 备件类别编码
        /// </summary>
        [Description("备件类别编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 备件类别名称
        /// </summary>
        [Description("备件类别名称")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 备件类别ID
        /// </summary>
        [Description("备件类别ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 代码
        /// </summary>
        [Description("代码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_DAIMA { get; set; }

        /// <summary>
        /// 图号/设备
        /// </summary>
        [Description("图号/设备")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_TUHAO { get; set; }

        /// <summary>
        /// 物资英文名称
        /// </summary>
        [Description("物资英文名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ENGNAME { get; set; }

        /// <summary>
        /// 物资ID
        /// </summary>
        [Description("物资ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 确认数量
        /// </summary>
        [Description("确认数量")]
        public decimal? CONFIRM_NUM { get; set; }

        /// <summary>
        /// 请购金额
        /// </summary>
        [Description("请购金额")]
        public decimal? COLLECT_MONEY { get; set; }

        /// <summary>
        /// 含税单价(元)
        /// </summary>
        [Description("含税单价(元)")]
        public decimal? TAX_PRICE { get; set; }

        /// <summary>
        /// 含税总金额(元)
        /// </summary>
        [Description("含税总金额(元)")]
        public decimal? TAX_MONEY { get; set; }

        /// <summary>
        /// 不含税单价(元)
        /// </summary>
        [Description("不含税单价(元)")]
        public decimal? NOTAX_PRICE { get; set; }

        /// <summary>
        /// 不含税总金额(元)
        /// </summary>
        [Description("不含税总金额(元)")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 申请数量
        /// </summary>
        [Description("申请数量")]
        public decimal? REQUEST_NUM { get; set; }

        /// <summary>
        /// 核准数量
        /// </summary>
        [Description("核准数量")]
        public decimal? CHECK_NUM { get; set; }

        /// <summary>
        /// 是否全数购买
        /// </summary>
        [Description("是否全数购买")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_FULLBUY { get; set; }

    }

}