//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{

    /// <summary>
    /// 实体类SP_CATALOG_SCAN_DET
    /// </summary>
    [Table("SP_CATALOG_SCAN_DET")]
    public class SP_CATALOG_SCAN_DET
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 其他编号
        /// </summary>
        [Description("其他编号")]
        [Column(DbType = DbType.AnsiString)]
        public string OTHER_CODE { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 制造厂
        /// </summary>
        [Description("制造厂")]
        [Column(DbType = DbType.AnsiString)]
        public string FACTORY { get; set; }

        /// <summary>
        /// 库存数量
        /// </summary>
        [Description("库存数量")]
        public decimal? STORE_NUM { get; set; }

        /// <summary>
        /// 盘点数量
        /// </summary>
        [Description("盘点数量")]
        public decimal? SCAN_NUM { get; set; }

        /// <summary>
        /// 盘点仓库编码
        /// </summary>
        [Description("盘点仓库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_CODE { get; set; }

        /// <summary>
        /// 盘点仓库
        /// </summary>
        [Description("盘点仓库")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 盘点仓库ID
        /// </summary>
        [Description("盘点仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 库位名称
        /// </summary>
        [Description("库位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_NAME { get; set; }

        /// <summary>
        /// 盘点库位编码
        /// </summary>
        [Description("盘点库位编码")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_CODE { get; set; }

        /// <summary>
        /// 库位ID
        /// </summary>
        [Description("库位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_ID { get; set; }

        /// <summary>
        /// 盘点分类编码
        /// </summary>
        [Description("盘点分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 盘点分类
        /// </summary>
        [Description("盘点分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 盘点分类ID
        /// </summary>
        [Description("盘点分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string SCAN_DET_ID { get; set; }

        /// <summary>
        /// 盘点ID
        /// </summary>
        [Description("盘点ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_ID { get; set; }

        /// <summary>
        /// 备件品种ID
        /// </summary>
        [Description("备件品种ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 库存明细ID
        /// </summary>
        [Description("库存明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }

}