//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{

    /// <summary>
    /// 实体类sp_collect
    /// </summary>
    [Table("sp_collect")]
    public class SP_COLLECT
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 请购单号
        /// </summary>
        [Description("请购单号")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_CODE { get; set; }

        /// <summary>
        /// 请购日期
        /// </summary>
        [Description("请购日期")]
        public DateTime? COLLECT_DATE { get; set; }

        /// <summary>
        /// 采购人
        /// </summary>
        [Description("采购人")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_USER { get; set; }

        /// <summary>
        /// 采购人ID
        /// </summary>
        [Description("采购人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_USERID { get; set; }

        /// <summary>
        /// 采购部门
        /// </summary>
        [Description("采购部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 采购部门ID
        /// </summary>
        [Description("采购部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        [Description("仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string COLLECT_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 采购方式
        /// </summary>
        [Description("采购方式")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_METHOD { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 总金额
        /// </summary>
        [Description("总金额")]
        public decimal? COLLECT_PRICE { get; set; }

        /// <summary>
        /// 确认状态
        /// </summary>
        [Description("确认状态")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_AUDIT { get; set; }

        /// <summary>
        /// 含税总金额(元)
        /// </summary>
        [Description("含税总金额(元)")]
        public decimal? TAX_MONEY { get; set; }

        /// <summary>
        /// 不含税总金额(元)
        /// </summary>
        [Description("不含税总金额(元)")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 采购结果确认单单号
        /// </summary>
        [Description("采购结果确认单单号")]
        [Column(DbType = DbType.AnsiString)]
        public string CONFIRM_CODE { get; set; }

        /// <summary>
        /// 采购结果确认日期
        /// </summary>
        [Description("采购结果确认日期")]
        public DateTime? CONFIRM_DATE { get; set; }

        /// <summary>
        /// 供应商编码
        /// </summary>
        [Description("供应商编码")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_CODE { get; set; }

        /// <summary>
        /// 供应商ID
        /// </summary>
        [Description("供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 仓库编码
        /// </summary>
        [Description("仓库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_CODE { get; set; }

        /// <summary>
        /// 库存方式
        /// </summary>
        [Description("库存方式")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_TYPE { get; set; }

        /// <summary>
        /// 仓管员
        /// </summary>
        [Description("仓管员")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_USER { get; set; }

        /// <summary>
        /// 仓管员ID
        /// </summary>
        [Description("仓管员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_USERID { get; set; }

        /// <summary>
        /// 物资分类
        /// </summary>
        [Description("物资分类")]
        [Column(DbType = DbType.AnsiString)]
        public string COLLECT_SPTYPE { get; set; }

        /// <summary>
        /// 换算比例(%)
        /// </summary>
        [Description("换算比例(%)")]
        public decimal? RATIO { get; set; }

        /// <summary>
        /// 询价供应商
        /// </summary>
        [Description("询价供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string CONSULT_PROVIDER { get; set; }

        /// <summary>
        /// 竞价标的编号
        /// </summary>
        [Description("竞价标的编号")]
        [Column(DbType = DbType.AnsiString)]
        public string BD_NO { get; set; }

    }

}