//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类sp_inback_det
    /// </summary>
    [Table("sp_inback_det")]
    public class SP_INBACK_DET
    {

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 规格型号
        /// </summary>
        [Description("规格型号")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 入库数量
        /// </summary>
        [Description("入库数量")]
        public decimal? COUNT { get; set; }

        /// <summary>
        /// 入库单价(元)
        /// </summary>
        [Description("入库单价(元)")]
        public decimal? PRICE { get; set; }

        /// <summary>
        /// 入库金额(元)
        /// </summary>
        [Description("入库金额(元)")]
        public decimal? MONEY { get; set; }

        /// <summary>
        /// 货位编码
        /// </summary>
        [Description("货位编码")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_CODE { get; set; }

        /// <summary>
        /// 货位名称
        /// </summary>
        [Description("货位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_NAME { get; set; }

        /// <summary>
        /// 货位ID
        /// </summary>
        [Description("货位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_ID { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USERID { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USER { get; set; }

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_NO { get; set; }

        /// <summary>
        /// 说明
        /// </summary>
        [Description("说明")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 流水账ID
        /// </summary>
        [Description("流水账ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WATER_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string INDET_ID { get; set; }

        /// <summary>
        /// 入库冲红单ID
        /// </summary>
        [Description("入库冲红单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string IN_BACK_ID { get; set; }

        /// <summary>
        /// 订单明细ID
        /// </summary>
        [Description("订单明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDERDET_ID { get; set; }

        /// <summary>
        /// 库存ID
        /// </summary>
        [Description("库存ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 采购入库明细ID
        /// </summary>
        [Description("采购入库明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTOREDET_ID { get; set; }

    }
}