//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;
namespace Gksyb.Model
{
    /// <summary>
    /// 实体类SP_INSTORE
    /// </summary>
    [Table("SP_INSTORE")]
    public class SP_INSTORE
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string IN_ID { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 入库单号
        /// </summary>
        [Description("入库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string IN_CODE { get; set; }

        /// <summary>
        /// 入库日期
        /// </summary>
        [Description("入库日期")]
        public DateTime? IN_DATE { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 仓管员ID
        /// </summary>
        [Description("仓管员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string IN_USERID { get; set; }

        /// <summary>
        /// 仓管员
        /// </summary>
        [Description("仓管员")]
        [Column(DbType = DbType.AnsiString)]
        public string IN_USER { get; set; }

        /// <summary>
        /// 验收人ID
        /// </summary>
        [Description("验收人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHK_USERID { get; set; }

        /// <summary>
        /// 验收人
        /// </summary>
        [Description("验收人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHK_USER { get; set; }

        /// <summary>
        /// 收货部门ID
        /// </summary>
        [Description("收货部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 收货部门（船舶）
        /// </summary>
        [Description("收货部门（船舶）")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 收货人id
        /// </summary>
        [Description("收货人id")]
        [Column(DbType = DbType.AnsiString)]
        public string CONSIGNEE_ID { get; set; }

        /// <summary>
        /// 收货人
        /// </summary>
        [Description("收货人")]
        [Column(DbType = DbType.AnsiString)]
        public string CONSIGNEE { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        public long? CREATE_USERID { get; set; }

        /// <summary>
        /// 添加人
        /// </summary>
        [Description("添加人")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        public long? MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改人
        /// </summary>
        [Description("修改人")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}