//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类sp_instore
    /// </summary>
    [Table("sp_instore")]
    public class SP_INSTORE
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 入库单号
        /// </summary>
        [Description("入库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string IN_CODE { get; set; }

        /// <summary>
        /// 入库日期
        /// </summary>
        [Description("入库日期")]
        public DateTime? IN_DATE { get; set; }

        /// <summary>
        /// 订单号
        /// </summary>
        [Description("订单号")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDER_CODE { get; set; }

        /// <summary>
        /// 合同号
        /// </summary>
        [Description("合同号")]
        [Column(DbType = DbType.AnsiString)]
        public string CONTRACT_NO { get; set; }

        /// <summary>
        /// 供应商ID
        /// </summary>
        [Description("供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 入库金额
        /// </summary>
        [Description("入库金额")]
        public decimal? INSTORE_MONEY { get; set; }

        /// <summary>
        /// 采购人ID
        /// </summary>
        [Description("采购人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_USERID { get; set; }

        /// <summary>
        /// 采购人
        /// </summary>
        [Description("采购人")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_USER { get; set; }

        /// <summary>
        /// 仓管员ID
        /// </summary>
        [Description("仓管员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }

        /// <summary>
        /// 仓管员
        /// </summary>
        [Description("仓管员")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }

        /// <summary>
        /// 验收人ID
        /// </summary>
        [Description("验收人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHK_USERID { get; set; }

        /// <summary>
        /// 验收人
        /// </summary>
        [Description("验收人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHK_USER { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        [Description("仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 入库性质
        /// </summary>
        [Description("入库性质")]
        [Column(DbType = DbType.AnsiString)]
        public string PROPERTY { get; set; }

        /// <summary>
        /// 公司ID
        /// </summary>
        [Description("公司ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 公司名称
        /// </summary>
        [Description("公司名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string IN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 验收单ID
        /// </summary>
        [Description("验收单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string RECEIVE_ID { get; set; }

        /// <summary>
        /// 送货单号
        /// </summary>
        [Description("送货单号")]
        [Column(DbType = DbType.AnsiString)]
        public string DELIVERY_CODE { get; set; }

        /// <summary>
        /// 入库类型
        /// </summary>
        [Description("入库类型")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_TYPE { get; set; }

        /// <summary>
        /// 编制部门ID
        /// </summary>
        [Description("编制部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_DEPTID { get; set; }

        /// <summary>
        /// 编制部门
        /// </summary>
        [Description("编制部门")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_DEPT { get; set; }

        /// <summary>
        /// 盘点部门编码
        /// </summary>
        [Description("盘点部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 是否冲红
        /// </summary>
        [Description("是否冲红")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_RED { get; set; }

    }
}