//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 物料领用申请
    /// </summary>
    [Table("SP_OUT_APP")]
    public class SP_OUT_APP
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_A { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        [Description("仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 出库单号
        /// </summary>
        [Description("出库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_CODE { get; set; }

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_CODE { get; set; }

        /// <summary>
        /// 申请日期
        /// </summary>
        [Description("申请日期")]
        public DateTime? APPLY_DATE { get; set; }

        /// <summary>
        /// 出库日期
        /// </summary>
        [Description("出库日期")]
        public DateTime? OUT_DATE { get; set; }

        /// <summary>
        /// 出库性质
        /// </summary>
        [Description("出库性质")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_TYPE { get; set; }

        /// <summary>
        /// 领用部门ID
        /// </summary>
        [Description("领用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 领用部门编码
        /// </summary>
        [Description("领用部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 领用部门
        /// </summary>
        [Description("领用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 申请类型
        /// </summary>
        [Description("申请类型")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_TYPE { get; set; }

        /// <summary>
        /// 设备/设施ID
        /// </summary>
        [Description("设备/设施ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 设备/设施编码
        /// </summary>
        [Description("设备/设施编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_CODE { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NO { get; set; }

        /// <summary>
        /// 设备/设施名称
        /// </summary>
        [Description("设备/设施名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 规格型号
        /// </summary>
        [Description("规格型号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_SIZE { get; set; }

        /// <summary>
        /// 设备型号
        /// </summary>
        [Description("设备型号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_TYPE { get; set; }

        /// <summary>
        /// 资产单位ID
        /// </summary>
        [Description("资产单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string UDEPT_ID { get; set; }

        /// <summary>
        /// 资产单位编码
        /// </summary>
        [Description("资产单位编码")]
        [Column(DbType = DbType.AnsiString)]
        public string UDEPT_CODE { get; set; }

        /// <summary>
        /// 资产单位
        /// </summary>
        [Description("资产单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UDEPT_NAME { get; set; }

        /// <summary>
        /// 管理部门ID
        /// </summary>
        [Description("管理部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MDEPT_ID { get; set; }

        /// <summary>
        /// 管理部门编码
        /// </summary>
        [Description("管理部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string MDEPT_CODE { get; set; }

        /// <summary>
        /// 管理部门
        /// </summary>
        [Description("管理部门")]
        [Column(DbType = DbType.AnsiString)]
        public string MDEPT_NAME { get; set; }

        /// <summary>
        /// 项目编号
        /// </summary>
        [Description("项目编号")]
        [Column(DbType = DbType.AnsiString)]
        public string PROJECT_CODE { get; set; }

        /// <summary>
        /// 项目名称
        /// </summary>
        [Description("项目名称")]
        [Column(DbType = DbType.AnsiString)]
        public string PROJECT_NAME { get; set; }

        /// <summary>
        /// 工单号
        /// </summary>
        [Description("工单号")]
        [Column(DbType = DbType.AnsiString)]
        public string WORKSHEET_CODE { get; set; }

        /// <summary>
        /// 用途ID
        /// </summary>
        [Description("用途ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_ID { get; set; }

        /// <summary>
        /// 用途
        /// </summary>
        [Description("用途")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_NAME { get; set; }

        /// <summary>
        /// 领用人ID
        /// </summary>
        [Description("领用人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }

        /// <summary>
        /// 领用人
        /// </summary>
        [Description("领用人")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }

        /// <summary>
        /// 仓库员ID
        /// </summary>
        [Description("仓库员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string M_USERID { get; set; }

        /// <summary>
        /// 仓管员
        /// </summary>
        [Description("仓管员")]
        [Column(DbType = DbType.AnsiString)]
        public string M_USER { get; set; }

        /// <summary>
        /// 出库金额(元)
        /// </summary>
        [Description("出库金额(元)")]
        public decimal? SUM_MONEY { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 来源ID
        /// </summary>
        [Description("来源ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_ID { get; set; }

        /// <summary>
        /// 来源单号
        /// </summary>
        [Description("来源单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_CODE { get; set; }

        /// <summary>
        /// 是否主管审批
        /// </summary>
        [Description("是否主管审批")]
        [Column(DbType = DbType.AnsiString)]
        public string NEED_CHECK { get; set; }

        /// <summary>
        /// 来源类型
        /// </summary>
        [Description("来源类型")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_TYPE { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 旧件仓库ID
        /// </summary>
        [Description("旧件仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string OLD_HOUSEID { get; set; }

        /// <summary>
        /// 旧件仓库
        /// </summary>
        [Description("旧件仓库")]
        [Column(DbType = DbType.AnsiString)]
        public string OLD_HOUSE { get; set; }

        /// <summary>
        /// 旧件库位ID
        /// </summary>
        [Description("旧件库位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string OLD_STOCKID { get; set; }

        /// <summary>
        /// 旧件库位
        /// </summary>
        [Description("旧件库位")]
        [Column(DbType = DbType.AnsiString)]
        public string OLD_STOCK { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_B { get; set; }

        /// <summary>
        /// OA审批日期
        /// </summary>
        [Description("OA审批日期")]
        public DateTime? OA_DATE { get; set; }

        /// <summary>
        /// 流程ID
        /// </summary>
        [Description("流程ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string OUT_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 领用申请ID
        /// </summary>
        [Description("领用申请ID")]
        [Column(DbType = DbType.AnsiString)]
        public string OUTAPP_ID { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_LB { get; set; }

        /// <summary>
        /// 审核人
        /// </summary>
        [Description("审核人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHK_MAN { get; set; }

        /// <summary>
        /// 是否设备
        /// </summary>
        [Description("是否设备")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_DEV { get; set; }

        /// <summary>
        /// 退回原因
        /// </summary>
        [Description("退回原因")]
        [Column(DbType = DbType.AnsiString)]
        public string RETURN_MEMO { get; set; }

        /// <summary>
        /// 用途编号
        /// </summary>
        [Description("用途编号")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_NO { get; set; }

        /// <summary>
        /// 领用密码
        /// </summary>
        [Description("领用密码")]
        [Column(DbType = DbType.AnsiString)]
        public string LY_PWD { get; set; }

        /// <summary>
        /// 用途
        /// </summary>
        [Description("用途")]
        [Column(DbType = DbType.AnsiString)]
        public string YT { get; set; }

        /// <summary>
        /// 领用总升数
        /// </summary>
        [Description("领用总升数")]
        public decimal? SUM_COUNT { get; set; }

        /// <summary>
        /// 油品单价
        /// </summary>
        [Description("油品单价")]
        public decimal? YPPRICE { get; set; }

        /// <summary>
        /// 是否APP申请
        /// </summary>
        [Description("是否APP申请")]
        [Column(DbType = DbType.AnsiString)]
        public string APPAPPLY { get; set; }

    }
}