//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类物料出库明细
    /// </summary>
    [Table("SP_OUTSTORE_DET")]
    public class SP_OUTSTORE_DET
    {

        /// <summary>
        /// 发票号
        /// </summary>
        [Description("发票号")]
        [Column(DbType = DbType.AnsiString)]
        public string INVOICE_CODE { get; set; }

        /// <summary>
        /// 是否借用
        /// </summary>
        [Description("是否借用")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_REND { get; set; }

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_NO { get; set; }

        /// <summary>
        /// 物料ID
        /// </summary>
        [Description("物料ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 标准编号
        /// </summary>
        [Description("标准编号")]
        [Column(DbType = DbType.AnsiString)]
        public string COMP_CODE { get; set; }

        /// <summary>
        /// 标准编号
        /// </summary>
        [Description("标准编号")]
        [Column(DbType = DbType.AnsiString)]
        public string STANDARD_CODE { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 规格型号
        /// </summary>
        [Description("规格型号")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 重量(KG)
        /// </summary>
        [Description("重量(KG)")]
        public decimal? WEIGHT { get; set; }

        /// <summary>
        /// 分类编码
        /// </summary>
        [Description("分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 分类ID
        /// </summary>
        [Description("分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 分类名称
        /// </summary>
        [Description("分类名称")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 申请数量
        /// </summary>
        [Description("申请数量")]
        public decimal? APPLY_NUM { get; set; }

        /// <summary>
        /// 出库数量
        /// </summary>
        [Description("出库数量")]
        public decimal? COUNT { get; set; }

        /// <summary>
        /// 退货数量
        /// </summary>
        [Description("退货数量")]
        public decimal? RETURN_NUM { get; set; }

        /// <summary>
        /// 退旧件数量
        /// </summary>
        [Description("退旧件数量")]
        public decimal? REC_NUM { get; set; }

        /// <summary>
        /// 库存数量
        /// </summary>
        [Description("库存数量")]
        public decimal? STORE_NUM { get; set; }

        /// <summary>
        /// 是否出库冲红
        /// </summary>
        [Description("是否出库冲红")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_OUTBACK { get; set; }

        /// <summary>
        /// 参考单价(元)
        /// </summary>
        [Description("参考单价(元)")]
        public decimal? PRICE { get; set; }

        /// <summary>
        /// 财务价格(元)
        /// </summary>
        [Description("财务价格(元)")]
        public decimal? FINANCE_PRICE { get; set; }

        /// <summary>
        /// 金额(元)
        /// </summary>
        [Description("金额(元)")]
        public decimal? APPLY_MONEY { get; set; }

        /// <summary>
        /// 金额(元)
        /// </summary>
        [Description("金额(元)")]
        public decimal? MONEY { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        [Description("仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 不含税单价(元)
        /// </summary>
        [Description("不含税单价(元)")]
        public decimal? NOTAX_PRICE { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 库位ID
        /// </summary>
        [Description("库位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_ID { get; set; }

        /// <summary>
        /// 不含税金额(元)
        /// </summary>
        [Description("不含税金额(元)")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 库位名称
        /// </summary>
        [Description("库位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_NAME { get; set; }

        /// <summary>
        /// 批次号
        /// </summary>
        [Description("批次号")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_CODE { get; set; }

        /// <summary>
        /// 税率
        /// </summary>
        [Description("税率")]
        public decimal? TAX_RATE { get; set; }

        /// <summary>
        /// 入库日期
        /// </summary>
        [Description("入库日期")]
        public DateTime? IN_DATE { get; set; }

        /// <summary>
        /// 是否回收
        /// </summary>
        [Description("是否回收")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_RECOVERY { get; set; }

        /// <summary>
        /// 是否零库存领用
        /// </summary>
        [Description("是否零库存领用")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_FIC { get; set; }

        /// <summary>
        /// 其他编号
        /// </summary>
        [Description("其他编号")]
        [Column(DbType = DbType.AnsiString)]
        public string OTHER_CODE { get; set; }

        /// <summary>
        /// 资产归属ID
        /// </summary>
        [Description("资产归属ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 库存归属ID
        /// </summary>
        [Description("库存归属ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_DEPT_ID { get; set; }

        /// <summary>
        /// 部门名称
        /// </summary>
        [Description("部门名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 设备ID
        /// </summary>
        [Description("设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NO { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 说明
        /// </summary>
        [Description("说明")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 库存ID
        /// </summary>
        [Description("库存ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_ID { get; set; }

        /// <summary>
        /// 来源ID
        /// </summary>
        [Description("来源ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string OUTDET_ID { get; set; }

        /// <summary>
        /// 用友账套
        /// </summary>
        [Description("用友账套")]
        [Column(DbType = DbType.AnsiString)]
        public string YONGYOU_ZT { get; set; }

        /// <summary>
        /// 出库单ID
        /// </summary>
        [Description("出库单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_ID { get; set; }

        /// <summary>
        /// 流水账ID
        /// </summary>
        [Description("流水账ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WATER_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 货位编码
        /// </summary>
        [Description("货位编码")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_CODE { get; set; }

        /// <summary>
        /// 采购分类
        /// </summary>
        [Description("采购分类")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_NAME { get; set; }

        /// <summary>
        /// 采购ID
        /// </summary>
        [Description("采购ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_ID { get; set; }

        /// <summary>
        /// 领用公司
        /// </summary>
        [Description("领用公司")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME2 { get; set; }

    }
}