//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;
namespace Gksyb.Model
{
    /// <summary>
    /// 实体类SP_OUTSTORE_DET
    /// </summary>
    [Table("SP_OUTSTORE_DET")]
    public class SP_OUTSTORE_DET
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string OUT_DET_ID { get; set; }

        /// <summary>
        /// 物资出库id
        /// </summary>
        [Description("物资出库id")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_ID { get; set; }

        /// <summary>
        /// 库存id
        /// </summary>
        [Description("库存id")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_ID { get; set; }

        /// <summary>
        /// 批次号
        /// </summary>
        [Description("批次号")]
        [Column(DbType = DbType.AnsiString)]
        public string BATCH_CODE { get; set; }

        /// <summary>
        /// 物资id
        /// </summary>
        [Description("物资id")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 物资名称
        /// </summary>
        [Description("物资名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 物资编码
        /// </summary>
        [Description("物资编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物资分类id
        /// </summary>
        [Description("物资分类id")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 物资分类名称
        /// </summary>
        [Description("物资分类名称")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 属性
        /// </summary>
        [Description("属性")]
        [Column(DbType = DbType.AnsiString)]
        public string PROPERTY { get; set; }

        /// <summary>
        /// 出库数量
        /// </summary>
        [Description("出库数量")]
        public decimal? OUT_NUM { get; set; }

        /// <summary>
        /// 出库含税金额
        /// </summary>
        [Description("出库含税金额")]
        public decimal? TAX_MONEY { get; set; }

        /// <summary>
        /// 出库不含税金额
        /// </summary>
        [Description("出库不含税金额")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 仓库id
        /// </summary>
        [Description("仓库id")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 仓库编码
        /// </summary>
        [Description("仓库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_CODE { get; set; }

        /// <summary>
        /// 设备id
        /// </summary>
        [Description("设备id")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NO { get; set; }

        /// <summary>
        /// 添加人id
        /// </summary>
        [Description("添加人id")]
        public long? CREATE_USERID { get; set; }

        /// <summary>
        /// 添加人
        /// </summary>
        [Description("添加人")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人id
        /// </summary>
        [Description("修改人id")]
        public long? MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改人
        /// </summary>
        [Description("修改人")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}