//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 物料出库冲红
    /// </summary>
    [Table("SP_OUT_BACK")]
    public class SP_OUT_BACK
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 冲红日期
        /// </summary>
        [Description("冲红日期")]
        public DateTime? BACK_DATE { get; set; }

        /// <summary>
        /// 冲红单号
        /// </summary>
        [Description("冲红单号")]
        [Column(DbType = DbType.AnsiString)]
        public string BACK_CODE { get; set; }

        /// <summary>
        /// 出库ID
        /// </summary>
        [Description("出库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_ID { get; set; }

        /// <summary>
        /// 出库单号
        /// </summary>
        [Description("出库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_CODE { get; set; }

        /// <summary>
        /// 出库日期
        /// </summary>
        [Description("出库日期")]
        public DateTime? OUT_DATE { get; set; }

        /// <summary>
        /// 编制人
        /// </summary>
        [Description("编制人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 编制人
        /// </summary>
        [Description("编制人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 申请部门ID
        /// </summary>
        [Description("申请部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 领用人ID
        /// </summary>
        [Description("领用人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }

        /// <summary>
        /// 领用人
        /// </summary>
        [Description("领用人")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }

        /// <summary>
        /// 冲红金额
        /// </summary>
        [Description("冲红金额")]
        public decimal? SUM_MONEY { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string OUT_BACK_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}