//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{

    /// <summary>
    /// 实体类sp_purplan
    /// </summary>
    [Table("sp_purplan")]
    public class SP_PURPLAN
    {

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_NO { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 询价单号
        /// </summary>
        [Description("询价单号")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_NO { get; set; }

        /// <summary>
        /// 询价日期
        /// </summary>
        [Description("询价日期")]
        public DateTime? PLAN_DATE { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 申请部门编码
        /// </summary>
        [Description("申请部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 是否协议供货
        /// </summary>
        [Description("是否协议供货")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_SUPPACT { get; set; }

        /// <summary>
        /// 询价下达人ID
        /// </summary>
        [Description("询价下达人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string XJDOWN_USERID { get; set; }

        /// <summary>
        /// 询价下达人
        /// </summary>
        [Description("询价下达人")]
        [Column(DbType = DbType.AnsiString)]
        public string XJDOWN_USER { get; set; }

        /// <summary>
        /// 询价人ID
        /// </summary>
        [Description("询价人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string XJ_USER { get; set; }

        /// <summary>
        /// 询价人
        /// </summary>
        [Description("询价人")]
        [Column(DbType = DbType.AnsiString)]
        public string XJ_USERID { get; set; }

        /// <summary>
        /// 中标供应商ID
        /// </summary>
        [Description("中标供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_PROVIDERID { get; set; }

        /// <summary>
        /// 中标供应商
        /// </summary>
        [Description("中标供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_PROVIDER { get; set; }

        /// <summary>
        /// 采购分类ID
        /// </summary>
        [Description("采购分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 采购分类编码
        /// </summary>
        [Description("采购分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 采购分类
        /// </summary>
        [Description("采购分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// OA审批结果
        /// </summary>
        [Description("OA审批结果")]
        [Column(DbType = DbType.AnsiString)]
        public string OA_CHECK { get; set; }

        /// <summary>
        /// OA审批时间
        /// </summary>
        [Description("OA审批时间")]
        public DateTime? OA_DATE { get; set; }

        /// <summary>
        /// OA退回理由
        /// </summary>
        [Description("OA退回理由")]
        [Column(DbType = DbType.AnsiString)]
        public string OA_MEMO { get; set; }

        /// <summary>
        /// OA审批流ID
        /// </summary>
        [Description("OA审批流ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_ID { get; set; }

        /// <summary>
        /// 采购申请ID
        /// </summary>
        [Description("采购申请ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_ID { get; set; }

        /// <summary>
        /// 总金额(元)
        /// </summary>
        [Description("总金额(元)")]
        public decimal? SUM_MONEY { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string PURPLAN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 询价状态
        /// </summary>
        [Description("询价状态")]
        [Column(DbType = DbType.AnsiString)]
        public string STATUS { get; set; }

        /// <summary>
        /// 是否协议
        /// </summary>
        [Description("是否协议")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_PRO { get; set; }

        /// <summary>
        /// 标的名称
        /// </summary>
        [Description("标的名称")]
        [Column(DbType = DbType.AnsiString)]
        public string BD_NAME { get; set; }

        /// <summary>
        /// 计划供应商
        /// </summary>
        [Description("计划供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 计划供应商ID
        /// </summary>
        [Description("计划供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 采购员OAID
        /// </summary>
        [Description("采购员OAID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_CODE { get; set; }

        /// <summary>
        /// 采购员ID
        /// </summary>
        [Description("采购员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_USERID { get; set; }

        /// <summary>
        /// 采购员
        /// </summary>
        [Description("采购员")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_USER { get; set; }

        /// <summary>
        /// 流程标题
        /// </summary>
        [Description("流程标题")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_NAME { get; set; }

        /// <summary>
        /// 采购方式
        /// </summary>
        [Description("采购方式")]
        [Column(DbType = DbType.AnsiString)]
        public string CGFS { get; set; }

        /// <summary>
        /// 手机号
        /// </summary>
        [Description("手机号")]
        [Column(DbType = DbType.AnsiString)]
        public string MOB_CODE { get; set; }

        /// <summary>
        /// 采购方式
        /// </summary>
        [Description("采购方式")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_TYPE { get; set; }

        /// <summary>
        /// 采购方式ID
        /// </summary>
        [Description("采购方式ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_TYPEID { get; set; }

        /// <summary>
        /// 实施主体
        /// </summary>
        [Description("实施主体")]
        [Column(DbType = DbType.AnsiString)]
        public string SSZT { get; set; }

        /// <summary>
        /// 实施主体ID
        /// </summary>
        [Description("实施主体ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SSZTID { get; set; }

        /// <summary>
        /// 采购员手机号
        /// </summary>
        [Description("采购员手机号")]
        [Column(DbType = DbType.AnsiString)]
        public string MOBILE { get; set; }

        /// <summary>
        /// 采购员ID
        /// </summary>
        [Description("采购员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CGYID { get; set; }

        /// <summary>
        /// 采购员部门ID
        /// </summary>
        [Description("采购员部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CGYDEPTID { get; set; }

        /// <summary>
        /// 采购员
        /// </summary>
        [Description("采购员")]
        [Column(DbType = DbType.AnsiString)]
        public string CGY { get; set; }

        /// <summary>
        /// OA单号
        /// </summary>
        [Description("OA单号")]
        [Column(DbType = DbType.AnsiString)]
        public string OACODE { get; set; }

        /// <summary>
        /// 竞价JSON
        /// </summary>
        [Description("竞价JSON")]
        [Column(DbType = DbType.AnsiString)]
        public string JJ_JSON { get; set; }

        /// <summary>
        /// 竞价JSON
        /// </summary>
        [Description("竞价JSON")]
        [Column(DbType = DbType.AnsiString)]
        public string JJ_JSON3 { get; set; }

        /// <summary>
        /// 是否紧急采购
        /// </summary>
        [Description("是否紧急采购")]
        [Column(DbType = DbType.AnsiString)]
        public string ID_URGENT_PURCHASE { get; set; }

    }

}