//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{

    /// <summary>
    /// 实体类sp_purplan_det
    /// </summary>
    [Table("sp_purplan_det")]
    public class SP_PURPLAN_DET
    {

        /// <summary>
        /// 状态
        /// </summary>
        [Description("状态")]
        [Column(DbType = DbType.AnsiString)]
        public string STATUS { get; set; }

        /// <summary>
        /// 申请ID
        /// </summary>
        [Description("申请ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_ID { get; set; }

        /// <summary>
        /// 物料ID
        /// </summary>
        [Description("物料ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 单位
        /// </summary>
        [Description("单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 数量
        /// </summary>
        [Description("数量")]
        public decimal? COUNT { get; set; }

        /// <summary>
        /// 单价(元)
        /// </summary>
        [Description("单价(元)")]
        public decimal? PRICE { get; set; }

        /// <summary>
        /// 金额(元)
        /// </summary>
        [Description("金额(元)")]
        public decimal? MONEY { get; set; }

        /// <summary>
        /// 库存数量
        /// </summary>
        [Description("库存数量")]
        public decimal? STORE_NUM { get; set; }

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_NO { get; set; }

        /// <summary>
        /// 申请日期
        /// </summary>
        [Description("申请日期")]
        public DateTime? APPLY_DATE { get; set; }

        /// <summary>
        /// 申请部门ID
        /// </summary>
        [Description("申请部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 申请部门编码
        /// </summary>
        [Description("申请部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 上次入库单价
        /// </summary>
        [Description("上次入库单价")]
        public decimal? LAST_PRICE { get; set; }

        /// <summary>
        /// 上次供应商ID
        /// </summary>
        [Description("上次供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string LAST_PROVIDERID { get; set; }

        /// <summary>
        /// 上次供应商
        /// </summary>
        [Description("上次供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string LAST_PROVIDER { get; set; }

        /// <summary>
        /// 紧急程度
        /// </summary>
        [Description("紧急程度")]
        [Column(DbType = DbType.AnsiString)]
        public string EXIG_DEV { get; set; }

        /// <summary>
        /// 设备ID
        /// </summary>
        [Description("设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_CODE { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 分类ID
        /// </summary>
        [Description("分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 物料分类ID
        /// </summary>
        [Description("物料分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 物料分类
        /// </summary>
        [Description("物料分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 时间要求
        /// </summary>
        [Description("时间要求")]
        [Column(DbType = DbType.AnsiString)]
        public string TIME_REQ { get; set; }

        /// <summary>
        /// 项目编号
        /// </summary>
        [Description("项目编号")]
        [Column(DbType = DbType.AnsiString)]
        public string PROJECT_CODE { get; set; }

        /// <summary>
        /// 供应周期(天)
        /// </summary>
        [Description("供应周期(天)")]
        [Column(DbType = DbType.AnsiString)]
        public string PERIOD { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 采购申请流程ID
        /// </summary>
        [Description("采购申请流程ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REQUEST_ID { get; set; }

        /// <summary>
        /// 询价单ID
        /// </summary>
        [Description("询价单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PURPLAN_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string PLAN_ID { get; set; }

        /// <summary>
        /// 采购申请ID
        /// </summary>
        [Description("采购申请ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SPDET_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 用途
        /// </summary>
        [Description("用途")]
        [Column(DbType = DbType.AnsiString)]
        public string USE_MEMO { get; set; }

        /// <summary>
        /// 需求备注
        /// </summary>
        [Description("需求备注")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_MEMO { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USERID { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USER { get; set; }

        /// <summary>
        /// 要求交货日期
        /// </summary>
        [Description("要求交货日期")]
        public DateTime? REQ_DATE { get; set; }

        /// <summary>
        /// 质保期
        /// </summary>
        [Description("质保期")]
        public decimal? WARRANTY { get; set; }

        /// <summary>
        /// 预估金额(元)
        /// </summary>
        [Description("预估金额(元)")]
        public decimal? YG_MONEY { get; set; }

        /// <summary>
        /// 询价终止时间
        /// </summary>
        [Description("询价终止时间")]
        public DateTime? STOP_DATE { get; set; }

        /// <summary>
        /// 使用地点
        /// </summary>
        [Description("使用地点")]
        [Column(DbType = DbType.AnsiString)]
        public string SYDD { get; set; }

        /// <summary>
        /// 采购方式
        /// </summary>
        [Description("采购方式")]
        [Column(DbType = DbType.AnsiString)]
        public string CGFS { get; set; }

        /// <summary>
        /// 消耗周期
        /// </summary>
        [Description("消耗周期")]
        [Column(DbType = DbType.AnsiString)]
        public string XHZQ { get; set; }

        /// <summary>
        /// 使用地点
        /// </summary>
        [Description("使用地点")]
        [Column(DbType = DbType.AnsiString)]
        public string SYDDDEPTID { get; set; }

        /// <summary>
        /// 数量
        /// </summary>
        [Description("数量")]
        public decimal? COUNT2 { get; set; }

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE2 { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME2 { get; set; }

        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE2 { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE2 { get; set; }

        /// <summary>
        /// 单位
        /// </summary>
        [Description("单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT2 { get; set; }

    }

}