//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类sp_receive_det
    /// </summary>
    [Table("sp_receive_det")]
    public class SP_RECEIVE_DET
    {

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 规格型号
        /// </summary>
        [Description("规格型号")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 数量
        /// </summary>
        [Description("数量")]
        public decimal? COUNT { get; set; }

        /// <summary>
        /// 验收数量
        /// </summary>
        [Description("验收数量")]
        public decimal? CHK_COUNT { get; set; }

        /// <summary>
        /// 金额(元)
        /// </summary>
        [Description("金额(元)")]
        public decimal? CHK_MONEY { get; set; }

        /// <summary>
        /// 单价(元)
        /// </summary>
        [Description("单价(元)")]
        public decimal? PRICE { get; set; }

        /// <summary>
        /// 金额(元)
        /// </summary>
        [Description("金额(元)")]
        public decimal? MONEY { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USER { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_USERID { get; set; }

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_NO { get; set; }

        /// <summary>
        /// 项目编号
        /// </summary>
        [Description("项目编号")]
        [Column(DbType = DbType.AnsiString)]
        public string PROJECT_CODE { get; set; }

        /// <summary>
        /// 分类ID
        /// </summary>
        [Description("分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 分类编码
        /// </summary>
        [Description("分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 分类名称
        /// </summary>
        [Description("分类名称")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 说明
        /// </summary>
        [Description("说明")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 申请明细ID
        /// </summary>
        [Description("申请明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SPDET_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string RECDET_ID { get; set; }

        /// <summary>
        /// 订单明细ID
        /// </summary>
        [Description("订单明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDERDET_ID { get; set; }

        /// <summary>
        /// 主表主键
        /// </summary>
        [Description("主表主键")]
        [Column(DbType = DbType.AnsiString)]
        public string RECEIVE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 需求备注
        /// </summary>
        [Description("需求备注")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_MEMO { get; set; }

        /// <summary>
        /// 用途
        /// </summary>
        [Description("用途")]
        [Column(DbType = DbType.AnsiString)]
        public string USE_MEMO { get; set; }

        /// <summary>
        /// 退回来源ID
        /// </summary>
        [Description("退回来源ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_ID { get; set; }

        /// <summary>
        /// 是否退回
        /// </summary>
        [Description("是否退回")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_STOP { get; set; }

        /// <summary>
        /// 物料ID
        /// </summary>
        [Description("物料ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 是否待处理
        /// </summary>
        [Description("是否待处理")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_PENDING { get; set; }

        /// <summary>
        /// 退回说明
        /// </summary>
        [Description("退回说明")]
        [Column(DbType = DbType.AnsiString)]
        public string RETURN_MEMO { get; set; }

        /// <summary>
        /// 送货单号
        /// </summary>
        [Description("送货单号")]
        [Column(DbType = DbType.AnsiString)]
        public string DELIVERY_CODE { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 申请部门
        /// </summary>
        [Description("申请部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 货位编码
        /// </summary>
        [Description("货位编码")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_CODE { get; set; }

        /// <summary>
        /// 货位名称
        /// </summary>
        [Description("货位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_NAME { get; set; }

        /// <summary>
        /// 货位ID
        /// </summary>
        [Description("货位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_ID { get; set; }

        /// <summary>
        /// 不含税单价(元)
        /// </summary>
        [Description("不含税单价(元)")]
        public decimal? NOTAX_PRICE { get; set; }

        /// <summary>
        /// 不含税金额(元)
        /// </summary>
        [Description("不含税金额(元)")]
        public decimal? UNTAX_MONEY { get; set; }

        /// <summary>
        /// 税率
        /// </summary>
        [Description("税率")]
        public decimal? TAX_RATE { get; set; }

        /// <summary>
        /// 数量
        /// </summary>
        [Description("数量")]
        public decimal? COUNT2 { get; set; }

        /// <summary>
        /// 验收数量
        /// </summary>
        [Description("验收数量")]
        public decimal? CHK_COUNT2 { get; set; }

        /// <summary>
        /// 单价(元)
        /// </summary>
        [Description("单价(元)")]
        public decimal? PRICE2 { get; set; }

        /// <summary>
        /// 库存主键
        /// </summary>
        [Description("库存主键")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_ID { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 入库日期
        /// </summary>
        [Description("入库日期")]
        public DateTime? IN_DATE { get; set; }

    }
}