//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类sp_receive
    /// </summary>
    [Table("sp_receive")]
    public class SP_RECEIVE
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_CHK { get; set; }

        /// <summary>
        /// 送货单号
        /// </summary>
        [Description("送货单号")]
        [Column(DbType = DbType.AnsiString)]
        public string DELIVERY_CODE { get; set; }

        /// <summary>
        /// 登记单号
        /// </summary>
        [Description("登记单号")]
        [Column(DbType = DbType.AnsiString)]
        public string RECEIVE_CODE { get; set; }

        /// <summary>
        /// 收货日期
        /// </summary>
        [Description("收货日期")]
        public DateTime? RECEIVE_DATE { get; set; }

        /// <summary>
        /// 收货人ID
        /// </summary>
        [Description("收货人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }

        /// <summary>
        /// 收货人
        /// </summary>
        [Description("收货人")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }

        /// <summary>
        /// 是否入库
        /// </summary>
        [Description("是否入库")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_INSTORE { get; set; }

        /// <summary>
        /// 供应商ID
        /// </summary>
        [Description("供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 订单ID
        /// </summary>
        [Description("订单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDER_ID { get; set; }

        /// <summary>
        /// 订单号
        /// </summary>
        [Description("订单号")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDER_CODE { get; set; }

        /// <summary>
        /// 合同号
        /// </summary>
        [Description("合同号")]
        [Column(DbType = DbType.AnsiString)]
        public string CONTRACT_NO { get; set; }

        /// <summary>
        /// 验收部门ID
        /// </summary>
        [Description("验收部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 验收部门
        /// </summary>
        [Description("验收部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 采购人ID
        /// </summary>
        [Description("采购人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_USERID { get; set; }

        /// <summary>
        /// 采购人
        /// </summary>
        [Description("采购人")]
        [Column(DbType = DbType.AnsiString)]
        public string PUR_USER { get; set; }

        /// <summary>
        /// 申请人ID
        /// </summary>
        [Description("申请人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHK_USERID { get; set; }

        /// <summary>
        /// 申请人
        /// </summary>
        [Description("申请人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHK_USER { get; set; }

        /// <summary>
        /// 验收意见
        /// </summary>
        [Description("验收意见")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string REG_MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string RECEIVE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 二级部门ID
        /// </summary>
        [Description("二级部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级部门
        /// </summary>
        [Description("二级部门")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 验收日期
        /// </summary>
        [Description("验收日期")]
        public DateTime? CHK_DATE { get; set; }

        /// <summary>
        /// 编制部门ID
        /// </summary>
        [Description("编制部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_DEPTID { get; set; }

        /// <summary>
        /// 编制部门
        /// </summary>
        [Description("编制部门")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_DEPT { get; set; }

        /// <summary>
        /// 验收人ID
        /// </summary>
        [Description("验收人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 验收人
        /// </summary>
        [Description("验收人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 申购公司
        /// </summary>
        [Description("申购公司")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME2 { get; set; }

        /// <summary>
        /// 发票号
        /// </summary>
        [Description("发票号")]
        [Column(DbType = DbType.AnsiString)]
        public string INVOICE_CODE { get; set; }

        /// <summary>
        /// 仓库货位名称
        /// </summary>
        [Description("仓库货位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

    }
}