//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类sp_stop_det
    /// </summary>
    [Table("sp_stop_det")]
    public class SP_STOP_DET
    {

        /// <summary>
        /// 中止数量
        /// </summary>
        [Description("中止数量")]
        public decimal? STOP_NUM { get; set; }

        /// <summary>
        /// 订单ID
        /// </summary>
        [Description("订单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDER_ID { get; set; }

        /// <summary>
        /// 订单明细ID
        /// </summary>
        [Description("订单明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDERDET_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string STOP_DET_ID { get; set; }

        /// <summary>
        /// 中止ID
        /// </summary>
        [Description("中止ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOP_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 中止数量
        /// </summary>
        [Description("中止数量")]
        public decimal? STOP_NUM2 { get; set; }

    }

}