//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{

    /// <summary>
    /// 实体类sp_scan
    /// </summary>
    [Table("sp_scan")]
    public class SP_SCAN
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_LOSS { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_MORE { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 盘点单号
        /// </summary>
        [Description("盘点单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_CODE { get; set; }

        /// <summary>
        /// 盘点状态
        /// </summary>
        [Description("盘点状态")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_STATUS { get; set; }

        /// <summary>
        /// 盘点类型
        /// </summary>
        [Description("盘点类型")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_TYPE { get; set; }

        /// <summary>
        /// 盘点仓库编码
        /// </summary>
        [Description("盘点仓库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_CODE { get; set; }

        /// <summary>
        /// 盘点仓库
        /// </summary>
        [Description("盘点仓库")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 盘点仓库ID
        /// </summary>
        [Description("盘点仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 盘点库位编码
        /// </summary>
        [Description("盘点库位编码")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_CODE { get; set; }

        /// <summary>
        /// 盘点库位
        /// </summary>
        [Description("盘点库位")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_NAME { get; set; }

        /// <summary>
        /// 盘点库位ID
        /// </summary>
        [Description("盘点库位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_ID { get; set; }

        /// <summary>
        /// 备件类别编码
        /// </summary>
        [Description("备件类别编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 盘点类别
        /// </summary>
        [Description("盘点类别")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 盘点类别ID
        /// </summary>
        [Description("盘点类别ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 盘点部门
        /// </summary>
        [Description("盘点部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 盘点部门ID
        /// </summary>
        [Description("盘点部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 盘点日期
        /// </summary>
        [Description("盘点日期")]
        public DateTime? SCAN_DATE { get; set; }

        /// <summary>
        /// 盘点人
        /// </summary>
        [Description("盘点人")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_USER { get; set; }

        /// <summary>
        /// 盘点人ID
        /// </summary>
        [Description("盘点人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_USERID { get; set; }

        /// <summary>
        /// 盘点任务备注
        /// </summary>
        [Description("盘点任务备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 盘盈单号
        /// </summary>
        [Description("盘盈单号")]
        [Column(DbType = DbType.AnsiString)]
        public string MORE_CODE { get; set; }

        /// <summary>
        /// 盘盈日期
        /// </summary>
        [Description("盘盈日期")]
        public DateTime? MORE_DATE { get; set; }

        /// <summary>
        /// 盘盈原因
        /// </summary>
        [Description("盘盈原因")]
        [Column(DbType = DbType.AnsiString)]
        public string MORE_REASON { get; set; }

        /// <summary>
        /// 盘盈备注
        /// </summary>
        [Description("盘盈备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MORE_MEMO { get; set; }

        /// <summary>
        /// 盘亏单号
        /// </summary>
        [Description("盘亏单号")]
        [Column(DbType = DbType.AnsiString)]
        public string LOSS_CODE { get; set; }

        /// <summary>
        /// 盘亏日期
        /// </summary>
        [Description("盘亏日期")]
        public DateTime? LOSS_DATE { get; set; }

        /// <summary>
        /// 盘亏原因
        /// </summary>
        [Description("盘亏原因")]
        [Column(DbType = DbType.AnsiString)]
        public string LOSS_REASON { get; set; }

        /// <summary>
        /// 盘亏备注
        /// </summary>
        [Description("盘亏备注")]
        [Column(DbType = DbType.AnsiString)]
        public string LOSS_MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string SCAN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 盘点状态
        /// </summary>
        [Description("盘点状态")]
        [Column(DbType = DbType.AnsiString)]
        public string PDAUDIT { get; set; }

        /// <summary>
        /// 盘点结果
        /// </summary>
        [Description("盘点结果")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_RESULT { get; set; }

        /// <summary>
        /// 差异金额
        /// </summary>
        [Description("差异金额")]
        public decimal? CY_MONEY { get; set; }

    }

}