//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Gksyb.Model.Dtos
{
    /// <summary>
    /// 修改密码
    /// </summary>
    public class ChangePasswordRequest 
    {
        /// <summary>
        /// 账号
        /// </summary>
        [ModelEncrypt]
        public string Username { get; set; }

        /// <summary>
        /// 旧密码
        /// </summary>
        [ModelEncrypt]
        [Required]
        public string OldPassword { get; set; }

        /// <summary>
        /// 新密码
        /// </summary>
        [ModelEncrypt]
        [Required]
        public string NewPassword { get; set; }

    }
}