//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。  
//     作者：洪云龙
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------

using Gksyb.Model.Core;
using System.Linq.Expressions;

namespace Gksyb.Core.Interfaces.Auth
{
    /// <summary>
    /// 组织
    /// </summary>
    public static class CorpInfoExtensions
    {
        /// <summary>
        /// 公司
        /// </summary>
        public const string Company = "G";

        /// <summary>
        /// 部门
        /// </summary>
        public const string Department = "B";

        /// <summary>
        /// CF_CORP转CorpInfo
        /// </summary>
        public static CorpInfo ToCorpInfo(this CF_CORP source)
        {
            return new CorpInfo()
            {
                CorpID = source.CORPID,
                CNO = source.CNO,
                SName = source.CORP_SNAME,
                CName = source.CNAME,
                CorpParentID = source.CORPPARENTID,
                ClassFlag = source.CLASSFLAG
            };
        }

        /// <summary>
        /// CF_CORP转CorpInfo
        /// </summary>
        public static Expression<Func<CF_CORP, CorpInfo>> SelectCorpInfo => corp => new CorpInfo()
        {
            CorpID = corp.CORPID,
            CNO = corp.CNO,
            SName = corp.CORP_SNAME,
            CName = corp.CNAME,
            CorpParentID = corp.CORPPARENTID,
            ClassFlag = corp.CLASSFLAG
        };
    }
}
