//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。  
//     作者：洪云龙
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------

using Gksyb.Model.Core;
using System.Linq.Expressions;

namespace Gksyb.Core.Interfaces.Auth
{
    /// <summary>
    /// 用户
    /// </summary>
    public static class UserInfoExtensions
    {
        /// <summary>
        /// CF_USER转UserInfo
        /// </summary>
        public static UserInfo ToUserInfo(this CF_USER source)
        {
            return new UserInfo()
            {
                Id = source.USERID,
                Account = source.LOGINNAME,
                Name = source.REALNAME,
                WorkerCode = source.DEPARTCODE,
                Phone = source.PHONE
            };
        }

        /// <summary>
        /// CF_USER转UserInfo
        /// </summary>
        public static Expression<Func<CF_USER, UserInfo>> SelectUserInfo => c => new UserInfo()
        {
            Id = c.USERID,
            Account = c.LOGINNAME,
            Name = c.REALNAME,
            WorkerCode = c.DEPARTCODE,
            Phone =c.PHONE
        };
    }
}
