//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;
namespace Gksyb.Model
{
    /// <summary>
    /// 实体类WF_PROCESS
    /// </summary>
    [Table("WF_PROCESS")]
    public class WF_PROCESS
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string PROCESS_ID { get; set; }

        /// <summary>
        /// 外键（对应记录主键）
        /// </summary>
        [Description("外键（对应记录主键）")]
        [Column(DbType = DbType.AnsiString)]
        public string TASK_ID { get; set; }

        /// <summary>
        /// 审批操作
        /// </summary>
        [Description("审批操作")]
        [Column(DbType = DbType.AnsiString)]
        public string OPERATION { get; set; }

        /// <summary>
        /// 审批意见
        /// </summary>
        [Description("审批意见")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 任务接收时间
        /// </summary>
        [Description("任务接收时间")]
        public DateTime? RECEIVE_TIME { get; set; }

        /// <summary>
        /// 任务处理时间
        /// </summary>
        [Description("任务处理时间")]
        public DateTime? DEAL_TIME { get; set; }

        /// <summary>
        /// 任务处理人
        /// </summary>
        [Description("任务处理人")]
        [Column(DbType = DbType.AnsiString)]
        public string DEAL_USER { get; set; }

        /// <summary>
        /// 审批节点
        /// </summary>
        [Description("审批节点")]
        [Column(DbType = DbType.AnsiString)]
        public string NODE_NAME { get; set; }

        /// <summary>
        /// 是否撤回
        /// </summary>
        [Description("是否撤回")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_REBACK { get; set; }

    }
}