//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类BASE_DEVICE_COMPOSE
    /// </summary>
    [Table("BASE_DEVICE_COMPOSE")]
    public class BASE_DEVICE_COMPOSE
    {

        /// <summary>
        /// 设备结构编码
        /// </summary>
        [Description("设备结构编码")]
        [Column(DbType = DbType.AnsiString)]
        public string COMPOSE_CODE { get; set; }

        /// <summary>
        /// 等级
        /// </summary>
        [Description("等级")]
        public decimal? TYPE_LEVEL { get; set; }

        /// <summary>
        /// 级别
        /// </summary>
        [Description("级别")]
        public decimal? COMPOSE_LEVEL { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 设备结构名称
        /// </summary>
        [Description("设备结构名称")]
        [Column(DbType = DbType.AnsiString)]
        public string COMPOSE_NAME { get; set; }

        /// <summary>
        /// 设备全称
        /// </summary>
        [Description("设备全称")]
        [Column(DbType = DbType.AnsiString)]
        public string ALLNAME { get; set; }

        /// <summary>
        /// 工作单元
        /// </summary>
        [Description("工作单元")]
        [Column(DbType = DbType.AnsiString)]
        public string WORD_UNIT { get; set; }

        /// <summary>
        /// 机构
        /// </summary>
        [Description("机构")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTITUTION { get; set; }

        /// <summary>
        /// 部件
        /// </summary>
        [Description("部件")]
        [Column(DbType = DbType.AnsiString)]
        public string PARTS { get; set; }

        /// <summary>
        /// 器件
        /// </summary>
        [Description("器件")]
        [Column(DbType = DbType.AnsiString)]
        public string COMPONENT { get; set; }

        /// <summary>
        /// 设备分类
        /// </summary>
        [Description("设备分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 结构件
        /// </summary>
        [Description("结构件")]
        [Column(DbType = DbType.AnsiString)]
        public string STRUCTURE { get; set; }

        /// <summary>
        /// 功能件
        /// </summary>
        [Description("功能件")]
        [Column(DbType = DbType.AnsiString)]
        public string FUNCTOR { get; set; }

        /// <summary>
        /// 元件
        /// </summary>
        [Description("元件")]
        [Column(DbType = DbType.AnsiString)]
        public string ELEMENT { get; set; }

        /// <summary>
        /// 使用部门
        /// </summary>
        [Description("使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 类别ID
        /// </summary>
        [Description("类别ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string COMPOSE_ID { get; set; }

        /// <summary>
        /// 上级节点ID
        /// </summary>
        [Description("上级节点ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PRE_COMPOSEID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

    }
}