//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类DEVICE_CARD
    /// </summary>
    [Table("DEVICE_CARD")]
    public class DEVICE_CARD
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_CODE { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 设备机型
        /// </summary>
        [Description("设备机型")]
        [Column(DbType = DbType.AnsiString)]
        public string BOM_NAME { get; set; }

        /// <summary>
        /// 设备类别
        /// </summary>
        [Description("设备类别")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 设备型号
        /// </summary>
        [Description("设备型号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_TYPE { get; set; }

        /// <summary>
        /// 设备规格
        /// </summary>
        [Description("设备规格")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_SIZE { get; set; }

        /// <summary>
        /// 立卡日期
        /// </summary>
        [Description("立卡日期")]
        public DateTime? CARD_DATE { get; set; }

        /// <summary>
        /// 使用部门
        /// </summary>
        [Description("使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 使用二级单位
        /// </summary>
        [Description("使用二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 维保部门
        /// </summary>
        [Description("维保部门")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_NAME { get; set; }

        /// <summary>
        /// 维保二级单位
        /// </summary>
        [Description("维保二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPT { get; set; }

        /// <summary>
        /// 地理区域
        /// </summary>
        [Description("地理区域")]
        [Column(DbType = DbType.AnsiString)]
        public string SITE_NAME { get; set; }

        /// <summary>
        /// 安装地点
        /// </summary>
        [Description("安装地点")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTALL_SITE { get; set; }

        /// <summary>
        /// 启用日期
        /// </summary>
        [Description("启用日期")]
        public DateTime? REV_DATE { get; set; }

        /// <summary>
        /// 主设备ID
        /// </summary>
        [Description("主设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string FDEVICE_ID { get; set; }

        /// <summary>
        /// 主设备编号
        /// </summary>
        [Description("主设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string FDEVICE_CODE { get; set; }

        /// <summary>
        /// 专项管理属性
        /// </summary>
        [Description("专项管理属性")]
        [Column(DbType = DbType.AnsiString)]
        public string SPECIAL_TYPE { get; set; }

        /// <summary>
        /// ABC分类
        /// </summary>
        [Description("ABC分类")]
        [Column(DbType = DbType.AnsiString)]
        public string ABC_TYPE { get; set; }

        /// <summary>
        /// 标签编码
        /// </summary>
        [Description("标签编码")]
        [Column(DbType = DbType.AnsiString)]
        public string LABEL_CODE { get; set; }

        /// <summary>
        /// 当前管理状态
        /// </summary>
        [Description("当前管理状态")]
        [Column(DbType = DbType.AnsiString)]
        public string STATUS { get; set; }

        /// <summary>
        /// 状态变动日期
        /// </summary>
        [Description("状态变动日期")]
        public DateTime? STATUS_DATE { get; set; }

        /// <summary>
        /// 资产编号
        /// </summary>
        [Description("资产编号")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_CODE { get; set; }

        /// <summary>
        /// 财务分类
        /// </summary>
        [Description("财务分类")]
        [Column(DbType = DbType.AnsiString)]
        public string FINAN_TYPE { get; set; }

        /// <summary>
        /// 当前折旧月度
        /// </summary>
        [Description("当前折旧月度")]
        public DateTime? DEP_MONTH { get; set; }

        /// <summary>
        /// 当前累计折旧
        /// </summary>
        [Description("当前累计折旧")]
        public decimal? DEP_VALUE { get; set; }

        /// <summary>
        /// 安装及杂费(元)
        /// </summary>
        [Description("安装及杂费(元)")]
        public decimal? INSTALL_FEE { get; set; }

        /// <summary>
        /// 单价(元)
        /// </summary>
        [Description("单价(元)")]
        public decimal? PRICE { get; set; }

        /// <summary>
        /// 原值(元)
        /// </summary>
        [Description("原值(元)")]
        public decimal? ORG_VALUE { get; set; }

        /// <summary>
        /// 净值(元)
        /// </summary>
        [Description("净值(元)")]
        public decimal? NET_VALUE { get; set; }

        /// <summary>
        /// 使用年限(年)
        /// </summary>
        [Description("使用年限(年)")]
        public decimal? USE_YEAR { get; set; }

        /// <summary>
        /// 净残值比例(%)
        /// </summary>
        [Description("净残值比例(%)")]
        public decimal? NET_RATE { get; set; }

        /// <summary>
        /// 年折旧率(%)
        /// </summary>
        [Description("年折旧率(%)")]
        public decimal? DEP_RATE { get; set; }

        /// <summary>
        /// 资产来源
        /// </summary>
        [Description("资产来源")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_SOURCE { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 制造厂
        /// </summary>
        [Description("制造厂")]
        [Column(DbType = DbType.AnsiString)]
        public string FACTORY { get; set; }

        /// <summary>
        /// 出厂编号
        /// </summary>
        [Description("出厂编号")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_CODE { get; set; }

        /// <summary>
        /// 出厂日期
        /// </summary>
        [Description("出厂日期")]
        public DateTime? OUT_DATE { get; set; }

        /// <summary>
        /// 生产用途
        /// </summary>
        [Description("生产用途")]
        [Column(DbType = DbType.AnsiString)]
        public string PURPOSE { get; set; }

        /// <summary>
        /// 图号
        /// </summary>
        [Description("图号")]
        [Column(DbType = DbType.AnsiString)]
        public string GRAPH_NO { get; set; }

        /// <summary>
        /// 参数组
        /// </summary>
        [Description("参数组")]
        [Column(DbType = DbType.AnsiString)]
        public string PARAMS { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 维保二级单位ID
        /// </summary>
        [Description("维保二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPTID { get; set; }

        /// <summary>
        /// 维保部门ID
        /// </summary>
        [Description("维保部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_ID { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 供应商ID
        /// </summary>
        [Description("供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 类别ID
        /// </summary>
        [Description("类别ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 使用人
        /// </summary>
        [Description("使用人")]
        [Column(DbType = DbType.AnsiString)]
        public string CARD_USER { get; set; }

        /// <summary>
        /// 使用人ID
        /// </summary>
        [Description("使用人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CARD_USERID { get; set; }

        /// <summary>
        /// 地理区域ID
        /// </summary>
        [Description("地理区域ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SITE_ID { get; set; }

        /// <summary>
        /// 设备类别编码
        /// </summary>
        [Description("设备类别编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 设备机型ID
        /// </summary>
        [Description("设备机型ID")]
        [Column(DbType = DbType.AnsiString)]
        public string BOM_ID { get; set; }

        /// <summary>
        /// 安装验收ID
        /// </summary>
        [Description("安装验收ID")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTALL_ID { get; set; }

        /// <summary>
        /// 开箱验收明细ID
        /// </summary>
        [Description("开箱验收明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string BOX_DET_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

        /// <summary>
        /// 盘盈记录ID
        /// </summary>
        [Description("盘盈记录ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MORE_ID { get; set; }

        /// <summary>
        /// 地理区域编码
        /// </summary>
        [Description("地理区域编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SITE_CODE { get; set; }

        /// <summary>
        /// 设备机型编码
        /// </summary>
        [Description("设备机型编码")]
        [Column(DbType = DbType.AnsiString)]
        public string BOM_CODE { get; set; }

        /// <summary>
        /// 维保部门编码
        /// </summary>
        [Description("维保部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_CODE { get; set; }

        /// <summary>
        /// 部门编码
        /// </summary>
        [Description("部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 常用系数
        /// </summary>
        [Description("常用系数")]
        public decimal? USED_COUNT { get; set; }

        /// <summary>
        /// 船长
        /// </summary>
        [Description("船长")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_LENGTH { get; set; }

        /// <summary>
        /// 型宽
        /// </summary>
        [Description("型宽")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_WIDTH { get; set; }

        /// <summary>
        /// 型深
        /// </summary>
        [Description("型深")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_DEPTH { get; set; }

        /// <summary>
        /// 吃水
        /// </summary>
        [Description("吃水")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_DRAFT { get; set; }

        /// <summary>
        /// 船舶类型
        /// </summary>
        [Description("船舶类型")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_TYPE { get; set; }

        /// <summary>
        /// 主机功率
        /// </summary>
        [Description("主机功率")]
        [Column(DbType = DbType.AnsiString)]
        public string MAIN_POWER { get; set; }

        /// <summary>
        /// 副机功率
        /// </summary>
        [Description("副机功率")]
        [Column(DbType = DbType.AnsiString)]
        public string SECOND_POWER { get; set; }

        /// <summary>
        /// 坞修日期
        /// </summary>
        [Description("坞修日期")]
        public DateTime? REP_DATE { get; set; }

        /// <summary>
        /// 船舶识别号
        /// </summary>
        [Description("船舶识别号")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_ID { get; set; }

        /// <summary>
        /// 航速
        /// </summary>
        [Description("航速")]
        [Column(DbType = DbType.AnsiString)]
        public string SPEED { get; set; }

        /// <summary>
        /// 拖力
        /// </summary>
        [Description("拖力")]
        [Column(DbType = DbType.AnsiString)]
        public string DRAG_FORCE { get; set; }

        /// <summary>
        /// 总吨
        /// </summary>
        [Description("总吨")]
        [Column(DbType = DbType.AnsiString)]
        public string TOTAL_TON { get; set; }

        /// <summary>
        /// 净吨
        /// </summary>
        [Description("净吨")]
        [Column(DbType = DbType.AnsiString)]
        public string PURE_TON { get; set; }

        /// <summary>
        /// 排序序号
        /// </summary>
        [Description("排序序号")]
        public decimal? ORDINAL { get; set; }

        /// <summary>
        /// 是否环保设备
        /// </summary>
        [Description("是否环保设备")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_GREEN { get; set; }

        /// <summary>
        /// 坞修日期(五年)
        /// </summary>
        [Description("坞修日期(五年)")]
        public DateTime? REP_DATE5 { get; set; }

    }
}