//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类device_doc
    /// </summary>
    [Table("device_doc")]
    public class DEVICE_DOC
    {

        /// <summary>
        /// 档案编号
        /// </summary>
        [Description("档案编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DOC_CODE { get; set; }

        /// <summary>
        /// 资料名称
        /// </summary>
        [Description("资料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DOC_NAME { get; set; }

        /// <summary>
        /// 份数
        /// </summary>
        [Description("份数")]
        public decimal? DOC_NUM { get; set; }

        /// <summary>
        /// 存放地点
        /// </summary>
        [Description("存放地点")]
        [Column(DbType = DbType.AnsiString)]
        public string DOC_SITE { get; set; }

        /// <summary>
        /// 附件
        /// </summary>
        [Description("附件")]
        [Column(DbType = DbType.AnsiString)]
        public string DOC_ATTACH { get; set; }

        /// <summary>
        /// 说明
        /// </summary>
        [Description("说明")]
        [Column(DbType = DbType.AnsiString)]
        public string DOC_EXPLAIN { get; set; }

        /// <summary>
        /// 设备ID
        /// </summary>
        [Description("设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string DOC_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

    }
}