//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类device_vary
    /// </summary>
    [Table("device_vary")]
    public class DEVICE_VARY
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 变动单号
        /// </summary>
        [Description("变动单号")]
        [Column(DbType = DbType.AnsiString)]
        public string VARY_CODE { get; set; }

        /// <summary>
        /// 登记人
        /// </summary>
        [Description("登记人")]
        [Column(DbType = DbType.AnsiString)]
        public string EIDT_USER { get; set; }

        /// <summary>
        /// 登记人ID
        /// </summary>
        [Description("登记人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EIDT_USERID { get; set; }

        /// <summary>
        /// 调出使用部门
        /// </summary>
        [Description("调出使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 调出使用部门ID
        /// </summary>
        [Description("调出使用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 调出二级单位
        /// </summary>
        [Description("调出二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 调出二级单位ID
        /// </summary>
        [Description("调出二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 调入使用部门
        /// </summary>
        [Description("调入使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_NAME { get; set; }

        /// <summary>
        /// 调入使用部门ID
        /// </summary>
        [Description("调入使用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_ID { get; set; }

        /// <summary>
        /// 调入二级单位
        /// </summary>
        [Description("调入二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPT { get; set; }

        /// <summary>
        /// 调入二级单位ID
        /// </summary>
        [Description("调入二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPTID { get; set; }

        /// <summary>
        /// 申请日期
        /// </summary>
        [Description("申请日期")]
        public DateTime? APPLY_DATE { get; set; }

        /// <summary>
        /// 变动完成日期
        /// </summary>
        [Description("变动完成日期")]
        public DateTime? VARY_DATE { get; set; }

        /// <summary>
        /// 计划启用日期
        /// </summary>
        [Description("计划启用日期")]
        public DateTime? PLAN_START_DATE { get; set; }

        /// <summary>
        /// 设备总原值(元)
        /// </summary>
        [Description("设备总原值(元)")]
        public decimal? SUM_ORG_VALUE { get; set; }

        /// <summary>
        /// 设备总净值(元)
        /// </summary>
        [Description("设备总净值(元)")]
        public decimal? SUM_NET_VALUE { get; set; }

        /// <summary>
        /// 总已提折旧(元)
        /// </summary>
        [Description("总已提折旧(元)")]
        public decimal? SUM_DEP_VALUE { get; set; }

        /// <summary>
        /// 变卖总金额(元)
        /// </summary>
        [Description("变卖总金额(元)")]
        public decimal? SUM_ALLOT_MONEY { get; set; }

        /// <summary>
        /// 变动原因
        /// </summary>
        [Description("变动原因")]
        [Column(DbType = DbType.AnsiString)]
        public string REASONS { get; set; }

        /// <summary>
        /// 设备技术状态
        /// </summary>
        [Description("设备技术状态")]
        [Column(DbType = DbType.AnsiString)]
        public string TECH_STATUS { get; set; }

        /// <summary>
        /// 鉴定人
        /// </summary>
        [Description("鉴定人")]
        [Column(DbType = DbType.AnsiString)]
        public string APPRAISER { get; set; }

        /// <summary>
        /// 鉴定人ID
        /// </summary>
        [Description("鉴定人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPRAISER_ID { get; set; }

        /// <summary>
        /// 接收单位
        /// </summary>
        [Description("接收单位")]
        [Column(DbType = DbType.AnsiString)]
        public string RECEIVING { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 鉴定结果
        /// </summary>
        [Description("鉴定结果")]
        [Column(DbType = DbType.AnsiString)]
        public string RESULT { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string VARY_ID { get; set; }

        /// <summary>
        /// 变动类型
        /// </summary>
        [Description("变动类型")]
        [Column(DbType = DbType.AnsiString)]
        public string VARY_TYPE { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}