//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类device_base_param
    /// </summary>
    [Table("device_base_param")]
    public class DEVICE_BASE_PARAM
    {

        /// <summary>
        /// 一级参数名称
        /// </summary>
        [Description("一级参数名称")]
        [Column(DbType = DbType.AnsiString)]
        public string FIRST_PARAM_NAME { get; set; }

        /// <summary>
        /// 参数名称
        /// </summary>
        [Description("参数名称")]
        [Column(DbType = DbType.AnsiString)]
        public string PARAM_NAME { get; set; }

        /// <summary>
        /// 参数编号
        /// </summary>
        [Description("参数编号")]
        [Column(DbType = DbType.AnsiString)]
        public string PARAM_CODE { get; set; }

        /// <summary>
        /// 设备分类ID
        /// </summary>
        [Description("设备分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 设备分类名称
        /// </summary>
        [Description("设备分类名称")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 排序
        /// </summary>
        [Description("排序")]
        public decimal? SORT { get; set; }

        /// <summary>
        /// 参数单位
        /// </summary>
        [Description("参数单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 状态
        /// </summary>
        [Description("状态")]
        [Column(DbType = DbType.AnsiString)]
        public string STATUS { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string DEVICE_PARAMS_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

    }
}