//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类DEVICE_SCAN
    /// </summary>
    [Table("DEVICE_SCAN")]
    public class DEVICE_SCAN
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 盘点单号
        /// </summary>
        [Description("盘点单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SCAN_CODE { get; set; }

        /// <summary>
        /// 盘点状态
        /// </summary>
        [Description("盘点状态")]
        [Column(DbType = DbType.AnsiString)]
        public string STATUS { get; set; }

        /// <summary>
        /// 盘点部门
        /// </summary>
        [Description("盘点部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 设备类别
        /// </summary>
        [Description("设备类别")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// ABC分类
        /// </summary>
        [Description("ABC分类")]
        [Column(DbType = DbType.AnsiString)]
        public string ABC_TYPE { get; set; }

        /// <summary>
        /// 盘点人
        /// </summary>
        [Description("盘点人")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_NAME { get; set; }

        /// <summary>
        /// 盘点日期
        /// </summary>
        [Description("盘点日期")]
        public DateTime? SCAN_DATE { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 盘点人ID
        /// </summary>
        [Description("盘点人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string USER_ID { get; set; }

        /// <summary>
        /// 盘点部门ID
        /// </summary>
        [Description("盘点部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 盘点部门编码
        /// </summary>
        [Description("盘点部门编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_CODE { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 设备类别ID
        /// </summary>
        [Description("设备类别ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 标识
        /// </summary>
        [Description("标识")]
        [Column(DbType = DbType.AnsiString)]
        public string IDENT { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string SCAN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

    }
}