//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类device_remould
    /// </summary>
    [Table("device_remould")]
    public class DEVICE_REMOULD
    {

        /// <summary>
        /// 改造开始时间
        /// </summary>
        [Description("改造开始时间")]
        public DateTime? START_DATE { get; set; }

        /// <summary>
        /// 关联设备ID
        /// </summary>
        [Description("关联设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 改造结束时间
        /// </summary>
        [Description("改造结束时间")]
        [Column(DbType = DbType.AnsiString)]
        public string END_DATE { get; set; }

        /// <summary>
        /// 改造类型
        /// </summary>
        [Description("改造类型")]
        [Column(DbType = DbType.AnsiString)]
        public string REMOULD_TYPE { get; set; }

        /// <summary>
        /// 改造情况描述
        /// </summary>
        [Description("改造情况描述")]
        [Column(DbType = DbType.AnsiString)]
        public string REMOULD_DESC { get; set; }

        /// <summary>
        /// 是否完成改造
        /// </summary>
        [Description("是否完成改造")]
        [Column(DbType = DbType.AnsiString)]
        public string ISFINISH { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string REMARK { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string DEVICE_REMOULD_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}