//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类PM_PLAN_EXE
    /// </summary>
    [Table("PM_PLAN_EXE")]
    public class PM_PLAN_EXE
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_EXE { get; set; }

        /// <summary>
        /// 点检实施单号
        /// </summary>
        [Description("点检实施单号")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_CODE { get; set; }

        /// <summary>
        /// 点检定标编号
        /// </summary>
        [Description("点检定标编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DIN_CODE { get; set; }

        /// <summary>
        /// 点检标准编号
        /// </summary>
        [Description("点检标准编号")]
        [Column(DbType = DbType.AnsiString)]
        public string STD_CODE { get; set; }

        /// <summary>
        /// 点检标准名称
        /// </summary>
        [Description("点检标准名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STD_NAME { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_CODE { get; set; }

        /// <summary>
        /// 资产编号
        /// </summary>
        [Description("资产编号")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_CODE { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 设备型号
        /// </summary>
        [Description("设备型号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_TYPE { get; set; }

        /// <summary>
        /// 设备规格
        /// </summary>
        [Description("设备规格")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_SIZE { get; set; }

        /// <summary>
        /// 地理区域
        /// </summary>
        [Description("地理区域")]
        [Column(DbType = DbType.AnsiString)]
        public string SITE_NAME { get; set; }

        /// <summary>
        /// 安装地点
        /// </summary>
        [Description("安装地点")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTALL_SITE { get; set; }

        /// <summary>
        /// 使用部门
        /// </summary>
        [Description("使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 使用二级单位
        /// </summary>
        [Description("使用二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 维保单位
        /// </summary>
        [Description("维保单位")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_NAME { get; set; }

        /// <summary>
        /// 维保二级单位
        /// </summary>
        [Description("维保二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPT { get; set; }

        /// <summary>
        /// 计划点检时间
        /// </summary>
        [Description("计划点检时间")]
        public DateTime? STD_DATE { get; set; }

        /// <summary>
        /// 实际开工时间
        /// </summary>
        [Description("实际开工时间")]
        public DateTime? BEGIN_DATE { get; set; }

        /// <summary>
        /// 实际完工时间
        /// </summary>
        [Description("实际完工时间")]
        public DateTime? END_DATE { get; set; }

        /// <summary>
        /// 维保时长（小时）
        /// </summary>
        [Description("维保时长（小时）")]
        public decimal? MAINTENANCE_HOUR { get; set; }

        /// <summary>
        /// 点检实施时间(H)
        /// </summary>
        [Description("点检实施时间(H)")]
        public decimal? PLAN_DATE { get; set; }

        /// <summary>
        /// 是否有遗留问题
        /// </summary>
        [Description("是否有遗留问题")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_LOSE { get; set; }

        /// <summary>
        /// 实施人员
        /// </summary>
        [Description("实施人员")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_USER { get; set; }

        /// <summary>
        /// 遗留问题描述
        /// </summary>
        [Description("遗留问题描述")]
        [Column(DbType = DbType.AnsiString)]
        public string LEG_DESC { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 使用部门ID
        /// </summary>
        [Description("使用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 维保部门ID
        /// </summary>
        [Description("维保部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_ID { get; set; }

        /// <summary>
        /// 使用二级单位ID
        /// </summary>
        [Description("使用二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 维保二级单位ID
        /// </summary>
        [Description("维保二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPTID { get; set; }

        /// <summary>
        /// 实施人员ID
        /// </summary>
        [Description("实施人员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_USERID { get; set; }

        /// <summary>
        /// 点检定标ID
        /// </summary>
        [Description("点检定标ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DIN_ID { get; set; }

        /// <summary>
        /// 设备ID
        /// </summary>
        [Description("设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 维护类别
        /// </summary>
        [Description("维护类别")]
        [Column(DbType = DbType.AnsiString)]
        public string PM_TYPE { get; set; }

        /// <summary>
        /// 编制人
        /// </summary>
        [Description("编制人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 编制人ID
        /// </summary>
        [Description("编制人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 编制日期
        /// </summary>
        [Description("编制日期")]
        public DateTime? EDIT_DATE { get; set; }

        /// <summary>
        /// 来源
        /// </summary>
        [Description("来源")]
        [Column(DbType = DbType.AnsiString)]
        public string SOURCE { get; set; }

        /// <summary>
        /// 保养费用
        /// </summary>
        [Description("保养费用")]
        public decimal? PLAN_COST { get; set; }

        /// <summary>
        /// 单据类型
        /// </summary>
        [Description("单据类型")]
        [Column(DbType = DbType.AnsiString)]
        public string STATUS { get; set; }

        /// <summary>
        /// 计划开工时间
        /// </summary>
        [Description("计划开工时间")]
        public DateTime? PLAN_BEGIN_DATE { get; set; }

        /// <summary>
        /// 计划完工时间
        /// </summary>
        [Description("计划完工时间")]
        public DateTime? PLAN_END_DATE { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_A { get; set; }

        /// <summary>
        /// 点检状态
        /// </summary>
        [Description("点检状态")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_STATUS { get; set; }

        /// <summary>
        /// 是否生成过需求单
        /// </summary>
        [Description("是否生成过需求单")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_REQUEST { get; set; }

        /// <summary>
        /// 维保部门
        /// </summary>
        [Description("维保部门")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_DEPT { get; set; }

        /// <summary>
        /// 计划维保完成时间
        /// </summary>
        [Description("计划维保完成时间")]
        public DateTime? PLAN_FINISH_TIME { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string EXE_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 保养实施单号
        /// </summary>
        [Description("保养实施单号")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_CODE { get; set; }

        /// <summary>
        /// 实施提交时间
        /// </summary>
        [Description("实施提交时间")]
        public DateTime? AUDIT_TIME { get; set; }

        /// <summary>
        /// 燃油型号
        /// </summary>
        [Description("燃油型号")]
        [Column(DbType = DbType.AnsiString)]
        public string RY_TYPE { get; set; }

        /// <summary>
        /// 燃油领用
        /// </summary>
        [Description("燃油领用")]
        [Column(DbType = DbType.AnsiString)]
        public string RY_OUT { get; set; }

        /// <summary>
        /// 燃油消耗
        /// </summary>
        [Description("燃油消耗")]
        [Column(DbType = DbType.AnsiString)]
        public string RY_USE { get; set; }

        /// <summary>
        /// 燃油库存
        /// </summary>
        [Description("燃油库存")]
        [Column(DbType = DbType.AnsiString)]
        public string RY_STORE { get; set; }

        /// <summary>
        /// 滑油型号
        /// </summary>
        [Description("滑油型号")]
        [Column(DbType = DbType.AnsiString)]
        public string HY_TYPE { get; set; }

        /// <summary>
        /// 滑油领用
        /// </summary>
        [Description("滑油领用")]
        [Column(DbType = DbType.AnsiString)]
        public string HY_OUT { get; set; }

        /// <summary>
        /// 滑油消耗
        /// </summary>
        [Description("滑油消耗")]
        [Column(DbType = DbType.AnsiString)]
        public string HY_USE { get; set; }

        /// <summary>
        /// 滑油库存
        /// </summary>
        [Description("滑油库存")]
        [Column(DbType = DbType.AnsiString)]
        public string HY_STORE { get; set; }

        /// <summary>
        /// 齿轮油型号
        /// </summary>
        [Description("齿轮油型号")]
        [Column(DbType = DbType.AnsiString)]
        public string CLY_TYPE { get; set; }

        /// <summary>
        /// 齿轮油领用
        /// </summary>
        [Description("齿轮油领用")]
        [Column(DbType = DbType.AnsiString)]
        public string CLY_OUT { get; set; }

        /// <summary>
        /// 齿轮油消耗
        /// </summary>
        [Description("齿轮油消耗")]
        [Column(DbType = DbType.AnsiString)]
        public string CLY_USE { get; set; }

        /// <summary>
        /// 齿轮油库存
        /// </summary>
        [Description("齿轮油库存")]
        [Column(DbType = DbType.AnsiString)]
        public string CLY_STORE { get; set; }

        /// <summary>
        /// 液压油型号
        /// </summary>
        [Description("液压油型号")]
        [Column(DbType = DbType.AnsiString)]
        public string YYY_TYPE { get; set; }

        /// <summary>
        /// 液压油领用
        /// </summary>
        [Description("液压油领用")]
        [Column(DbType = DbType.AnsiString)]
        public string YYY_OUT { get; set; }

        /// <summary>
        /// 液压油消耗
        /// </summary>
        [Description("液压油消耗")]
        [Column(DbType = DbType.AnsiString)]
        public string YYY_USE { get; set; }

        /// <summary>
        /// 液压油库存
        /// </summary>
        [Description("液压油库存")]
        [Column(DbType = DbType.AnsiString)]
        public string YYY_STORE { get; set; }

        /// <summary>
        /// 左机本月运转时间
        /// </summary>
        [Description("左机本月运转时间")]
        [Column(DbType = DbType.AnsiString)]
        public string LEFT_MONTH { get; set; }

        /// <summary>
        /// 右机本月运转时间
        /// </summary>
        [Description("右机本月运转时间")]
        [Column(DbType = DbType.AnsiString)]
        public string RIGHT_MONTH { get; set; }

        /// <summary>
        /// 左机累计运转时间
        /// </summary>
        [Description("左机累计运转时间")]
        [Column(DbType = DbType.AnsiString)]
        public string LEFT_ALL { get; set; }

        /// <summary>
        /// 右机累计运转时间
        /// </summary>
        [Description("右机累计运转时间")]
        [Column(DbType = DbType.AnsiString)]
        public string RIGHT_ALL { get; set; }

        /// <summary>
        /// 本月电表数
        /// </summary>
        [Description("本月电表数")]
        [Column(DbType = DbType.AnsiString)]
        public string ELEC_MONTH { get; set; }

        /// <summary>
        /// 本月实耗数
        /// </summary>
        [Description("本月实耗数")]
        [Column(DbType = DbType.AnsiString)]
        public string ELEC_USE { get; set; }

        /// <summary>
        /// 年份
        /// </summary>
        [Description("年份")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_YEAR { get; set; }

        /// <summary>
        /// 月份
        /// </summary>
        [Description("月份")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_MONTH { get; set; }

        /// <summary>
        /// 上月燃油流量计读数
        /// </summary>
        [Description("上月燃油流量计读数")]
        [Column(DbType = DbType.AnsiString)]
        public string FUEL_LM { get; set; }

        /// <summary>
        /// 本月燃油流量计读数
        /// </summary>
        [Description("本月燃油流量计读数")]
        [Column(DbType = DbType.AnsiString)]
        public string FUEL_NM { get; set; }

        /// <summary>
        /// 上月未完成的主要维修保养工程及原因
        /// </summary>
        [Description("上月未完成的主要维修保养工程及原因")]
        [Column(DbType = DbType.AnsiString)]
        public string NOTFINISH_LM { get; set; }

        /// <summary>
        /// 上月临时修理项目及原因，影响多少运营时间？
        /// </summary>
        [Description("上月临时修理项目及原因，影响多少运营时间？")]
        [Column(DbType = DbType.AnsiString)]
        public string TEMP_REP_LM { get; set; }

        /// <summary>
        /// 上月未解决的设备问题，建议与要求
        /// </summary>
        [Description("上月未解决的设备问题，建议与要求")]
        [Column(DbType = DbType.AnsiString)]
        public string NOTREPDEV_LM { get; set; }

        /// <summary>
        /// 副机特殊发电时间
        /// </summary>
        [Description("副机特殊发电时间")]
        [Column(DbType = DbType.AnsiString)]
        public string FJ_SPECTIME { get; set; }

    }
}