//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类REP_FAULT
    /// </summary>
    [Table("REP_FAULT")]
    public class REP_FAULT
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_A { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_B { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_C { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING_D { get; set; }

        /// <summary>
        /// 故障单号
        /// </summary>
        [Description("故障单号")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_CODE { get; set; }

        /// <summary>
        /// 故障状态
        /// </summary>
        [Description("故障状态")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_STATUS { get; set; }

        /// <summary>
        /// 故障发生时间
        /// </summary>
        [Description("故障发生时间")]
        public DateTime? FAULT_DATE { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 设备状态
        /// </summary>
        [Description("设备状态")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_STATUS { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_CODE { get; set; }

        /// <summary>
        /// 资产编号
        /// </summary>
        [Description("资产编号")]
        [Column(DbType = DbType.AnsiString)]
        public string ASSET_CODE { get; set; }

        /// <summary>
        /// 设备型号
        /// </summary>
        [Description("设备型号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_TYPE { get; set; }

        /// <summary>
        /// 设备规格
        /// </summary>
        [Description("设备规格")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_SIZE { get; set; }

        /// <summary>
        /// 设备类别
        /// </summary>
        [Description("设备类别")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 安装地点
        /// </summary>
        [Description("安装地点")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTALL_SITE { get; set; }

        /// <summary>
        /// 地理区域
        /// </summary>
        [Description("地理区域")]
        [Column(DbType = DbType.AnsiString)]
        public string SITE_NAME { get; set; }

        /// <summary>
        /// 使用部门
        /// </summary>
        [Description("使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 使用二级单位
        /// </summary>
        [Description("使用二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 维保部门
        /// </summary>
        [Description("维保部门")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_NAME { get; set; }

        /// <summary>
        /// 维保部门ID
        /// </summary>
        [Description("维保部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WDEPT_ID { get; set; }

        /// <summary>
        /// 维保二级单位
        /// </summary>
        [Description("维保二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPT { get; set; }

        /// <summary>
        /// 维保二级单位ID
        /// </summary>
        [Description("维保二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string WSEC_DEPTID { get; set; }

        /// <summary>
        /// 上报人
        /// </summary>
        [Description("上报人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 上报人ID
        /// </summary>
        [Description("上报人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 维修人
        /// </summary>
        [Description("维修人")]
        [Column(DbType = DbType.AnsiString)]
        public string REPAIR_USER { get; set; }

        /// <summary>
        /// 维修人ID
        /// </summary>
        [Description("维修人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REPAIR_USERID { get; set; }

        /// <summary>
        /// 故障现象描述
        /// </summary>
        [Description("故障现象描述")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_DESCRIBE { get; set; }

        /// <summary>
        /// 异常处理
        /// </summary>
        [Description("异常处理")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_DISPOSE { get; set; }

        /// <summary>
        /// 接单人
        /// </summary>
        [Description("接单人")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDER_USER { get; set; }

        /// <summary>
        /// 接单人ID
        /// </summary>
        [Description("接单人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ORDER_USERID { get; set; }

        /// <summary>
        /// 接单时间
        /// </summary>
        [Description("接单时间")]
        public DateTime? ORDER_DATE { get; set; }

        /// <summary>
        /// 异常处理备注
        /// </summary>
        [Description("异常处理备注")]
        [Column(DbType = DbType.AnsiString)]
        public string EXCEPTION_MEMO { get; set; }

        /// <summary>
        /// 处理方式
        /// </summary>
        [Description("处理方式")]
        [Column(DbType = DbType.AnsiString)]
        public string DISPOSE_TYPE { get; set; }

        /// <summary>
        /// 故障分类
        /// </summary>
        [Description("故障分类")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_TYPE_NAME { get; set; }

        /// <summary>
        /// 故障分类ID
        /// </summary>
        [Description("故障分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_TYPE_ID { get; set; }

        /// <summary>
        /// 完工时间
        /// </summary>
        [Description("完工时间")]
        public DateTime? COMPLETE_DATE { get; set; }

        /// <summary>
        /// 维修工时(H)
        /// </summary>
        [Description("维修工时(H)")]
        public decimal? REPAIR_HOURS { get; set; }

        /// <summary>
        /// 故障原因
        /// </summary>
        [Description("故障原因")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_REASON { get; set; }

        /// <summary>
        /// 解决方法
        /// </summary>
        [Description("解决方法")]
        [Column(DbType = DbType.AnsiString)]
        public string MEASURES { get; set; }

        /// <summary>
        /// 故障处理备注
        /// </summary>
        [Description("故障处理备注")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_MEMO { get; set; }

        /// <summary>
        /// 验收人
        /// </summary>
        [Description("验收人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_USER { get; set; }

        /// <summary>
        /// 验收人ID
        /// </summary>
        [Description("验收人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_USERID { get; set; }

        /// <summary>
        /// 验收时间
        /// </summary>
        [Description("验收时间")]
        public DateTime? CHECK_DATE { get; set; }

        /// <summary>
        /// 验收结果
        /// </summary>
        [Description("验收结果")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_RESULT { get; set; }

        /// <summary>
        /// 验收说明
        /// </summary>
        [Description("验收说明")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string FAULT_ID { get; set; }

        /// <summary>
        /// 设备卡片ID
        /// </summary>
        [Description("设备卡片ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 异常来源
        /// </summary>
        [Description("异常来源")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_SRC { get; set; }

        /// <summary>
        /// 来源单号
        /// </summary>
        [Description("来源单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_CODE { get; set; }

        /// <summary>
        /// 故障库编码
        /// </summary>
        [Description("故障库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string FRDB_CODE { get; set; }

        /// <summary>
        /// 故障库ID
        /// </summary>
        [Description("故障库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string FRDB_ID { get; set; }

        /// <summary>
        /// 设备类别ID
        /// </summary>
        [Description("设备类别ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 通知时间
        /// </summary>
        [Description("通知时间")]
        public DateTime? NOTICE_TIME { get; set; }

        /// <summary>
        /// 是否生成过需求单
        /// </summary>
        [Description("是否生成过需求单")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_REQUEST { get; set; }

        /// <summary>
        /// 船舶ID
        /// </summary>
        [Description("船舶ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_ID { get; set; }

        /// <summary>
        /// 船舶编码
        /// </summary>
        [Description("船舶编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_CODE { get; set; }

        /// <summary>
        /// 船舶名称
        /// </summary>
        [Description("船舶名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SHIP_NAME { get; set; }

    }
}