//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类REP_FRDB
    /// </summary>
    [Table("REP_FRDB")]
    public class REP_FRDB
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 故障库编码
        /// </summary>
        [Description("故障库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string FRDB_CODE { get; set; }

        /// <summary>
        /// 设备编码
        /// </summary>
        [Description("设备编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_CODE { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 故障程度
        /// </summary>
        [Description("故障程度")]
        [Column(DbType = DbType.AnsiString)]
        public string FRDB_LEVEL { get; set; }

        /// <summary>
        /// 设备ID
        /// </summary>
        [Description("设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string FRDB_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 添加日期
        /// </summary>
        [Description("添加日期")]
        public DateTime? EDIT_DATE { get; set; }

        /// <summary>
        /// 添加人
        /// </summary>
        [Description("添加人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 故障现象
        /// </summary>
        [Description("故障现象")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_DESCRIBE { get; set; }

        /// <summary>
        /// 故障原因
        /// </summary>
        [Description("故障原因")]
        [Column(DbType = DbType.AnsiString)]
        public string FAULT_REASON { get; set; }

        /// <summary>
        /// 解决方法
        /// </summary>
        [Description("解决方法")]
        [Column(DbType = DbType.AnsiString)]
        public string MEASURES { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 来源功能
        /// </summary>
        [Description("来源功能")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_FUNCTION { get; set; }

        /// <summary>
        /// 来源单号
        /// </summary>
        [Description("来源单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_CODE { get; set; }

        /// <summary>
        /// 维修设备名称
        /// </summary>
        [Description("维修设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_DEVICE { get; set; }

    }
}