//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类rep_plan_exe_item
    /// </summary>
    [Table("rep_plan_exe_item")]
    public class REP_PLAN_EXE_ITEM
    {

        /// <summary>
        /// 维修处理方式
        /// </summary>
        [Description("维修处理方式")]
        [Column(DbType = DbType.AnsiString)]
        public string DEAL_TYPE { get; set; }

        /// <summary>
        /// 维修部位
        /// </summary>
        [Description("维修部位")]
        [Column(DbType = DbType.AnsiString)]
        public string BOM_NAME { get; set; }

        /// <summary>
        /// 维修内容
        /// </summary>
        [Description("维修内容")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_CONTENT { get; set; }

        /// <summary>
        /// 维修方法
        /// </summary>
        [Description("维修方法")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_METHOD { get; set; }

        /// <summary>
        /// 使用工具
        /// </summary>
        [Description("使用工具")]
        [Column(DbType = DbType.AnsiString)]
        public string USE_TOOL { get; set; }

        /// <summary>
        /// 人员数量
        /// </summary>
        [Description("人员数量")]
        public decimal? LABOR_NUM { get; set; }

        /// <summary>
        /// 花费时间(分钟)
        /// </summary>
        [Description("花费时间(分钟)")]
        public decimal? TAKE_TIME { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 维修部位ID
        /// </summary>
        [Description("维修部位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string BOM_ID { get; set; }

        /// <summary>
        /// 外键
        /// </summary>
        [Description("外键")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_ID { get; set; }

        /// <summary>
        /// 维修计划项目ID
        /// </summary>
        [Description("维修计划项目ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_ITEM_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string EXE_ITEM_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 维修实施单ID
        /// </summary>
        [Description("维修实施单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_ID { get; set; }

        /// <summary>
        /// 检修负责人
        /// </summary>
        [Description("检修负责人")]
        [Column(DbType = DbType.AnsiString)]
        public string REP_LEADER { get; set; }

        /// <summary>
        /// 实际开工时间
        /// </summary>
        [Description("实际开工时间")]
        public DateTime? BEGIN_TIME { get; set; }

        /// <summary>
        /// 实际完工时间
        /// </summary>
        [Description("实际完工时间")]
        public DateTime? END_TIME { get; set; }

        /// <summary>
        /// 是否完成
        /// </summary>
        [Description("是否完成")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_COMPLETE { get; set; }

        /// <summary>
        /// 序号
        /// </summary>
        [Description("序号")]
        public decimal? REP_INDEX { get; set; }

        /// <summary>
        /// 是否月度询价
        /// </summary>
        [Description("是否月度询价")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_ASKBID { get; set; }

        /// <summary>
        /// 维修项目分类
        /// </summary>
        [Description("维修项目分类")]
        [Column(DbType = DbType.AnsiString)]
        public string ITEM_TYPE { get; set; }

    }
}