//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类REP_PLAN_SP
    /// </summary>
    [Table("REP_PLAN_SP")]
    public class REP_PLAN_SP
    {

        /// <summary>
        /// 是否已生成领料单
        /// </summary>
        [Description("是否已生成领料单")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_ORDER { get; set; }

        /// <summary>
        /// 来源
        /// </summary>
        [Description("来源")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SOURCE { get; set; }

        /// <summary>
        /// 备件品种编码
        /// </summary>
        [Description("备件品种编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 备件品种名称
        /// </summary>
        [Description("备件品种名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 型号规格
        /// </summary>
        [Description("型号规格")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 品牌、厂家
        /// </summary>
        [Description("品牌、厂家")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 其他编号
        /// </summary>
        [Description("其他编号")]
        [Column(DbType = DbType.AnsiString)]
        public string OTHER_CODE { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 制造厂
        /// </summary>
        [Description("制造厂")]
        [Column(DbType = DbType.AnsiString)]
        public string FACTORY { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 库存数量
        /// </summary>
        [Description("库存数量")]
        public decimal? STORE_NUM { get; set; }

        /// <summary>
        /// 申请数量
        /// </summary>
        [Description("申请数量")]
        public decimal? APPLY_NUM { get; set; }

        /// <summary>
        /// 实际消耗数量
        /// </summary>
        [Description("实际消耗数量")]
        public decimal? FACT_NUM { get; set; }

        /// <summary>
        /// 含税单价(元)
        /// </summary>
        [Description("含税单价(元)")]
        public decimal? TAX_PRICE { get; set; }

        /// <summary>
        /// 含税金额(元)
        /// </summary>
        [Description("含税金额(元)")]
        public decimal? TAX_MONEY { get; set; }

        /// <summary>
        /// 不含税单价(元)
        /// </summary>
        [Description("不含税单价(元)")]
        public decimal? NOTAX_PRICE { get; set; }

        /// <summary>
        /// 不含税金额(元)
        /// </summary>
        [Description("不含税金额(元)")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 出库单号
        /// </summary>
        [Description("出库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_CODE { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string PLAN_SP_ID { get; set; }

        /// <summary>
        /// 外键
        /// </summary>
        [Description("外键")]
        [Column(DbType = DbType.AnsiString)]
        public string PLAN_ID { get; set; }

        /// <summary>
        /// 库存汇总ID
        /// </summary>
        [Description("库存汇总ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_HOUSE_ID { get; set; }

        /// <summary>
        /// 备件品种ID
        /// </summary>
        [Description("备件品种ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        [Description("仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 是否备件
        /// </summary>
        [Description("是否备件")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_BJ { get; set; }

        /// <summary>
        /// 库位ID
        /// </summary>
        [Description("库位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_ID { get; set; }

        /// <summary>
        /// 库位名称
        /// </summary>
        [Description("库位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_NAME { get; set; }

        /// <summary>
        /// 委外维修ID
        /// </summary>
        [Description("委外维修ID")]
        [Column(DbType = DbType.AnsiString)]
        public string OUT_ID { get; set; }

        /// <summary>
        /// 维修实施单ID
        /// </summary>
        [Description("维修实施单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_ID { get; set; }

        /// <summary>
        /// 维修实施项目ID
        /// </summary>
        [Description("维修实施项目ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EXE_ITEM_ID { get; set; }

        /// <summary>
        /// 厂修确认单ID
        /// </summary>
        [Description("厂修确认单ID")]
        [Column(DbType = DbType.AnsiString)]
        public string FACTORY_ID { get; set; }

        /// <summary>
        /// 实际开始时间
        /// </summary>
        [Description("实际开始时间")]
        public DateTime? BEGIN_TIME { get; set; }

        /// <summary>
        /// 实际结束时间
        /// </summary>
        [Description("实际结束时间")]
        public DateTime? END_TIME { get; set; }

    }
}