//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类RUN_STOP
    /// </summary>
    [Table("RUN_STOP")]
    public class RUN_STOP
    {

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 停机编码
        /// </summary>
        [Description("停机编码")]
        [Column(DbType = DbType.AnsiString)]
        public string STOP_CODE { get; set; }

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NO { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 设备型号
        /// </summary>
        [Description("设备型号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_TYPE { get; set; }

        /// <summary>
        /// 制造厂
        /// </summary>
        [Description("制造厂")]
        [Column(DbType = DbType.AnsiString)]
        public string FACTORY_NAME { get; set; }

        /// <summary>
        /// 使用部门ID
        /// </summary>
        [Description("使用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 设备分类
        /// </summary>
        [Description("设备分类")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 分类编号
        /// </summary>
        [Description("分类编号")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 编制部门
        /// </summary>
        [Description("编制部门")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 停机记录来源
        /// </summary>
        [Description("停机记录来源")]
        [Column(DbType = DbType.AnsiString)]
        public string STOP_SOURCE { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }

        /// <summary>
        /// 停机开始时间
        /// </summary>
        [Description("停机开始时间")]
        public DateTime? RUN_START { get; set; }

        /// <summary>
        /// 停机结束时间
        /// </summary>
        [Description("停机结束时间")]
        public DateTime? RUN_END { get; set; }

        /// <summary>
        /// 编制人
        /// </summary>
        [Description("编制人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 编制日期
        /// </summary>
        [Description("编制日期")]
        public DateTime? EDIT_DATE { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 编制人ID
        /// </summary>
        [Description("编制人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 使用部门
        /// </summary>
        [Description("使用部门")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_DEPT { get; set; }

        /// <summary>
        /// 使用部门ID
        /// </summary>
        [Description("使用部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_DEPTID { get; set; }

        /// <summary>
        /// 其中故障停机台时
        /// </summary>
        [Description("其中故障停机台时")]
        public decimal? ALL_STOP_HOURS { get; set; }

        /// <summary>
        /// 计划内停机台时
        /// </summary>
        [Description("计划内停机台时")]
        public decimal? PLAN_STOP_HOURS { get; set; }

        /// <summary>
        /// 总停机台时
        /// </summary>
        [Description("总停机台时")]
        public decimal? STOP_HOURS { get; set; }

        /// <summary>
        /// 停机过程描述
        /// </summary>
        [Description("停机过程描述")]
        [Column(DbType = DbType.AnsiString)]
        public string STOP_DESC { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 分类ID
        /// </summary>
        [Description("分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 设备ID
        /// </summary>
        [Description("设备ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 故障报修ID
        /// </summary>
        [Description("故障报修ID")]
        [Column(DbType = DbType.AnsiString)]
        public string REPORT_ID { get; set; }

        /// <summary>
        /// 故障台账ID
        /// </summary>
        [Description("故障台账ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROBLEM_ID { get; set; }

        /// <summary>
        /// 诊断时间
        /// </summary>
        [Description("诊断时间")]
        public DateTime? RESPONSE_DATE { get; set; }

        /// <summary>
        /// 来源单号
        /// </summary>
        [Description("来源单号")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_CODE { get; set; }

        /// <summary>
        /// 班次
        /// </summary>
        [Description("班次")]
        [Column(DbType = DbType.AnsiString)]
        public string REPAIR_BC { get; set; }

        /// <summary>
        /// 抢修团队
        /// </summary>
        [Description("抢修团队")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_TEAM { get; set; }

        /// <summary>
        /// 故障部位
        /// </summary>
        [Description("故障部位")]
        [Column(DbType = DbType.AnsiString)]
        public string MAL_PARTS { get; set; }

        /// <summary>
        /// 分析部门
        /// </summary>
        [Description("分析部门")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_DEPT { get; set; }

        /// <summary>
        /// 分析人
        /// </summary>
        [Description("分析人")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_USER { get; set; }

        /// <summary>
        /// 分析日期
        /// </summary>
        [Description("分析日期")]
        public DateTime? CHECK_DATE { get; set; }

        /// <summary>
        /// 主要原因
        /// </summary>
        [Description("主要原因")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_DESC { get; set; }

        /// <summary>
        /// 故障分类
        /// </summary>
        [Description("故障分类")]
        [Column(DbType = DbType.AnsiString)]
        public string MAL_TYPE_NAME { get; set; }

        /// <summary>
        /// 故障分类ID
        /// </summary>
        [Description("故障分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MAL_TYPE_ID { get; set; }

        /// <summary>
        /// 分析部门ID
        /// </summary>
        [Description("分析部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_DEPTID { get; set; }

        /// <summary>
        /// 分析人ID
        /// </summary>
        [Description("分析人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CHECK_USERID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string RUN_STOP_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string ADD_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? ADD_DATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFY_DATE { get; set; }

    }
}