//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类RUN_MAL_TYPE
    /// </summary>
    [Table("RUN_MAL_TYPE")]
    public class RUN_MAL_TYPE
    {

        /// <summary>
        /// 分类编号
        /// </summary>
        [Description("分类编号")]
        [Column(DbType = DbType.AnsiString)]
        public string MAL_TYPE_CODE { get; set; }

        /// <summary>
        /// 故障分类
        /// </summary>
        [Description("故障分类")]
        [Column(DbType = DbType.AnsiString)]
        public string MAL_TYPE_NAME { get; set; }

        /// <summary>
        /// 故障分类级别
        /// </summary>
        [Description("故障分类级别")]
        [Column(DbType = DbType.AnsiString)]
        public string MAL_TYPE_LEVEL { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 是否故障设备
        /// </summary>
        [Description("是否故障设备")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_DEVICE { get; set; }

        /// <summary>
        /// 编制人
        /// </summary>
        [Description("编制人")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USER { get; set; }

        /// <summary>
        /// 编制日期
        /// </summary>
        [Description("编制日期")]
        public DateTime? EDIT_DATE { get; set; }

        /// <summary>
        /// 编制人ID
        /// </summary>
        [Description("编制人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string EDIT_USERID { get; set; }

        /// <summary>
        /// 区分
        /// </summary>
        [Description("区分")]
        [Column(DbType = DbType.AnsiString)]
        public string DISTINGUISH { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string MAL_TYPE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

    }
}