//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类RUN_TRANS
    /// </summary>
    [Table("RUN_TRANS")]
    public class RUN_TRANS
    {

        /// <summary>
        /// 设备编号
        /// </summary>
        [Description("设备编号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NO { get; set; }

        /// <summary>
        /// 设备名称
        /// </summary>
        [Description("设备名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_NAME { get; set; }

        /// <summary>
        /// 设备编码
        /// </summary>
        [Description("设备编码")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_CODE { get; set; }

        /// <summary>
        /// 工作单元
        /// </summary>
        [Description("工作单元")]
        [Column(DbType = DbType.AnsiString)]
        public string WORD_UNIT { get; set; }

        /// <summary>
        /// 机构
        /// </summary>
        [Description("机构")]
        [Column(DbType = DbType.AnsiString)]
        public string INSTITUTION { get; set; }

        /// <summary>
        /// 原状态
        /// </summary>
        [Description("原状态")]
        [Column(DbType = DbType.AnsiString)]
        public string RUN_STATUS { get; set; }

        /// <summary>
        /// 现状态
        /// </summary>
        [Description("现状态")]
        [Column(DbType = DbType.AnsiString)]
        public string NEW_RUN_STATUS { get; set; }

        /// <summary>
        /// 转换时间
        /// </summary>
        [Description("转换时间")]
        public DateTime? TRANS_DATE { get; set; }

        /// <summary>
        /// 转换原因
        /// </summary>
        [Description("转换原因")]
        [Column(DbType = DbType.AnsiString)]
        public string TRANS_MEMO { get; set; }

        /// <summary>
        /// 设备类别ID
        /// </summary>
        [Description("设备类别ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string TRANS_ID { get; set; }

        /// <summary>
        /// 设备构造id
        /// </summary>
        [Description("设备构造id")]
        [Column(DbType = DbType.AnsiString)]
        public string COMPOSE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 记录状态
        /// </summary>
        [Description("记录状态")]
        [Column(DbType = DbType.AnsiString)]
        public string AUDITING { get; set; }

        /// <summary>
        /// 设备id
        /// </summary>
        [Description("设备id")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_ID { get; set; }

        /// <summary>
        /// 设备型号
        /// </summary>
        [Description("设备型号")]
        [Column(DbType = DbType.AnsiString)]
        public string DEVICE_TYPE { get; set; }

        /// <summary>
        /// 部门ID
        /// </summary>
        [Description("部门ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 部门名称
        /// </summary>
        [Description("部门名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 二级单位ID
        /// </summary>
        [Description("二级单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPTID { get; set; }

        /// <summary>
        /// 二级单位
        /// </summary>
        [Description("二级单位")]
        [Column(DbType = DbType.AnsiString)]
        public string SEC_DEPT { get; set; }


    }
}