//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类RUN_STOP_TYPE
    /// </summary>
    [Table("RUN_STOP_TYPE")]
    public class RUN_STOP_TYPE
    {

        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Column(DbType = DbType.AnsiString)]
        public string MEMO { get; set; }

        /// <summary>
        /// 是否故障停机
        /// </summary>
        [Description("是否故障停机")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_STOP { get; set; }

        /// <summary>
        /// 是否计划内停机
        /// </summary>
        [Description("是否计划内停机")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_PLAN { get; set; }

        /// <summary>
        /// 停机分类名称
        /// </summary>
        [Description("停机分类名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STOP_NAME { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string STOP_TYPE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// TENANT_ID
        /// </summary>
        [Description("TENANT_ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TENANT_ID { get; set; }

    }
}