//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model
{
    /// <summary>
    /// 实体类SP_STORE
    /// </summary>
    [Table("SP_STORE")]
    public class SP_STORE
    {

        /// <summary>
        /// 批次号
        /// </summary>
        [Description("批次号")]
        [Column(DbType = DbType.AnsiString)]
        public string STORE_CODE { get; set; }

        /// <summary>
        /// 来源类型
        /// </summary>
        [Description("来源类型")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_TYPE { get; set; }

        /// <summary>
        /// 物料ID
        /// </summary>
        [Description("物料ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_ID { get; set; }

        /// <summary>
        /// 库存数量
        /// </summary>
        [Description("库存数量")]
        public decimal? NUM { get; set; }

        /// <summary>
        /// 库存单价
        /// </summary>
        [Description("库存单价")]
        public decimal? PRICE { get; set; }

        /// <summary>
        /// 库存金额(元)
        /// </summary>
        [Description("库存金额(元)")]
        public decimal? MONEY { get; set; }

        /// <summary>
        /// 仓库ID
        /// </summary>
        [Description("仓库ID")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_ID { get; set; }

        /// <summary>
        /// 仓库名称
        /// </summary>
        [Description("仓库名称")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_NAME { get; set; }

        /// <summary>
        /// 库位ID
        /// </summary>
        [Description("库位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_ID { get; set; }

        /// <summary>
        /// 库位名称
        /// </summary>
        [Description("库位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_NAME { get; set; }

        /// <summary>
        /// 仓管员ID
        /// </summary>
        [Description("仓管员ID")]
        [Column(DbType = DbType.AnsiString)]
        public string M_USERID { get; set; }

        /// <summary>
        /// 仓管员
        /// </summary>
        [Description("仓管员")]
        [Column(DbType = DbType.AnsiString)]
        public string M_USER { get; set; }

        /// <summary>
        /// 物料编码
        /// </summary>
        [Description("物料编码")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_CODE { get; set; }

        /// <summary>
        /// 物料名称
        /// </summary>
        [Description("物料名称")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_NAME { get; set; }

        /// <summary>
        /// 规格型号
        /// </summary>
        [Description("规格型号")]
        [Column(DbType = DbType.AnsiString)]
        public string SP_SIZE { get; set; }

        /// <summary>
        /// 图号
        /// </summary>
        [Description("图号")]
        [Column(DbType = DbType.AnsiString)]
        public string DRAWING_NO { get; set; }

        /// <summary>
        /// 分类ID
        /// </summary>
        [Description("分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_ID { get; set; }

        /// <summary>
        /// 分类名称
        /// </summary>
        [Description("分类名称")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// 分类编码
        /// </summary>
        [Description("分类编码")]
        [Column(DbType = DbType.AnsiString)]
        public string TYPE_CODE { get; set; }

        /// <summary>
        /// 重量(KG)
        /// </summary>
        [Description("重量(KG)")]
        public decimal? WEIGHT { get; set; }

        /// <summary>
        /// 计量单位
        /// </summary>
        [Description("计量单位")]
        [Column(DbType = DbType.AnsiString)]
        public string UNIT { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PRODUCE { get; set; }

        /// <summary>
        /// 在途数
        /// </summary>
        [Description("在途数")]
        public decimal? ONROAD_NUM { get; set; }

        /// <summary>
        /// 可重用度
        /// </summary>
        [Description("可重用度")]
        [Column(DbType = DbType.AnsiString)]
        public string REUSABILITY { get; set; }

        /// <summary>
        /// 累计入库量
        /// </summary>
        [Description("累计入库量")]
        public decimal? IN_NUM { get; set; }

        /// <summary>
        /// 累计出库量
        /// </summary>
        [Description("累计出库量")]
        public decimal? OUT_NUM { get; set; }

        /// <summary>
        /// 借用数量
        /// </summary>
        [Description("借用数量")]
        public decimal? BORROW_NUM { get; set; }

        /// <summary>
        /// 申请单号
        /// </summary>
        [Description("申请单号")]
        [Column(DbType = DbType.AnsiString)]
        public string APPLY_NO { get; set; }

        /// <summary>
        /// 供应商ID
        /// </summary>
        [Description("供应商ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_ID { get; set; }

        /// <summary>
        /// 供应商
        /// </summary>
        [Description("供应商")]
        [Column(DbType = DbType.AnsiString)]
        public string PROVIDER_NAME { get; set; }

        /// <summary>
        /// 入库日期
        /// </summary>
        [Description("入库日期")]
        public DateTime? IN_DATE { get; set; }

        /// <summary>
        /// 入库单号
        /// </summary>
        [Description("入库单号")]
        [Column(DbType = DbType.AnsiString)]
        public string IN_CODE { get; set; }

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string STORE_ID { get; set; }

        /// <summary>
        /// 添加人ID
        /// </summary>
        [Description("添加人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string CREATE_USERID { get; set; }

        /// <summary>
        /// 添加时间
        /// </summary>
        [Description("添加时间")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        [Column(DbType = DbType.AnsiString)]
        public string MODIFY_USERID { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Description("修改时间")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 库位编号
        /// </summary>
        [Description("库位编号")]
        [Column(DbType = DbType.AnsiString)]
        public string STOCK_CODE { get; set; }

        /// <summary>
        /// 单位ID
        /// </summary>
        [Description("单位ID")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_ID { get; set; }

        /// <summary>
        /// 单位名称
        /// </summary>
        [Description("单位名称")]
        [Column(DbType = DbType.AnsiString)]
        public string DEPT_NAME { get; set; }

        /// <summary>
        /// 仓库编码
        /// </summary>
        [Description("仓库编码")]
        [Column(DbType = DbType.AnsiString)]
        public string HOUSE_CODE { get; set; }

        /// <summary>
        /// 送货单号
        /// </summary>
        [Description("送货单号")]
        [Column(DbType = DbType.AnsiString)]
        public string DELIVERY_CODE { get; set; }

        /// <summary>
        /// 采购分类ID
        /// </summary>
        [Description("采购分类ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_ID { get; set; }

        /// <summary>
        /// 采购分类
        /// </summary>
        [Description("采购分类")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_NAME { get; set; }

        /// <summary>
        /// 库存上限
        /// </summary>
        [Description("库存上限")]
        public double? STORE_TOP { get; set; }

        /// <summary>
        /// 库存下限
        /// </summary>
        [Description("库存下限")]
        public double? STORE_LOWER { get; set; }

        /// <summary>
        /// 来源ID
        /// </summary>
        [Description("来源ID")]
        [Column(DbType = DbType.AnsiString)]
        public string SRC_ID { get; set; }

        /// <summary>
        /// 是否已冲红
        /// </summary>
        [Description("是否已冲红")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_BACK { get; set; }

        /// <summary>
        /// 是否供应商库存
        /// </summary>
        [Description("是否供应商库存")]
        [Column(DbType = DbType.AnsiString)]
        public string IS_FIC { get; set; }

        /// <summary>
        /// 含税金额(元)
        /// </summary>
        [Description("含税金额(元)")]
        public decimal? TAX_MONEY { get; set; }

        /// <summary>
        /// 含税单价(元)
        /// </summary>
        [Description("含税单价(元)")]
        public decimal? TAX_PRICE { get; set; }

        /// <summary>
        /// 入库明细ID
        /// </summary>
        [Description("入库明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string INDET_ID { get; set; }

        /// <summary>
        /// 集团编码
        /// </summary>
        [Description("集团编码")]
        [Column(DbType = DbType.AnsiString)]
        public string COMP_CODE { get; set; }

        /// <summary>
        /// 库龄(月)
        /// </summary>
        [Description("库龄(月)")]
        public decimal? STORE_MONTH { get; set; }

        /// <summary>
        /// 采购编码
        /// </summary>
        [Description("采购编码")]
        [Column(DbType = DbType.AnsiString)]
        public string PURTYPE_CODE { get; set; }

        /// <summary>
        /// 协议明细ID
        /// </summary>
        [Description("协议明细ID")]
        [Column(DbType = DbType.AnsiString)]
        public string PRO_DET_ID { get; set; }

        /// <summary>
        /// 发票号
        /// </summary>
        [Description("发票号")]
        [Column(DbType = DbType.AnsiString)]
        public string INVOICE_CODE { get; set; }

        /// <summary>
        /// 不含税金额(元)
        /// </summary>
        [Description("不含税金额(元)")]
        public decimal? UNTAX_MONEY { get; set; }

        /// <summary>
        /// 不含税金额(元)
        /// </summary>
        [Description("不含税金额(元)")]
        public decimal? UNTAX_MONEY2 { get; set; }

        /// <summary>
        /// 税率
        /// </summary>
        [Description("税率")]
        public decimal? TAX_RATE { get; set; }

        /// <summary>
        /// 不含税单价(元)
        /// </summary>
        [Description("不含税单价(元)")]
        public decimal? NOTAX_PRICE { get; set; }

        /// <summary>
        /// 不含税金额(元)
        /// </summary>
        [Description("不含税金额(元)")]
        public decimal? NOTAX_MONEY { get; set; }

        /// <summary>
        /// 库存数量
        /// </summary>
        [Description("库存数量")]
        public decimal? NUM2 { get; set; }

        /// <summary>
        /// 库存单价
        /// </summary>
        [Description("库存单价")]
        public decimal? PRICE2 { get; set; }

        /// <summary>
        /// 是否是旧库存
        /// </summary>
        [Description("是否是旧库存")]
        [Column(DbType = DbType.AnsiString)]
        public string ISOLD { get; set; }

    }
}