//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.WorkFlow
{
    /// <summary>
    /// 流程定义
    /// </summary>
    [Table("WF_FLOW")]
    public class WF_FLOW
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString, Size = 11)]
        public string ID { get; set; }

        /// <summary>
        /// 流程名称
        /// </summary>
        [Description("流程名称")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string FLOW_NAME { get; set; }

        /// <summary>
        /// 流程标题
        /// </summary>
        [Description("流程标题")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string FLOW_TITLE { get; set; }

        /// <summary>
        /// 流程序号
        /// </summary>
        [Description("流程序号")]
        public string FLOW_ORDER { get; set; }

        /// <summary>
        /// 流程内容
        /// </summary>
        [ModelEncrypt]
        [Description("流程内容")]
        [Column(DbType = DbType.AnsiString, Size = 4000)]
        public string FLOW_CONTENT { get; set; }

        /// <summary>
        /// 流程表单
        /// </summary>
        [ModelEncrypt]
        [Description("流程表单")]
        [Column(DbType = DbType.AnsiString, Size = 4000)]
        public string FLOW_FORM { get; set; }

        /// <summary>
        /// 流程表单url
        /// </summary>
        [Description("流程表单URL")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string FLOW_FORM_URL { get; set; }

        /// <summary>
        /// 流程版本
        /// </summary>
        [Description("流程版本")]
        public int? FLOW_VERSION { get; set; }

        /// <summary>
        /// 状态(1:可用 0:已下线)
        /// </summary>
        [Description("状态(1:正常 0:已下线)")]
        [Column(DbType = DbType.AnsiString, Size = 1)]
        public string FLAG { get; set; }

        /// <summary>
        /// 所属组织
        /// </summary>
        [Description("所属组织")]
        [Column(DbType = DbType.AnsiString, Size = 20)]
        public string CORPID { get; set; }

        /// <summary>
        /// 创建人ID
        /// </summary>
        [Description("创建人ID")]
        public int? CREATEUSERID { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 创建日期
        /// </summary>
        [Description("创建日期")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 修改人ID
        /// </summary>
        [Description("修改人ID")]
        public long? MODIFYUSERID { get; set; }

        /// <summary>
        /// 最后修改人
        /// </summary>
        [Description("最后修改人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string MODIFYUSER { get; set; }

        /// <summary>
        /// 修改日期
        /// </summary>
        [Description("修改日期")]
        public DateTime? MODIFYDATE { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string APPNAME { get; set; }
    }
}