//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;

namespace Gksyb.Model.WorkFlow
{
    /// <summary>
    /// 流程节点
    /// </summary>
    [Table("WF_HISTORY_NODE")]
    public class WF_HISTORY_NODE : WF_NODE
    {
    }
}