//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.WorkFlow
{
    /// <summary>
    /// 流程节点
    /// </summary>
    [Table("WF_NODE")]
    public class WF_NODE
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString)]
        public string ID { get; set; }

        /// <summary>
        /// 流程主键
        /// </summary>
        [Description("流程主键")]
        [Column(DbType = DbType.AnsiString)]
        public string FLOW_ID { get; set; }

        /// <summary>
        /// 任务主键
        /// </summary>
        [Description("任务主键")]
        [Column(DbType = DbType.AnsiString)]
        public string TASK_ID { get; set; }

        /// <summary>
        /// 节点编号
        /// </summary>
        [Description("节点编号")]
        [Column(DbType = DbType.AnsiString)]
        public string NODE_ID { get; set; }

        /// <summary>
        /// 节点名称
        /// </summary>
        [Description("节点名称")]
        [Column(DbType = DbType.AnsiString)]
        public string NODE_NAME { get; set; }

        /// <summary>
        /// 节点标题
        /// </summary>
        [Description("节点标题")]
        [Column(DbType = DbType.AnsiString)]
        public string NODE_TITLE { get; set; }

        /// <summary>
        /// 节点类型
        /// </summary>
        [Description("节点类型")]
        public string NODE_TYPE { get; set; }

        /// <summary>
        /// 节点状态 参考<see cref="WF_NODEExtensions"/> 
        /// </summary>
        [Description("节点状态")]
        public int? NODE_STATUS { get; set; }

        /// <summary>
        /// 节点处理人ID
        /// </summary>
        [Description("节点处理人ID")]
        public long? NODE_USERID { get; set; }

        /// <summary>
        /// 节点处理人
        /// </summary>
        [Description("节点处理人账号")]
        [Column(DbType = DbType.AnsiString)]
        public string NODE_USERNAME { get; set; }

        /// <summary>
        /// 节点处理人
        /// </summary>
        [Description("节点处理人")]
        [Column(DbType = DbType.AnsiString)]
        public string NODE_USER { get; set; }

        /// <summary>
        /// 处理意见
        /// </summary>
        [Description("处理意见")]
        public string NODE_REASON { get; set; }

        /// <summary>
        /// 下一节点编号
        /// </summary>
        [Description("下一节点编号")]
        [Column(DbType = DbType.AnsiString)]
        public string TO_NODE_ID { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 创建日期
        /// </summary>
        [Description("创建日期")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 查看日期
        /// </summary>
        [Description("查看日期")]
        public DateTime? VIEWDATE { get; set; }

        /// <summary>
        /// 完成日期
        /// </summary>
        [Description("完成时间")]
        public DateTime? FINISHDATE { get; set; }

    }
}