//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.WorkFlow
{
    /// <summary>
    /// 流程任务
    /// </summary>
    [Table("WF_TASK")]
    public class WF_TASK
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Description("主键")]
        [Column(IsPrimaryKey = true, DbType = DbType.AnsiString, Size = 11)]
        public string ID { get; set; }

        /// <summary>
        /// 流程主键
        /// </summary>
        [Description("流程主键")]
        [Column(DbType = DbType.AnsiString, Size = 11)]
        public string FLOW_ID { get; set; }

        /// <summary>
        /// 流程名称
        /// </summary>
        [Description("流程名称")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string FLOW_NAME { get; set; }

        /// <summary>
        /// 流程名称
        /// </summary>
        [Description("流程名称")]
        [Column(DbType = DbType.AnsiString, Size = 200)]
        public string FLOW_TITLE { get; set; }

        /// <summary>
        /// 流程备注
        /// </summary>
        [Description("流程备注")]
        [Column(DbType = DbType.AnsiString, Size = 500)]
        public string FLOW_REMARK { get; set; }

        /// <summary>
        /// 流程表单数据
        /// </summary>
        [Description("流程表单数据")]
        [Column(DbType = DbType.AnsiString, Size = 4000)]
        public string FLOW_FORM_DATA { get; set; }

        /// <summary>
        /// 流程状态 参考<see cref="WF_TASKExtensions"/> {0:回收,1:激活,2:完成}
        /// </summary>
        [Description("流程状态")]
        public int? FLOW_STATUS { get; set; }

        /// <summary>
        /// 所属组织
        /// </summary>
        [Description("所属组织")]
        [Column(DbType = DbType.AnsiString, Size = 20)]
        public string CORPID { get; set; }

        /// <summary>
        /// 创建人ID
        /// </summary>
        [Description("创建人ID")]
        public long? CREATEUSERID { get; set; }

        /// <summary>
        /// 创建账号
        /// </summary>
        [Description("创建账号")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string CREATEUSERNAME { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string CREATEUSER { get; set; }

        /// <summary>
        /// 创建日期
        /// </summary>
        [Description("创建日期")]
        public DateTime? CREATEDATE { get; set; }

        /// <summary>
        /// 完成日期
        /// </summary>
        [Description("完成时间")]
        public DateTime? FINISHDATE { get; set; }

        /// <summary>
        /// 程序名
        /// </summary>
        [Description("程序名")]
        [Column(DbType = DbType.AnsiString, Size = 100)]
        public string APPNAME { get; set; }

    }
}