//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;
using System;
using System.ComponentModel;
using System.Data;

namespace Gksyb.Model.WorkFlow
{
    /// <summary>
    /// 流程任务日志
    /// </summary>
    [Table("WF_TASK_LOG")]
    public class WF_TASK_LOG
    {

        /// <summary>
        /// 编号
        /// </summary>
        [Description("编号")]
        [Column(IsPrimaryKey = true)]
        public long? ID { get; set; }

        /// <summary>
        /// 任务编号
        /// </summary>
        [Description("任务编号")]
        [Column(DbType = DbType.AnsiString)]
        public string TASK_ID { get; set; }

        /// <summary>
        /// 节点主键
        /// </summary>
        [Description("节点主键")]
        [Column(DbType = DbType.AnsiString)]
        public string WF_NODE_ID { get; set; }

        /// <summary>
        /// 节点编号
        /// </summary>
        [Description("节点编号")]
        [Column(DbType = DbType.AnsiString)]
        public string NODE_ID { get; set; }

        /// <summary>
        /// 操作人
        /// </summary>
        [Description("操作人")]
        [Column(DbType = DbType.AnsiString)]
        public string OPERATOR { get; set; }

        /// <summary>
        /// 操作类型
        /// </summary>
        [Description("操作类型")]
        [Column(DbType = DbType.AnsiString)]
        public string OPERTYPE { get; set; }

        /// <summary>
        /// 操作标题
        /// </summary>
        [Description("操作标题")]
        [Column(DbType = DbType.AnsiString)]
        public string OPERTITLE { get; set; }

        /// <summary>
        /// 操作明细
        /// </summary>
        [Description("操作明细")]
        [Column(DbType = DbType.AnsiString)]
        public string OPERDETAIL { get; set; }

        /// <summary>
        /// 操作日期
        /// </summary>
        [Description("操作日期")]
        public DateTime? OPERDATE { get; set; }

    }
}