//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using Chloe.Annotations;

namespace Gksyb.Model.Core
{
    /// <summary>
    /// 实体类CF_USER
    /// </summary>
    [NotMapped]
    public class UserRequest : CF_USER
    {
        /// <summary>
        /// 角色
        /// </summary>
        public string ROLE { get; set; }
        /// <summary>
        /// 用户公司
        /// </summary>
        public string CORP { get; set; }

        /// <summary>
        /// 用户公司岗位
        /// </summary>
        public Dictionary<string,string> CorpStation { get; set; }

        /// <summary>
        /// 角色归属公司
        /// </summary>
        public Dictionary<string, string> RoleCorp { get; set; }
    }
}